/* eslint-disable isaacscript/format-line-comments */

// THIS CODE WAS AUTOMATICALLY GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
// YOU CAN REGENERATE IT USING:
// npm run generate:configs

export const all = {
  plugins: ["isaacscript"],
  rules: {
    "@typescript-eslint/member-ordering": "off",
    eqeqeq: "off",
    "no-template-curly-in-string": "off",
    "no-useless-return": "off",
    "isaacscript/complete-sentences-jsdoc": "error",
    "isaacscript/complete-sentences-line-comments": "error",
    "isaacscript/enum-member-number-separation": "error",
    "isaacscript/eqeqeq-fix": "error",
    "isaacscript/format-jsdoc-comments": "error",
    "isaacscript/format-line-comments": "error",
    "isaacscript/member-ordering": "error",
    "isaacscript/no-empty-jsdoc": "error",
    "isaacscript/no-explicit-array-loops": "error",
    "isaacscript/no-implicit-map-set-loops": "error",
    "isaacscript/no-let-any": "error",
    "isaacscript/no-object-any": "error",
    "isaacscript/no-template-curly-in-string-fix": "error",
    "isaacscript/no-useless-return-no-fix": "error",
    "isaacscript/no-void-return-type": "error",
    "isaacscript/strict-enums": "error",
  },
};
