/* eslint-disable isaacscript/format-line-comments */

// THIS CODE WAS AUTOMATICALLY GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
// YOU CAN REGENERATE IT USING:
// yarn run generate:configs

export const all = {
  plugins: ["isaacscript"],
  rules: {
    eqeqeq: "off",
    "no-template-curly-in-string": "off",
    "isaacscript/complete-sentences-jsdoc": "recommended",
    "isaacscript/complete-sentences-line-comments": "recommended",
    "isaacscript/eqeqeq-fix": "recommended",
    "isaacscript/format-jsdoc-comments": "recommended",
    "isaacscript/format-line-comments": "recommended",
    "isaacscript/jsdoc-code-block-language": "recommended",
    "isaacscript/no-confusing-set-methods": "recommended",
    "isaacscript/no-empty-jsdoc": "recommended",
    "isaacscript/no-empty-line-comments": "recommended",
    "isaacscript/no-explicit-array-loops": "recommended",
    "isaacscript/no-explicit-map-set-loops": "recommended",
    "isaacscript/no-let-any": "recommended",
    "isaacscript/no-object-any": "recommended",
    "isaacscript/no-object-methods-with-map-set": "recommended",
    "isaacscript/no-template-curly-in-string-fix": "recommended",
    "isaacscript/no-unsafe-plusplus": "recommended",
    "isaacscript/no-void-return-type": "recommended",
    "isaacscript/prefer-plusplus": "recommended",
    "isaacscript/prefer-postfix-plusplus": "recommended",
    "isaacscript/require-capital-const-assertions": "recommended",
    "isaacscript/require-capital-read-only": "recommended",
    "isaacscript/require-variadic-function-argument": "recommended",
    "isaacscript/strict-enums": "recommended",
  },
};
