/// THIS FILE IS AUTOMATICALLY GENERATED BY THE "generate.ts" SCRIPT.
/// DO NOT EDIT THIS FILE! YOU CAN REGENERATE IT WITH:
/// npm run generate

import type { TSESLint } from "@typescript-eslint/utils";

export const recommended: TSESLint.FlatConfig.ConfigArray = [
  {
    plugins: {},
    rules: { eqeqeq: "off", "no-template-curly-in-string": "off" },
  },
  {
    files: ["**/*.js", "**/*.cjs", "**/*.mjs", "**/*.jsx"],
    rules: {
      "isaacscript/no-let-any": "off",
      "isaacscript/no-object-any": "off",
      "isaacscript/require-capital-const-assertions": "off",
      "isaacscript/require-capital-read-only": "off",
    },
  },
];
