/* eslint-disable isaacscript/format-line-comments */

// THIS CODE WAS AUTOMATICALLY GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
// YOU CAN REGENERATE IT USING:
// yarn run generate:configs

export const recommended = {
  plugins: ["isaacscript"],
  rules: {
    "@typescript-eslint/member-ordering": "off",
    eqeqeq: "off",
    "no-template-curly-in-string": "off",
    "no-useless-return": "off",
    "isaacscript/complete-sentences-jsdoc": "error",
    "isaacscript/complete-sentences-line-comments": "error",
    "isaacscript/eqeqeq-fix": "error",
    "isaacscript/format-jsdoc-comments": "error",
    "isaacscript/format-line-comments": "error",
    "isaacscript/jsdoc-code-block-language": "error",
    "isaacscript/no-empty-jsdoc": "error",
    "isaacscript/no-explicit-array-loops": "error",
    "isaacscript/no-explicit-map-set-loops": "error",
    "isaacscript/no-let-any": "error",
    "isaacscript/no-object-any": "error",
    "isaacscript/no-template-curly-in-string-fix": "error",
    "isaacscript/no-unsafe-plusplus": "error",
    "isaacscript/no-useless-return-no-fix": "error",
    "isaacscript/no-void-return-type": "error",
    "isaacscript/prefer-plusplus": "error",
    "isaacscript/prefer-postfix-plusplus": "error",
    "isaacscript/require-const-assertions": "error",
    "isaacscript/strict-enums": "error",
  },
};
