/// THIS FILE IS AUTOMATICALLY GENERATED BY THE "generate.ts" SCRIPT.
/// DO NOT EDIT THIS FILE! YOU CAN REGENERATE IT WITH:
/// npm run generate

import type { TSESLint } from "@typescript-eslint/utils";

export const recommended: TSESLint.FlatConfig.ConfigArray = [
  {
    plugins: {},
    rules: {
      "isaacscript/enum-member-number-separation": "error",
      "isaacscript/no-invalid-default-map": "error",
      "isaacscript/no-throw": "error",
      "isaacscript/require-v-registration": "error",
    },
  },
];
