import { CardType, ItemConfigCardType } from "isaac-typescript-definitions";

export const DEFAULT_CARD_TYPE = ItemConfigCardType.MODDED;

export const CARD_TYPE_TO_ITEM_CONFIG_CARD_TYPE: {
  readonly [key in CardType]: ItemConfigCardType;
} = {
  [CardType.NULL]: ItemConfigCardType.NULL, // 0
  [CardType.FOOL]: ItemConfigCardType.TAROT, // 1
  [CardType.MAGICIAN]: ItemConfigCardType.TAROT, // 2
  [CardType.HIGH_PRIESTESS]: ItemConfigCardType.TAROT, // 3
  [CardType.EMPRESS]: ItemConfigCardType.TAROT, // 4
  [CardType.EMPEROR]: ItemConfigCardType.TAROT, // 5
  [CardType.HIEROPHANT]: ItemConfigCardType.TAROT, // 6
  [CardType.LOVERS]: ItemConfigCardType.TAROT, // 7
  [CardType.CHARIOT]: ItemConfigCardType.TAROT, // 8
  [CardType.JUSTICE]: ItemConfigCardType.TAROT, // 9
  [CardType.HERMIT]: ItemConfigCardType.TAROT, // 10
  [CardType.WHEEL_OF_FORTUNE]: ItemConfigCardType.TAROT, // 11
  [CardType.STRENGTH]: ItemConfigCardType.TAROT, // 12
  [CardType.HANGED_MAN]: ItemConfigCardType.TAROT, // 13
  [CardType.DEATH]: ItemConfigCardType.TAROT, // 14
  [CardType.TEMPERANCE]: ItemConfigCardType.TAROT, // 15
  [CardType.DEVIL]: ItemConfigCardType.TAROT, // 16
  [CardType.TOWER]: ItemConfigCardType.TAROT, // 17
  [CardType.STARS]: ItemConfigCardType.TAROT, // 18
  [CardType.MOON]: ItemConfigCardType.TAROT, // 19
  [CardType.SUN]: ItemConfigCardType.TAROT, // 20
  [CardType.JUDGEMENT]: ItemConfigCardType.TAROT, // 21
  [CardType.WORLD]: ItemConfigCardType.TAROT, // 22
  [CardType.CLUBS_2]: ItemConfigCardType.SUIT, // 23
  [CardType.DIAMONDS_2]: ItemConfigCardType.SUIT, // 24
  [CardType.SPADES_2]: ItemConfigCardType.SUIT, // 25
  [CardType.HEARTS_2]: ItemConfigCardType.SUIT, // 26
  [CardType.ACE_OF_CLUBS]: ItemConfigCardType.SUIT, // 27
  [CardType.ACE_OF_DIAMONDS]: ItemConfigCardType.SUIT, // 28
  [CardType.ACE_OF_SPADES]: ItemConfigCardType.SUIT, // 29
  [CardType.ACE_OF_HEARTS]: ItemConfigCardType.SUIT, // 30
  [CardType.JOKER]: ItemConfigCardType.SUIT, // 31
  [CardType.RUNE_HAGALAZ]: ItemConfigCardType.RUNE, // 32
  [CardType.RUNE_JERA]: ItemConfigCardType.RUNE, // 33
  [CardType.RUNE_EHWAZ]: ItemConfigCardType.RUNE, // 34
  [CardType.RUNE_DAGAZ]: ItemConfigCardType.RUNE, // 35
  [CardType.RUNE_ANSUZ]: ItemConfigCardType.RUNE, // 36
  [CardType.RUNE_PERTHRO]: ItemConfigCardType.RUNE, // 37
  [CardType.RUNE_BERKANO]: ItemConfigCardType.RUNE, // 38
  [CardType.RUNE_ALGIZ]: ItemConfigCardType.RUNE, // 39
  [CardType.RUNE_BLANK]: ItemConfigCardType.RUNE, // 40
  [CardType.RUNE_BLACK]: ItemConfigCardType.RUNE, // 41
  [CardType.CHAOS]: ItemConfigCardType.SPECIAL, // 42
  [CardType.CREDIT]: ItemConfigCardType.SPECIAL, // 43
  [CardType.RULES]: ItemConfigCardType.SPECIAL, // 44
  [CardType.AGAINST_HUMANITY]: ItemConfigCardType.SPECIAL, // 45
  [CardType.SUICIDE_KING]: ItemConfigCardType.SPECIAL, // 46
  [CardType.GET_OUT_OF_JAIL_FREE]: ItemConfigCardType.SPECIAL, // 47
  [CardType.QUESTION_MARK]: ItemConfigCardType.SPECIAL, // 48
  [CardType.DICE_SHARD]: ItemConfigCardType.SPECIAL_OBJECT, // 49
  [CardType.EMERGENCY_CONTACT]: ItemConfigCardType.SPECIAL_OBJECT, // 50
  [CardType.HOLY]: ItemConfigCardType.SPECIAL, // 51
  [CardType.HUGE_GROWTH]: ItemConfigCardType.SPECIAL, // 52
  [CardType.ANCIENT_RECALL]: ItemConfigCardType.SPECIAL, // 53
  [CardType.ERA_WALK]: ItemConfigCardType.SPECIAL, // 54
  [CardType.RUNE_SHARD]: ItemConfigCardType.RUNE, // 55
  [CardType.REVERSE_FOOL]: ItemConfigCardType.TAROT_REVERSE, // 56
  [CardType.REVERSE_MAGICIAN]: ItemConfigCardType.TAROT_REVERSE, // 57
  [CardType.REVERSE_HIGH_PRIESTESS]: ItemConfigCardType.TAROT_REVERSE, // 58
  [CardType.REVERSE_EMPRESS]: ItemConfigCardType.TAROT_REVERSE, // 59
  [CardType.REVERSE_EMPEROR]: ItemConfigCardType.TAROT_REVERSE, // 60
  [CardType.REVERSE_HIEROPHANT]: ItemConfigCardType.TAROT_REVERSE, // 61
  [CardType.REVERSE_LOVERS]: ItemConfigCardType.TAROT_REVERSE, // 62
  [CardType.REVERSE_CHARIOT]: ItemConfigCardType.TAROT_REVERSE, // 63
  [CardType.REVERSE_JUSTICE]: ItemConfigCardType.TAROT_REVERSE, // 64
  [CardType.REVERSE_HERMIT]: ItemConfigCardType.TAROT_REVERSE, // 65
  [CardType.REVERSE_WHEEL_OF_FORTUNE]: ItemConfigCardType.TAROT_REVERSE, // 66
  [CardType.REVERSE_STRENGTH]: ItemConfigCardType.TAROT_REVERSE, // 67
  [CardType.REVERSE_HANGED_MAN]: ItemConfigCardType.TAROT_REVERSE, // 68
  [CardType.REVERSE_DEATH]: ItemConfigCardType.TAROT_REVERSE, // 69
  [CardType.REVERSE_TEMPERANCE]: ItemConfigCardType.TAROT_REVERSE, // 70
  [CardType.REVERSE_DEVIL]: ItemConfigCardType.TAROT_REVERSE, // 71
  [CardType.REVERSE_TOWER]: ItemConfigCardType.TAROT_REVERSE, // 72
  [CardType.REVERSE_STARS]: ItemConfigCardType.TAROT_REVERSE, // 73
  [CardType.REVERSE_MOON]: ItemConfigCardType.TAROT_REVERSE, // 74
  [CardType.REVERSE_SUN]: ItemConfigCardType.TAROT_REVERSE, // 75
  [CardType.REVERSE_JUDGEMENT]: ItemConfigCardType.TAROT_REVERSE, // 76
  [CardType.REVERSE_WORLD]: ItemConfigCardType.TAROT_REVERSE, // 77
  [CardType.CRACKED_KEY]: ItemConfigCardType.SPECIAL_OBJECT, // 78
  [CardType.QUEEN_OF_HEARTS]: ItemConfigCardType.SUIT, // 79
  [CardType.WILD]: ItemConfigCardType.SPECIAL, // 80
  [CardType.SOUL_ISAAC]: ItemConfigCardType.RUNE, // 81
  [CardType.SOUL_MAGDALENE]: ItemConfigCardType.RUNE, // 82
  [CardType.SOUL_CAIN]: ItemConfigCardType.RUNE, // 83
  [CardType.SOUL_JUDAS]: ItemConfigCardType.RUNE, // 84
  [CardType.SOUL_BLUE_BABY]: ItemConfigCardType.RUNE, // 85
  [CardType.SOUL_EVE]: ItemConfigCardType.RUNE, // 86
  [CardType.SOUL_SAMSON]: ItemConfigCardType.RUNE, // 87
  [CardType.SOUL_AZAZEL]: ItemConfigCardType.RUNE, // 88
  [CardType.SOUL_LAZARUS]: ItemConfigCardType.RUNE, // 89
  [CardType.SOUL_EDEN]: ItemConfigCardType.RUNE, // 90
  [CardType.SOUL_LOST]: ItemConfigCardType.RUNE, // 91
  [CardType.SOUL_LILITH]: ItemConfigCardType.RUNE, // 92
  [CardType.SOUL_KEEPER]: ItemConfigCardType.RUNE, // 93
  [CardType.SOUL_APOLLYON]: ItemConfigCardType.RUNE, // 94
  [CardType.SOUL_FORGOTTEN]: ItemConfigCardType.RUNE, // 95
  [CardType.SOUL_BETHANY]: ItemConfigCardType.RUNE, // 96
  [CardType.SOUL_JACOB]: ItemConfigCardType.RUNE, // 97
} as const;
