import { CollectibleType } from "isaac-typescript-definitions";

export const DEFAULT_COLLECTIBLE_NAME = "Unknown";

/**
 * Maps collectible types to the real English names from the "stringtable.sta" file.
 *
 * For a mapping of name to `CollectibleType`, see `COLLECTIBLE_NAME_TO_TYPE_MAP`.
 */
export const COLLECTIBLE_NAMES = {
  [CollectibleType.NULL]: DEFAULT_COLLECTIBLE_NAME,
  [CollectibleType.SAD_ONION]: "The Sad Onion",
  [CollectibleType.INNER_EYE]: "The Inner Eye",
  [CollectibleType.SPOON_BENDER]: "Spoon Bender",
  [CollectibleType.CRICKETS_HEAD]: "Cricket's Head",
  [CollectibleType.MY_REFLECTION]: "My Reflection",
  [CollectibleType.NUMBER_ONE]: "Number One",
  [CollectibleType.BLOOD_OF_THE_MARTYR]: "Blood of the Martyr",
  [CollectibleType.BROTHER_BOBBY]: "Brother Bobby",
  [CollectibleType.SKATOLE]: "Skatole",
  [CollectibleType.HALO_OF_FLIES]: "Halo of Flies",
  [CollectibleType.ONE_UP]: "1up!",
  [CollectibleType.MAGIC_MUSHROOM]: "Magic Mushroom",
  [CollectibleType.VIRUS]: "The Virus",
  [CollectibleType.ROID_RAGE]: "Roid Rage",
  [CollectibleType.HEART]: "<3",
  [CollectibleType.RAW_LIVER]: "Raw Liver",
  [CollectibleType.SKELETON_KEY]: "Skeleton Key",
  [CollectibleType.DOLLAR]: "A Dollar",
  [CollectibleType.BOOM]: "Boom!",
  [CollectibleType.TRANSCENDENCE]: "Transcendence",
  [CollectibleType.COMPASS]: "The Compass",
  [CollectibleType.LUNCH]: "Lunch",
  [CollectibleType.DINNER]: "Dinner",
  [CollectibleType.DESSERT]: "Dessert",
  [CollectibleType.BREAKFAST]: "Breakfast",
  [CollectibleType.ROTTEN_MEAT]: "Rotten Meat",
  [CollectibleType.WOODEN_SPOON]: "Wooden Spoon",
  [CollectibleType.BELT]: "The Belt",
  [CollectibleType.MOMS_UNDERWEAR]: "Mom's Underwear",
  [CollectibleType.MOMS_HEELS]: "Mom's Heels",
  [CollectibleType.MOMS_LIPSTICK]: "Mom's Lipstick",
  [CollectibleType.WIRE_COAT_HANGER]: "Wire Coat Hanger",
  [CollectibleType.BIBLE]: "The Bible",
  [CollectibleType.BOOK_OF_BELIAL]: "The Book of Belial",
  [CollectibleType.NECRONOMICON]: "The Necronomicon",
  [CollectibleType.POOP]: "The Poop",
  [CollectibleType.MR_BOOM]: "Mr. Boom",
  [CollectibleType.TAMMYS_HEAD]: "Tammy's Head",
  [CollectibleType.MOMS_BRA]: "Mom's Bra",
  [CollectibleType.KAMIKAZE]: "Kamikaze!",
  [CollectibleType.MOMS_PAD]: "Mom's Pad",
  [CollectibleType.BOBS_ROTTEN_HEAD]: "Bob's Rotten Head",
  // There is no `CollectibleType` with a value of 43.
  [CollectibleType.TELEPORT]: "Teleport!",
  [CollectibleType.YUM_HEART]: "Yum Heart",
  [CollectibleType.LUCKY_FOOT]: "Lucky Foot",
  [CollectibleType.DOCTORS_REMOTE]: "Doctor's Remote",
  [CollectibleType.CUPIDS_ARROW]: "Cupid's Arrow",
  [CollectibleType.SHOOP_DA_WHOOP]: "Shoop da Whoop!",
  [CollectibleType.STEVEN]: "Steven",
  [CollectibleType.PENTAGRAM]: "Pentagram",
  [CollectibleType.DR_FETUS]: "Dr. Fetus",
  [CollectibleType.MAGNETO]: "Magneto",
  [CollectibleType.TREASURE_MAP]: "Treasure Map",
  [CollectibleType.MOMS_EYE]: "Mom's Eye",
  [CollectibleType.LEMON_MISHAP]: "Lemon Mishap",
  [CollectibleType.DISTANT_ADMIRATION]: "Distant Admiration",
  [CollectibleType.BOOK_OF_SHADOWS]: "Book of Shadows",
  [CollectibleType.BOOK_OF_BELIAL_BIRTHRIGHT]: "The Book of Belial",
  [CollectibleType.LADDER]: "The Ladder",
  // There is no `CollectibleType` with a value of 61.
  [CollectibleType.CHARM_OF_THE_VAMPIRE]: "Charm of the Vampire",
  [CollectibleType.BATTERY]: "The Battery",
  [CollectibleType.STEAM_SALE]: "Steam Sale",
  [CollectibleType.ANARCHIST_COOKBOOK]: "Anarchist Cookbook",
  [CollectibleType.HOURGLASS]: "The Hourglass",
  [CollectibleType.SISTER_MAGGY]: "Sister Maggy",
  [CollectibleType.TECHNOLOGY]: "Technology",
  [CollectibleType.CHOCOLATE_MILK]: "Chocolate Milk",
  [CollectibleType.GROWTH_HORMONES]: "Growth Hormones",
  [CollectibleType.MINI_MUSH]: "Mini Mush",
  [CollectibleType.ROSARY]: "Rosary",
  [CollectibleType.CUBE_OF_MEAT]: "Cube of Meat",
  [CollectibleType.QUARTER]: "A Quarter",
  [CollectibleType.PHD]: "PHD",
  [CollectibleType.XRAY_VISION]: "X-Ray Vision",
  [CollectibleType.MY_LITTLE_UNICORN]: "My Little Unicorn",
  [CollectibleType.BOOK_OF_REVELATIONS]: "Book of Revelations",
  [CollectibleType.MARK]: "The Mark",
  [CollectibleType.PACT]: "The Pact",
  [CollectibleType.DEAD_CAT]: "Dead Cat",
  [CollectibleType.LORD_OF_THE_PIT]: "Lord of the Pit",
  [CollectibleType.NAIL]: "The Nail",
  [CollectibleType.WE_NEED_TO_GO_DEEPER]: "We Need To Go Deeper!",
  [CollectibleType.DECK_OF_CARDS]: "Deck of Cards",
  [CollectibleType.MONSTROS_TOOTH]: "Monstro's Tooth",
  [CollectibleType.LOKIS_HORNS]: "Loki's Horns",
  [CollectibleType.LITTLE_CHUBBY]: "Little Chubby",
  [CollectibleType.SPIDER_BITE]: "Spider Bite",
  [CollectibleType.SMALL_ROCK]: "The Small Rock",
  [CollectibleType.SPELUNKER_HAT]: "Spelunker Hat",
  [CollectibleType.SUPER_BANDAGE]: "Super Bandage",
  [CollectibleType.GAMEKID]: "The Gamekid",
  [CollectibleType.SACK_OF_PENNIES]: "Sack of Pennies",
  [CollectibleType.ROBO_BABY]: "Robo-Baby",
  [CollectibleType.LITTLE_CHAD]: "Little C.H.A.D.",
  [CollectibleType.BOOK_OF_SIN]: "The Book of Sin",
  [CollectibleType.RELIC]: "The Relic",
  [CollectibleType.LITTLE_GISH]: "Little Gish",
  [CollectibleType.LITTLE_STEVEN]: "Little Steven",
  [CollectibleType.HALO]: "The Halo",
  [CollectibleType.MOMS_BOTTLE_OF_PILLS]: "Mom's Bottle of Pills",
  [CollectibleType.COMMON_COLD]: "The Common Cold",
  [CollectibleType.PARASITE]: "The Parasite",
  [CollectibleType.D6]: "The D6",
  [CollectibleType.MR_MEGA]: "Mr. Mega",
  [CollectibleType.PINKING_SHEARS]: "The Pinking Shears",
  [CollectibleType.WAFER]: "The Wafer",
  [CollectibleType.MONEY_EQUALS_POWER]: "Money = Power",
  [CollectibleType.MOMS_CONTACTS]: "Mom's Contacts",
  [CollectibleType.BEAN]: "The Bean",
  [CollectibleType.GUARDIAN_ANGEL]: "Guardian Angel",
  [CollectibleType.DEMON_BABY]: "Demon Baby",
  [CollectibleType.MOMS_KNIFE]: "Mom's Knife",
  [CollectibleType.OUIJA_BOARD]: "Ouija Board",
  [CollectibleType.NINE_VOLT]: "9 Volt",
  [CollectibleType.DEAD_BIRD]: "Dead Bird",
  [CollectibleType.BRIMSTONE]: "Brimstone",
  [CollectibleType.BLOOD_BAG]: "Blood Bag",
  [CollectibleType.ODD_MUSHROOM_THIN]: "Odd Mushroom",
  [CollectibleType.ODD_MUSHROOM_LARGE]: "Odd Mushroom",
  [CollectibleType.WHORE_OF_BABYLON]: "Whore of Babylon",
  [CollectibleType.MONSTER_MANUAL]: "Monster Manual",
  [CollectibleType.DEAD_SEA_SCROLLS]: "Dead Sea Scrolls",
  [CollectibleType.BOBBY_BOMB]: "Bobby-Bomb",
  [CollectibleType.RAZOR_BLADE]: "Razor Blade",
  [CollectibleType.FORGET_ME_NOW]: "Forget Me Now",
  [CollectibleType.FOREVER_ALONE]: "Forever Alone",
  [CollectibleType.BUCKET_OF_LARD]: "Bucket of Lard",
  [CollectibleType.PONY]: "A Pony",
  [CollectibleType.BOMB_BAG]: "Bomb Bag",
  [CollectibleType.LUMP_OF_COAL]: "A Lump of Coal",
  [CollectibleType.GUPPYS_PAW]: "Guppy's Paw",
  [CollectibleType.GUPPYS_TAIL]: "Guppy's Tail",
  [CollectibleType.IV_BAG]: "IV Bag",
  [CollectibleType.BEST_FRIEND]: "Best Friend",
  [CollectibleType.REMOTE_DETONATOR]: "Remote Detonator",
  [CollectibleType.STIGMATA]: "Stigmata",
  [CollectibleType.MOMS_PURSE]: "Mom's Purse",
  [CollectibleType.BOBS_CURSE]: "Bob's Curse",
  [CollectibleType.PAGEANT_BOY]: "Pageant Boy",
  [CollectibleType.SCAPULAR]: "Scapular",
  [CollectibleType.SPEED_BALL]: "Speed Ball",
  [CollectibleType.BUM_FRIEND]: "Bum Friend",
  [CollectibleType.GUPPYS_HEAD]: "Guppy's Head",
  [CollectibleType.PRAYER_CARD]: "Prayer Card",
  [CollectibleType.NOTCHED_AXE]: "Notched Axe",
  [CollectibleType.INFESTATION]: "Infestation",
  [CollectibleType.IPECAC]: "Ipecac",
  [CollectibleType.TOUGH_LOVE]: "Tough Love",
  [CollectibleType.MULLIGAN]: "The Mulligan",
  [CollectibleType.TECHNOLOGY_2]: "Technology 2",
  [CollectibleType.MUTANT_SPIDER]: "Mutant Spider",
  [CollectibleType.CHEMICAL_PEEL]: "Chemical Peel",
  [CollectibleType.PEEPER]: "The Peeper",
  [CollectibleType.HABIT]: "Habit",
  [CollectibleType.BLOODY_LUST]: "Bloody Lust",
  [CollectibleType.CRYSTAL_BALL]: "Crystal Ball",
  [CollectibleType.SPIRIT_OF_THE_NIGHT]: "Spirit of the Night",
  [CollectibleType.CRACK_THE_SKY]: "Crack the Sky",
  [CollectibleType.ANKH]: "Ankh",
  [CollectibleType.CELTIC_CROSS]: "Celtic Cross",
  [CollectibleType.GHOST_BABY]: "Ghost Baby",
  [CollectibleType.CANDLE]: "The Candle",
  [CollectibleType.CAT_O_NINE_TAILS]: "Cat-o-nine-tails",
  [CollectibleType.D20]: "D20",
  [CollectibleType.HARLEQUIN_BABY]: "Harlequin Baby",
  [CollectibleType.EPIC_FETUS]: "Epic Fetus",
  [CollectibleType.POLYPHEMUS]: "Polyphemus",
  [CollectibleType.DADDY_LONGLEGS]: "Daddy Longlegs",
  [CollectibleType.SPIDER_BUTT]: "Spider Butt",
  [CollectibleType.SACRIFICIAL_DAGGER]: "Sacrificial Dagger",
  [CollectibleType.MITRE]: "Mitre",
  [CollectibleType.RAINBOW_BABY]: "Rainbow Baby",
  [CollectibleType.DADS_KEY]: "Dad's Key",
  [CollectibleType.STEM_CELLS]: "Stem Cells",
  [CollectibleType.PORTABLE_SLOT]: "Portable Slot",
  [CollectibleType.HOLY_WATER]: "Holy Water",
  [CollectibleType.FATE]: "Fate",
  [CollectibleType.BLACK_BEAN]: "The Black Bean",
  [CollectibleType.WHITE_PONY]: "White Pony",
  [CollectibleType.SACRED_HEART]: "Sacred Heart",
  [CollectibleType.TOOTH_PICKS]: "Tooth Picks",
  [CollectibleType.HOLY_GRAIL]: "Holy Grail",
  [CollectibleType.DEAD_DOVE]: "Dead Dove",
  [CollectibleType.BLOOD_RIGHTS]: "Blood Rights",
  [CollectibleType.GUPPYS_HAIRBALL]: "Guppy's Hairball",
  [CollectibleType.ABEL]: "Abel",
  [CollectibleType.SMB_SUPER_FAN]: "SMB Super Fan",
  [CollectibleType.PYRO]: "Pyro",
  [CollectibleType.THREE_DOLLAR_BILL]: "3 Dollar Bill",
  [CollectibleType.TELEPATHY_BOOK]: "Telepathy For Dummies",
  [CollectibleType.MEAT]: "MEAT!",
  [CollectibleType.MAGIC_8_BALL]: "Magic 8 Ball",
  [CollectibleType.MOMS_COIN_PURSE]: "Mom's Coin Purse",
  [CollectibleType.SQUEEZY]: "Squeezy",
  [CollectibleType.JESUS_JUICE]: "Jesus Juice",
  [CollectibleType.BOX]: "Box",
  [CollectibleType.MOMS_KEY]: "Mom's Key",
  [CollectibleType.MOMS_EYESHADOW]: "Mom's Eyeshadow",
  [CollectibleType.IRON_BAR]: "Iron Bar",
  [CollectibleType.MIDAS_TOUCH]: "Midas' Touch",
  [CollectibleType.HUMBLING_BUNDLE]: "Humbleing Bundle",
  [CollectibleType.FANNY_PACK]: "Fanny Pack",
  [CollectibleType.SHARP_PLUG]: "Sharp Plug",
  [CollectibleType.GUILLOTINE]: "Guillotine",
  [CollectibleType.BALL_OF_BANDAGES]: "Ball of Bandages",
  [CollectibleType.CHAMPION_BELT]: "Champion Belt",
  [CollectibleType.BUTT_BOMBS]: "Butt Bombs",
  [CollectibleType.GNAWED_LEAF]: "Gnawed Leaf",
  [CollectibleType.SPIDERBABY]: "Spiderbaby",
  [CollectibleType.GUPPYS_COLLAR]: "Guppy's Collar",
  [CollectibleType.LOST_CONTACT]: "Lost Contact",
  [CollectibleType.ANEMIC]: "Anemic",
  [CollectibleType.GOAT_HEAD]: "Goat Head",
  [CollectibleType.CEREMONIAL_ROBES]: "Ceremonial Robes",
  [CollectibleType.MOMS_WIG]: "Mom's Wig",
  [CollectibleType.PLACENTA]: "Placenta",
  [CollectibleType.OLD_BANDAGE]: "Old Bandage",
  [CollectibleType.SAD_BOMBS]: "Sad Bombs",
  [CollectibleType.RUBBER_CEMENT]: "Rubber Cement",
  [CollectibleType.ANTI_GRAVITY]: "Anti-Gravity",
  [CollectibleType.PYROMANIAC]: "Pyromaniac",
  [CollectibleType.CRICKETS_BODY]: "Cricket's Body",
  [CollectibleType.GIMPY]: "Gimpy",
  [CollectibleType.BLACK_LOTUS]: "Black Lotus",
  [CollectibleType.PIGGY_BANK]: "Piggy Bank",
  [CollectibleType.MOMS_PERFUME]: "Mom's Perfume",
  [CollectibleType.MONSTROS_LUNG]: "Monstro's Lung",
  [CollectibleType.ABADDON]: "Abaddon",
  [CollectibleType.BALL_OF_TAR]: "Ball of Tar",
  [CollectibleType.STOP_WATCH]: "Stop Watch",
  [CollectibleType.TINY_PLANET]: "Tiny Planet",
  [CollectibleType.INFESTATION_2]: "Infestation 2",
  // There is no `CollectibleType` with a value of 235.
  [CollectibleType.E_COLI]: "E. Coli",
  [CollectibleType.DEATHS_TOUCH]: "Death's Touch",
  [CollectibleType.KEY_PIECE_1]: "Key Piece 1",
  [CollectibleType.KEY_PIECE_2]: "Key Piece 2",
  [CollectibleType.EXPERIMENTAL_TREATMENT]: "Experimental Treatment",
  [CollectibleType.CONTRACT_FROM_BELOW]: "Contract from Below",
  [CollectibleType.INFAMY]: "Infamy",
  [CollectibleType.TRINITY_SHIELD]: "Trinity Shield",
  [CollectibleType.TECH_5]: "Tech.5",
  [CollectibleType.TWENTY_TWENTY]: "20/20",
  [CollectibleType.BLUE_MAP]: "Blue Map",
  [CollectibleType.BFFS]: "BFFS!",
  [CollectibleType.HIVE_MIND]: "Hive Mind",
  [CollectibleType.THERES_OPTIONS]: "There's Options",
  [CollectibleType.BOGO_BOMBS]: "BOGO Bombs",
  [CollectibleType.STARTER_DECK]: "Starter Deck",
  [CollectibleType.LITTLE_BAGGY]: "Little Baggy",
  [CollectibleType.MAGIC_SCAB]: "Magic Scab",
  [CollectibleType.BLOOD_CLOT]: "Blood Clot",
  [CollectibleType.SCREW]: "Screw",
  [CollectibleType.HOT_BOMBS]: "Hot Bombs",
  [CollectibleType.FIRE_MIND]: "Fire Mind",
  [CollectibleType.MISSING_NO]: "Missing No.",
  [CollectibleType.DARK_MATTER]: "Dark Matter",
  [CollectibleType.BLACK_CANDLE]: "Black Candle",
  [CollectibleType.PROPTOSIS]: "Proptosis",
  [CollectibleType.MISSING_PAGE_2]: "Missing Page 2",
  [CollectibleType.CLEAR_RUNE]: "Clear Rune",
  [CollectibleType.SMART_FLY]: "Smart Fly",
  [CollectibleType.DRY_BABY]: "Dry Baby",
  [CollectibleType.JUICY_SACK]: "Juicy Sack",
  [CollectibleType.ROBO_BABY_2]: "Robo-Baby 2.0",
  [CollectibleType.ROTTEN_BABY]: "Rotten Baby",
  [CollectibleType.HEADLESS_BABY]: "Headless Baby",
  [CollectibleType.LEECH]: "Leech",
  [CollectibleType.MYSTERY_SACK]: "Mystery Sack",
  [CollectibleType.BBF]: "BBF",
  [CollectibleType.BOBS_BRAIN]: "Bob's Brain",
  [CollectibleType.BEST_BUD]: "Best Bud",
  [CollectibleType.LIL_BRIMSTONE]: "Lil Brimstone",
  [CollectibleType.ISAACS_HEART]: "Isaac's Heart",
  [CollectibleType.LIL_HAUNT]: "Lil Haunt",
  [CollectibleType.DARK_BUM]: "Dark Bum",
  [CollectibleType.BIG_FAN]: "Big Fan",
  [CollectibleType.SISSY_LONGLEGS]: "Sissy Longlegs",
  [CollectibleType.PUNCHING_BAG]: "Punching Bag",
  [CollectibleType.HOW_TO_JUMP]: "How to Jump",
  [CollectibleType.D100]: "D100",
  [CollectibleType.D4]: "D4",
  [CollectibleType.D10]: "D10",
  [CollectibleType.BLANK_CARD]: "Blank Card",
  [CollectibleType.BOOK_OF_SECRETS]: "Book of Secrets",
  [CollectibleType.BOX_OF_SPIDERS]: "Box of Spiders",
  [CollectibleType.RED_CANDLE]: "Red Candle",
  [CollectibleType.JAR]: "The Jar",
  [CollectibleType.FLUSH]: "Flush!",
  [CollectibleType.SATANIC_BIBLE]: "Satanic Bible",
  [CollectibleType.HEAD_OF_KRAMPUS]: "Head of Krampus",
  [CollectibleType.BUTTER_BEAN]: "Butter Bean",
  [CollectibleType.MAGIC_FINGERS]: "Magic Fingers",
  [CollectibleType.CONVERTER]: "Converter",
  [CollectibleType.BLUE_BOX]: "Pandora's Box",
  [CollectibleType.UNICORN_STUMP]: "Unicorn Stump",
  [CollectibleType.TAURUS]: "Taurus",
  [CollectibleType.ARIES]: "Aries",
  [CollectibleType.CANCER]: "Cancer",
  [CollectibleType.LEO]: "Leo",
  [CollectibleType.VIRGO]: "Virgo",
  [CollectibleType.LIBRA]: "Libra",
  [CollectibleType.SCORPIO]: "Scorpio",
  [CollectibleType.SAGITTARIUS]: "Sagittarius",
  [CollectibleType.CAPRICORN]: "Capricorn",
  [CollectibleType.AQUARIUS]: "Aquarius",
  [CollectibleType.PISCES]: "Pisces",
  [CollectibleType.EVES_MASCARA]: "Eve's Mascara",
  [CollectibleType.JUDAS_SHADOW]: "Judas' Shadow",
  [CollectibleType.MAGGYS_BOW]: "Maggy's Bow",
  [CollectibleType.HOLY_MANTLE]: "Holy Mantle",
  [CollectibleType.THUNDER_THIGHS]: "Thunder Thighs",
  [CollectibleType.STRANGE_ATTRACTOR]: "Strange Attractor",
  [CollectibleType.CURSED_EYE]: "Cursed Eye",
  [CollectibleType.MYSTERIOUS_LIQUID]: "Mysterious Liquid",
  [CollectibleType.GEMINI]: "Gemini",
  [CollectibleType.CAINS_OTHER_EYE]: "Cain's Other Eye",
  [CollectibleType.BLUE_BABYS_ONLY_FRIEND]: "???'s Only Friend",
  [CollectibleType.SAMSONS_CHAINS]: "Samson's Chains",
  [CollectibleType.MONGO_BABY]: "Mongo Baby",
  [CollectibleType.ISAACS_TEARS]: "Isaac's Tears",
  [CollectibleType.UNDEFINED]: "Undefined",
  [CollectibleType.SCISSORS]: "Scissors",
  [CollectibleType.BREATH_OF_LIFE]: "Breath of Life",
  [CollectibleType.POLAROID]: "The Polaroid",
  [CollectibleType.NEGATIVE]: "The Negative",
  [CollectibleType.LUDOVICO_TECHNIQUE]: "The Ludovico Technique",
  [CollectibleType.SOY_MILK]: "Soy Milk",
  [CollectibleType.GODHEAD]: "Godhead",
  [CollectibleType.LAZARUS_RAGS]: "Lazarus' Rags",
  [CollectibleType.MIND]: "The Mind",
  [CollectibleType.BODY]: "The Body",
  [CollectibleType.SOUL]: "The Soul",
  [CollectibleType.DEAD_ONION]: "Dead Onion",
  [CollectibleType.BROKEN_WATCH]: "Broken Watch",
  [CollectibleType.BOOMERANG]: "The Boomerang",
  [CollectibleType.SAFETY_PIN]: "Safety Pin",
  [CollectibleType.CAFFEINE_PILL]: "Caffeine Pill",
  [CollectibleType.TORN_PHOTO]: "Torn Photo",
  [CollectibleType.BLUE_CAP]: "Blue Cap",
  [CollectibleType.LATCH_KEY]: "Latch Key",
  [CollectibleType.MATCH_BOOK]: "Match Book",
  [CollectibleType.SYNTHOIL]: "Synthoil",
  [CollectibleType.SNACK]: "A Snack",
  [CollectibleType.DIPLOPIA]: "Diplopia",
  [CollectibleType.PLACEBO]: "Placebo",
  [CollectibleType.WOODEN_NICKEL]: "Wooden Nickel",
  [CollectibleType.TOXIC_SHOCK]: "Toxic Shock",
  [CollectibleType.MEGA_BEAN]: "Mega Bean",
  [CollectibleType.GLASS_CANNON]: "Glass Cannon",
  [CollectibleType.BOMBER_BOY]: "Bomber Boy",
  [CollectibleType.CRACK_JACKS]: "Crack Jacks",
  [CollectibleType.MOMS_PEARLS]: "Mom's Pearls",
  [CollectibleType.CAR_BATTERY]: "Car Battery",
  [CollectibleType.BOX_OF_FRIENDS]: "Box of Friends",
  [CollectibleType.WIZ]: "The Wiz",
  [CollectibleType.EIGHT_INCH_NAILS]: "8 Inch Nails",
  [CollectibleType.INCUBUS]: "Incubus",
  [CollectibleType.FATES_REWARD]: "Fate's Reward",
  [CollectibleType.LIL_CHEST]: "Lil Chest",
  [CollectibleType.SWORN_PROTECTOR]: "Sworn Protector",
  [CollectibleType.FRIEND_ZONE]: "Friend Zone",
  [CollectibleType.LOST_FLY]: "Lost Fly",
  [CollectibleType.SCATTER_BOMBS]: "Scatter Bombs",
  [CollectibleType.STICKY_BOMBS]: "Sticky Bombs",
  [CollectibleType.EPIPHORA]: "Epiphora",
  [CollectibleType.CONTINUUM]: "Continuum",
  [CollectibleType.MR_DOLLY]: "Mr. Dolly",
  [CollectibleType.CURSE_OF_THE_TOWER]: "Curse of the Tower",
  [CollectibleType.CHARGED_BABY]: "Charged Baby",
  [CollectibleType.DEAD_EYE]: "Dead Eye",
  [CollectibleType.HOLY_LIGHT]: "Holy Light",
  [CollectibleType.HOST_HAT]: "Host Hat",
  [CollectibleType.RESTOCK]: "Restock",
  [CollectibleType.BURSTING_SACK]: "Bursting Sack",
  [CollectibleType.NUMBER_TWO]: "Number Two",
  [CollectibleType.PUPULA_DUPLEX]: "Pupula Duplex",
  [CollectibleType.PAY_TO_PLAY]: "Pay To Play",
  [CollectibleType.EDENS_BLESSING]: "Eden's Blessing",
  [CollectibleType.FRIEND_BALL]: "Friendly Ball",
  [CollectibleType.TEAR_DETONATOR]: "Tear Detonator",
  [CollectibleType.LIL_GURDY]: "Lil Gurdy",
  [CollectibleType.BUMBO]: "Bumbo",
  [CollectibleType.D12]: "D12",
  [CollectibleType.CENSER]: "Censer",
  [CollectibleType.KEY_BUM]: "Key Bum",
  [CollectibleType.RUNE_BAG]: "Rune Bag",
  [CollectibleType.SERAPHIM]: "Seraphim",
  [CollectibleType.BETRAYAL]: "Betrayal",
  [CollectibleType.ZODIAC]: "Zodiac",
  [CollectibleType.SERPENTS_KISS]: "Serpent's Kiss",
  [CollectibleType.MARKED]: "Marked",
  [CollectibleType.TECH_X]: "Tech X",
  [CollectibleType.VENTRICLE_RAZOR]: "Ventricle Razor",
  [CollectibleType.TRACTOR_BEAM]: "Tractor Beam",
  [CollectibleType.GODS_FLESH]: "God's Flesh",
  [CollectibleType.MAW_OF_THE_VOID]: "Maw of the Void",
  [CollectibleType.SPEAR_OF_DESTINY]: "Spear of Destiny",
  [CollectibleType.EXPLOSIVO]: "Explosivo",
  [CollectibleType.CHAOS]: "Chaos",
  [CollectibleType.SPIDER_MOD]: "Spider Mod",
  [CollectibleType.FARTING_BABY]: "Farting Baby",
  [CollectibleType.GB_BUG]: "GB Bug",
  [CollectibleType.D8]: "D8",
  [CollectibleType.PURITY]: "Purity",
  [CollectibleType.ATHAME]: "Athame",
  [CollectibleType.EMPTY_VESSEL]: "Empty Vessel",
  [CollectibleType.EVIL_EYE]: "Evil Eye",
  [CollectibleType.LUSTY_BLOOD]: "Lusty Blood",
  [CollectibleType.CAMBION_CONCEPTION]: "Cambion Conception",
  [CollectibleType.IMMACULATE_CONCEPTION]: "Immaculate Conception",
  [CollectibleType.MORE_OPTIONS]: "More Options",
  [CollectibleType.CROWN_OF_LIGHT]: "Crown of Light",
  [CollectibleType.DEEP_POCKETS]: "Deep Pockets",
  [CollectibleType.SUCCUBUS]: "Succubus",
  [CollectibleType.FRUIT_CAKE]: "Fruit Cake",
  [CollectibleType.TELEPORT_2]: "Teleport 2.0",
  [CollectibleType.BLACK_POWDER]: "Black Powder",
  [CollectibleType.KIDNEY_BEAN]: "Kidney Bean",
  [CollectibleType.GLOWING_HOUR_GLASS]: "Glowing Hourglass",
  [CollectibleType.CIRCLE_OF_PROTECTION]: "Circle of Protection",
  [CollectibleType.SACK_HEAD]: "Sack Head",
  [CollectibleType.NIGHT_LIGHT]: "Night Light",
  [CollectibleType.OBSESSED_FAN]: "Obsessed Fan",
  [CollectibleType.MINE_CRAFTER]: "Mine Crafter",
  [CollectibleType.PJS]: "PJs",
  [CollectibleType.HEAD_OF_THE_KEEPER]: "Head of the Keeper",
  [CollectibleType.PAPA_FLY]: "Papa Fly",
  [CollectibleType.MULTIDIMENSIONAL_BABY]: "Multidimensional Baby",
  [CollectibleType.GLITTER_BOMBS]: "Glitter Bombs",
  [CollectibleType.MY_SHADOW]: "My Shadow",
  [CollectibleType.JAR_OF_FLIES]: "Jar of Flies",
  [CollectibleType.LIL_LOKI]: "Lil Loki",
  [CollectibleType.MILK]: "Milk!",
  [CollectibleType.D7]: "D7",
  [CollectibleType.BINKY]: "Binky",
  [CollectibleType.MOMS_BOX]: "Mom's Box",
  [CollectibleType.KIDNEY_STONE]: "Kidney Stone",
  [CollectibleType.MEGA_BLAST]: "Mega Blast",
  [CollectibleType.DARK_PRINCES_CROWN]: "Dark Prince's Crown",
  [CollectibleType.APPLE]: "Apple!",
  [CollectibleType.LEAD_PENCIL]: "Lead Pencil",
  [CollectibleType.DOG_TOOTH]: "Dog Tooth",
  [CollectibleType.DEAD_TOOTH]: "Dead Tooth",
  [CollectibleType.LINGER_BEAN]: "Linger Bean",
  [CollectibleType.SHARD_OF_GLASS]: "Shard of Glass",
  [CollectibleType.METAL_PLATE]: "Metal Plate",
  [CollectibleType.EYE_OF_GREED]: "Eye of Greed",
  [CollectibleType.TAROT_CLOTH]: "Tarot Cloth",
  [CollectibleType.VARICOSE_VEINS]: "Varicose Veins",
  [CollectibleType.COMPOUND_FRACTURE]: "Compound Fracture",
  [CollectibleType.POLYDACTYLY]: "Polydactyly",
  [CollectibleType.DADS_LOST_COIN]: "Dad's Lost Coin",
  [CollectibleType.MIDNIGHT_SNACK]: "Midnight Snack",
  [CollectibleType.CONE_HEAD]: "Cone Head",
  [CollectibleType.BELLY_BUTTON]: "Belly Button",
  [CollectibleType.SINUS_INFECTION]: "Sinus Infection",
  [CollectibleType.GLAUCOMA]: "Glaucoma",
  [CollectibleType.PARASITOID]: "Parasitoid",
  [CollectibleType.EYE_OF_BELIAL]: "Eye of Belial",
  [CollectibleType.SULFURIC_ACID]: "Sulfuric Acid",
  [CollectibleType.GLYPH_OF_BALANCE]: "Glyph of Balance",
  [CollectibleType.ANALOG_STICK]: "Analog Stick",
  [CollectibleType.CONTAGION]: "Contagion",
  [CollectibleType.FINGER]: "Finger!",
  [CollectibleType.SHADE]: "Shade",
  [CollectibleType.DEPRESSION]: "Depression",
  [CollectibleType.HUSHY]: "Hushy",
  [CollectibleType.LIL_MONSTRO]: "Lil Monstro",
  [CollectibleType.KING_BABY]: "King Baby",
  [CollectibleType.BIG_CHUBBY]: "Big Chubby",
  [CollectibleType.BROKEN_GLASS_CANNON]: "Broken Glass Cannon",
  [CollectibleType.PLAN_C]: "Plan C",
  [CollectibleType.D1]: "D1",
  [CollectibleType.VOID]: "Void",
  [CollectibleType.PAUSE]: "Pause",
  [CollectibleType.SMELTER]: "Smelter",
  [CollectibleType.COMPOST]: "Compost",
  [CollectibleType.DATAMINER]: "Dataminer",
  [CollectibleType.CLICKER]: "Clicker",
  [CollectibleType.MAMA_MEGA]: "Mama Mega!",
  [CollectibleType.WAIT_WHAT]: "Wait What?",
  [CollectibleType.CROOKED_PENNY]: "Crooked Penny",
  [CollectibleType.DULL_RAZOR]: "Dull Razor",
  [CollectibleType.POTATO_PEELER]: "Potato Peeler",
  [CollectibleType.METRONOME]: "Metronome",
  [CollectibleType.D_INFINITY]: "D infinity",
  [CollectibleType.EDENS_SOUL]: "Eden's Soul",
  [CollectibleType.ACID_BABY]: "Acid Baby",
  [CollectibleType.YO_LISTEN]: "YO LISTEN!",
  [CollectibleType.ADRENALINE]: "Adrenaline",
  [CollectibleType.JACOBS_LADDER]: "Jacob's Ladder",
  [CollectibleType.GHOST_PEPPER]: "Ghost Pepper",
  [CollectibleType.EUTHANASIA]: "Euthanasia",
  [CollectibleType.CAMO_UNDIES]: "Camo Undies",
  [CollectibleType.DUALITY]: "Duality",
  [CollectibleType.EUCHARIST]: "Eucharist",
  [CollectibleType.SACK_OF_SACKS]: "Sack of Sacks",
  [CollectibleType.GREEDS_GULLET]: "Greed's Gullet",
  [CollectibleType.LARGE_ZIT]: "Large Zit",
  [CollectibleType.LITTLE_HORN]: "Little Horn",
  [CollectibleType.BROWN_NUGGET]: "Brown Nugget",
  [CollectibleType.POKE_GO]: "Poke Go",
  [CollectibleType.BACKSTABBER]: "Backstabber",
  [CollectibleType.SHARP_STRAW]: "Sharp Straw",
  [CollectibleType.MOMS_RAZOR]: "Mom's Razor",
  [CollectibleType.BLOODSHOT_EYE]: "Bloodshot Eye",
  [CollectibleType.DELIRIOUS]: "Delirious",
  [CollectibleType.ANGRY_FLY]: "Angry Fly",
  [CollectibleType.BLACK_HOLE]: "Black Hole",
  [CollectibleType.BOZO]: "Bozo",
  [CollectibleType.BROKEN_MODEM]: "Broken Modem",
  [CollectibleType.MYSTERY_GIFT]: "Mystery Gift",
  [CollectibleType.SPRINKLER]: "Sprinkler",
  [CollectibleType.FAST_BOMBS]: "Fast Bombs",
  [CollectibleType.BUDDY_IN_A_BOX]: "Buddy in a Box",
  [CollectibleType.LIL_DELIRIUM]: "Lil Delirium",
  [CollectibleType.JUMPER_CABLES]: "Jumper Cables",
  [CollectibleType.COUPON]: "Coupon",
  [CollectibleType.TELEKINESIS]: "Telekinesis",
  [CollectibleType.MOVING_BOX]: "Moving Box",
  [CollectibleType.TECHNOLOGY_ZERO]: "Technology Zero",
  [CollectibleType.LEPROSY]: "Leprosy",
  [CollectibleType.SEVEN_SEALS]: "7 Seals",
  [CollectibleType.MR_ME]: "Mr. ME!",
  [CollectibleType.ANGELIC_PRISM]: "Angelic Prism",
  [CollectibleType.POP]: "Pop!",
  [CollectibleType.DEATHS_LIST]: "Death's List",
  [CollectibleType.HAEMOLACRIA]: "Haemolacria",
  [CollectibleType.LACHRYPHAGY]: "Lachryphagy",
  [CollectibleType.TRISAGION]: "Trisagion",
  [CollectibleType.SCHOOLBAG]: "Schoolbag",
  [CollectibleType.BLANKET]: "Blanket",
  [CollectibleType.SACRIFICIAL_ALTAR]: "Sacrificial Altar",
  [CollectibleType.LIL_SPEWER]: "Lil Spewer",
  [CollectibleType.MARBLES]: "Marbles",
  [CollectibleType.MYSTERY_EGG]: "Mystery Egg",
  [CollectibleType.FLAT_STONE]: "Flat Stone",
  [CollectibleType.MARROW]: "Marrow",
  [CollectibleType.SLIPPED_RIB]: "Slipped Rib",
  [CollectibleType.HALLOWED_GROUND]: "Hallowed Ground",
  [CollectibleType.POINTY_RIB]: "Pointy Rib",
  [CollectibleType.BOOK_OF_THE_DEAD]: "Book of the Dead",
  [CollectibleType.DADS_RING]: "Dad's Ring",
  [CollectibleType.DIVORCE_PAPERS]: "Divorce Papers",
  [CollectibleType.JAW_BONE]: "Jaw Bone",
  [CollectibleType.BRITTLE_BONES]: "Brittle Bones",
  [CollectibleType.BROKEN_SHOVEL_1]: "Broken Shovel",
  [CollectibleType.BROKEN_SHOVEL_2]: "Broken Shovel",
  [CollectibleType.MOMS_SHOVEL]: "Mom's Shovel",
  [CollectibleType.MUCORMYCOSIS]: "Mucormycosis",
  [CollectibleType.TWO_SPOOKY]: "2Spooky",
  [CollectibleType.GOLDEN_RAZOR]: "Golden Razor",
  [CollectibleType.SULFUR]: "Sulfur",
  [CollectibleType.FORTUNE_COOKIE]: "Fortune Cookie",
  [CollectibleType.EYE_SORE]: "Eye Sore",
  [CollectibleType.ONE_HUNDRED_TWENTY_VOLT]: "120 Volt",
  [CollectibleType.IT_HURTS]: "It Hurts",
  [CollectibleType.ALMOND_MILK]: "Almond Milk",
  [CollectibleType.ROCK_BOTTOM]: "Rock Bottom",
  [CollectibleType.NANCY_BOMBS]: "Nancy Bombs",
  [CollectibleType.BAR_OF_SOAP]: "A Bar of Soap",
  [CollectibleType.BLOOD_PUPPY]: "Blood Puppy",
  [CollectibleType.DREAM_CATCHER]: "Dream Catcher",
  [CollectibleType.PASCHAL_CANDLE]: "Paschal Candle",
  [CollectibleType.DIVINE_INTERVENTION]: "Divine Intervention",
  [CollectibleType.BLOOD_OATH]: "Blood Oath",
  [CollectibleType.PLAYDOUGH_COOKIE]: "Playdough Cookie",
  [CollectibleType.SOCKS]: "Orphan Socks",
  [CollectibleType.EYE_OF_THE_OCCULT]: "Eye of the Occult",
  [CollectibleType.IMMACULATE_HEART]: "Immaculate Heart",
  [CollectibleType.MONSTRANCE]: "Monstrance",
  [CollectibleType.INTRUDER]: "The Intruder",
  [CollectibleType.DIRTY_MIND]: "Dirty Mind",
  [CollectibleType.DAMOCLES]: "Damocles",
  [CollectibleType.FREE_LEMONADE]: "Free Lemonade",
  [CollectibleType.SPIRIT_SWORD]: "Spirit Sword",
  [CollectibleType.RED_KEY]: "Red Key",
  [CollectibleType.PSY_FLY]: "Psy Fly",
  [CollectibleType.WAVY_CAP]: "Wavy Cap",
  [CollectibleType.ROCKET_IN_A_JAR]: "Rocket in a Jar",
  [CollectibleType.BOOK_OF_VIRTUES]: "Book of Virtues",
  [CollectibleType.ALABASTER_BOX]: "Alabaster Box",
  [CollectibleType.STAIRWAY]: "The Stairway",
  // There is no `CollectibleType` with a value of 587.
  [CollectibleType.SOL]: "Sol",
  [CollectibleType.LUNA]: "Luna",
  [CollectibleType.MERCURIUS]: "Mercurius",
  [CollectibleType.VENUS]: "Venus",
  [CollectibleType.TERRA]: "Terra",
  [CollectibleType.MARS]: "Mars",
  [CollectibleType.JUPITER]: "Jupiter",
  [CollectibleType.SATURNUS]: "Saturnus",
  [CollectibleType.URANUS]: "Uranus",
  [CollectibleType.NEPTUNUS]: "Neptunus",
  [CollectibleType.PLUTO]: "Pluto",
  [CollectibleType.VOODOO_HEAD]: "Voodoo Head",
  [CollectibleType.EYE_DROPS]: "Eye Drops",
  [CollectibleType.ACT_OF_CONTRITION]: "Act of Contrition",
  [CollectibleType.MEMBER_CARD]: "Member Card",
  [CollectibleType.BATTERY_PACK]: "Battery Pack",
  [CollectibleType.MOMS_BRACELET]: "Mom's Bracelet",
  [CollectibleType.SCOOPER]: "The Scooper",
  [CollectibleType.OCULAR_RIFT]: "Ocular Rift",
  [CollectibleType.BOILED_BABY]: "Boiled Baby",
  [CollectibleType.FREEZER_BABY]: "Freezer Baby",
  [CollectibleType.ETERNAL_D6]: "Eternal D6",
  [CollectibleType.BIRD_CAGE]: "Bird Cage",
  [CollectibleType.LARYNX]: "Larynx",
  [CollectibleType.LOST_SOUL]: "Lost Soul",
  // There is no `CollectibleType` with a value of 613.
  [CollectibleType.BLOOD_BOMBS]: "Blood Bombs",
  [CollectibleType.LIL_DUMPY]: "Lil Dumpy",
  [CollectibleType.BIRDS_EYE]: "Bird's Eye",
  [CollectibleType.LODESTONE]: "Lodestone",
  [CollectibleType.ROTTEN_TOMATO]: "Rotten Tomato",
  [CollectibleType.BIRTHRIGHT]: "Birthright",
  // There is no `CollectibleType` with a value of 620.
  [CollectibleType.RED_STEW]: "Red Stew",
  [CollectibleType.GENESIS]: "Genesis",
  [CollectibleType.SHARP_KEY]: "Sharp Key",
  [CollectibleType.BOOSTER_PACK]: "Booster Pack",
  [CollectibleType.MEGA_MUSH]: "Mega Mush",
  [CollectibleType.KNIFE_PIECE_1]: "Knife Piece 1",
  [CollectibleType.KNIFE_PIECE_2]: "Knife Piece 2",
  [CollectibleType.DEATH_CERTIFICATE]: "Death Certificate",
  [CollectibleType.BOT_FLY]: "Bot Fly",
  // There is no `CollectibleType` with a value of 630.
  [CollectibleType.MEAT_CLEAVER]: "Meat Cleaver",
  [CollectibleType.EVIL_CHARM]: "Evil Charm",
  [CollectibleType.DOGMA]: "Dogma",
  [CollectibleType.PURGATORY]: "Purgatory",
  [CollectibleType.STITCHES]: "Stitches",
  [CollectibleType.R_KEY]: "R Key",
  [CollectibleType.KNOCKOUT_DROPS]: "Knockout Drops",
  [CollectibleType.ERASER]: "Eraser",
  [CollectibleType.YUCK_HEART]: "Yuck Heart",
  [CollectibleType.URN_OF_SOULS]: "Urn of Souls",
  [CollectibleType.AKELDAMA]: "Akeldama",
  [CollectibleType.MAGIC_SKIN]: "Magic Skin",
  [CollectibleType.REVELATION]: "Revelation",
  [CollectibleType.CONSOLATION_PRIZE]: "Consolation Prize",
  [CollectibleType.TINYTOMA]: "Tinytoma",
  [CollectibleType.BRIMSTONE_BOMBS]: "Brimstone Bombs",
  [CollectibleType.FOUR_FIVE_VOLT]: "4.5 Volt",
  // There is no `CollectibleType` with a value of 648.
  [CollectibleType.FRUITY_PLUM]: "Fruity Plum",
  [CollectibleType.PLUM_FLUTE]: "Plum Flute",
  [CollectibleType.STAR_OF_BETHLEHEM]: "Star of Bethlehem",
  [CollectibleType.CUBE_BABY]: "Cube Baby",
  [CollectibleType.VADE_RETRO]: "Vade Retro",
  [CollectibleType.FALSE_PHD]: "False PHD",
  [CollectibleType.SPIN_TO_WIN]: "Spin to Win",
  // There is no `CollectibleType` with a value of 656.
  [CollectibleType.DAMOCLES_PASSIVE]: "Damocles (Passive)",
  [CollectibleType.VASCULITIS]: "Vasculitis",
  [CollectibleType.GIANT_CELL]: "Giant Cell",
  [CollectibleType.TROPICAMIDE]: "Tropicamide",
  [CollectibleType.CARD_READING]: "Card Reading",
  [CollectibleType.QUINTS]: "Quints",
  // There is no `CollectibleType` with a value of 662.
  [CollectibleType.TOOTH_AND_NAIL]: "Tooth and Nail",
  [CollectibleType.BINGE_EATER]: "Binge Eater",
  [CollectibleType.GUPPYS_EYE]: "Guppy's Eye",
  // There is no `CollectibleType` with a value of 666.
  [CollectibleType.STRAWMAN]: "Strawman",
  [CollectibleType.DADS_NOTE]: "Dad's Note",
  [CollectibleType.SAUSAGE]: "Sausage",
  [CollectibleType.OPTIONS]: "Options?",
  [CollectibleType.CANDY_HEART]: "Candy Heart",
  [CollectibleType.POUND_OF_FLESH]: "A Pound of Flesh",
  [CollectibleType.REDEMPTION]: "Redemption",
  [CollectibleType.SPIRIT_SHACKLES]: "Spirit Shackles",
  [CollectibleType.CRACKED_ORB]: "Cracked Orb",
  [CollectibleType.EMPTY_HEART]: "Empty Heart",
  [CollectibleType.ASTRAL_PROJECTION]: "Astral Projection",
  [CollectibleType.C_SECTION]: "C Section",
  [CollectibleType.LIL_ABADDON]: "Lil Abaddon",
  [CollectibleType.MONTEZUMAS_REVENGE]: "Montezuma's Revenge",
  [CollectibleType.LIL_PORTAL]: "Lil Portal",
  [CollectibleType.WORM_FRIEND]: "Worm Friend",
  [CollectibleType.BONE_SPURS]: "Bone Spurs",
  [CollectibleType.HUNGRY_SOUL]: "Hungry Soul",
  [CollectibleType.JAR_OF_WISPS]: "Jar of Wisps",
  [CollectibleType.SOUL_LOCKET]: "Soul Locket",
  [CollectibleType.FRIEND_FINDER]: "Friend Finder",
  [CollectibleType.INNER_CHILD]: "Inner Child",
  [CollectibleType.GLITCHED_CROWN]: "Glitched Crown",
  [CollectibleType.JELLY_BELLY]: "Belly Jelly",
  [CollectibleType.SACRED_ORB]: "Sacred Orb",
  [CollectibleType.SANGUINE_BOND]: "Sanguine Bond",
  [CollectibleType.SWARM]: "The Swarm",
  [CollectibleType.HEARTBREAK]: "Heartbreak",
  [CollectibleType.BLOODY_GUST]: "Bloody Gust",
  [CollectibleType.SALVATION]: "Salvation",
  [CollectibleType.VANISHING_TWIN]: "Vanishing Twin",
  [CollectibleType.TWISTED_PAIR]: "Twisted Pair",
  [CollectibleType.AZAZELS_RAGE]: "Azazel's Rage",
  [CollectibleType.ECHO_CHAMBER]: "Echo Chamber",
  [CollectibleType.ISAACS_TOMB]: "Isaac's Tomb",
  [CollectibleType.VENGEFUL_SPIRIT]: "Vengeful Spirit",
  [CollectibleType.ESAU_JR]: "Esau Jr.",
  [CollectibleType.BERSERK]: "Berserk!",
  [CollectibleType.DARK_ARTS]: "Dark Arts",
  [CollectibleType.ABYSS]: "Abyss",
  [CollectibleType.SUPPER]: "Supper",
  [CollectibleType.STAPLER]: "Stapler",
  [CollectibleType.SUPLEX]: "Suplex!",
  [CollectibleType.BAG_OF_CRAFTING]: "Bag of Crafting",
  [CollectibleType.FLIP]: "Flip",
  [CollectibleType.LEMEGETON]: "Lemegeton",
  [CollectibleType.SUMPTORIUM]: "Sumptorium",
  [CollectibleType.RECALL]: "Recall",
  [CollectibleType.HOLD]: "Hold",
  [CollectibleType.KEEPERS_SACK]: "Keeper's Sack",
  [CollectibleType.KEEPERS_KIN]: "Keeper's Kin",
  // There is no `CollectibleType` with a value of 718.
  [CollectibleType.KEEPERS_BOX]: "Keeper's Box",
  [CollectibleType.EVERYTHING_JAR]: "Everything Jar",
  [CollectibleType.TMTRAINER]: "TMTRAINER",
  [CollectibleType.ANIMA_SOLA]: "Anima Sola",
  [CollectibleType.SPINDOWN_DICE]: "Spindown Dice",
  [CollectibleType.HYPERCOAGULATION]: "Hypercoagulation",
  [CollectibleType.IBS]: "IBS",
  [CollectibleType.HEMOPTYSIS]: "Hemoptysis",
  [CollectibleType.GHOST_BOMBS]: "Ghost Bombs",
  [CollectibleType.GELLO]: "Gello",
  [CollectibleType.DECAP_ATTACK]: "Decap Attack",
  [CollectibleType.GLASS_EYE]: "Glass Eye",
  [CollectibleType.STYE]: "Stye",
  [CollectibleType.MOMS_RING]: "Mom's Ring",
} as const satisfies Record<CollectibleType, string>;
