/* cspell:disable */

import { CollectibleType } from "isaac-typescript-definitions";

export const DEFAULT_COLLECTIBLE_DESCRIPTION = "Unknown";

/** Maps collectible types to the real English descriptions from the "stringtable.sta" file. */
export const COLLECTIBLE_DESCRIPTIONS = {
  [CollectibleType.NULL]: DEFAULT_COLLECTIBLE_DESCRIPTION,
  [CollectibleType.SAD_ONION]: "Tears up",
  [CollectibleType.INNER_EYE]: "Triple shot",
  [CollectibleType.SPOON_BENDER]: "Homing shots",
  [CollectibleType.CRICKETS_HEAD]: "DMG up",
  [CollectibleType.MY_REFLECTION]: "Boomerang tears",
  [CollectibleType.NUMBER_ONE]: "Tears up + range down",
  [CollectibleType.BLOOD_OF_THE_MARTYR]: "DMG up",
  [CollectibleType.BROTHER_BOBBY]: "Friends 'till the end",
  [CollectibleType.SKATOLE]: "Fly love",
  [CollectibleType.HALO_OF_FLIES]: "Projectile protection",
  [CollectibleType.ONE_UP]: "Extra life",
  [CollectibleType.MAGIC_MUSHROOM]: "All stats up!",
  [CollectibleType.VIRUS]: "Poison touch + speed up",
  [CollectibleType.ROID_RAGE]: "Speed and range up",
  [CollectibleType.HEART]: "HP up",
  [CollectibleType.RAW_LIVER]: "HP up",
  [CollectibleType.SKELETON_KEY]: "99 keys",
  [CollectibleType.DOLLAR]: "$$$",
  [CollectibleType.BOOM]: "10 bombs",
  [CollectibleType.TRANSCENDENCE]: "We all float down here...",
  [CollectibleType.COMPASS]: "The end is near",
  [CollectibleType.LUNCH]: "HP up",
  [CollectibleType.DINNER]: "HP up",
  [CollectibleType.DESSERT]: "HP up",
  [CollectibleType.BREAKFAST]: "HP up",
  [CollectibleType.ROTTEN_MEAT]: "HP up",
  [CollectibleType.WOODEN_SPOON]: "Speed up",
  [CollectibleType.BELT]: "Speed up",
  [CollectibleType.MOMS_UNDERWEAR]: "Range up",
  [CollectibleType.MOMS_HEELS]: "Range up",
  [CollectibleType.MOMS_LIPSTICK]: "Range up",
  [CollectibleType.WIRE_COAT_HANGER]: "Tears up",
  [CollectibleType.BIBLE]: "Temporary flight",
  [CollectibleType.BOOK_OF_BELIAL]: "Temporary DMG up",
  [CollectibleType.NECRONOMICON]: "Mass room damage",
  [CollectibleType.POOP]: "Plop!",
  [CollectibleType.MR_BOOM]: "Reusable bomb buddy",
  [CollectibleType.TAMMYS_HEAD]: "Reusable tear burst",
  [CollectibleType.MOMS_BRA]: "Mass paralysis",
  [CollectibleType.KAMIKAZE]: "Become the bomb!",
  [CollectibleType.MOMS_PAD]: "Mass fear",
  [CollectibleType.BOBS_ROTTEN_HEAD]: "Reusable ranged bomb",
  // There is no `CollectibleType` with a value of 43.
  [CollectibleType.TELEPORT]: "Teleport!",
  [CollectibleType.YUM_HEART]: "Reusable regeneration",
  [CollectibleType.LUCKY_FOOT]: "Luck up",
  [CollectibleType.DOCTORS_REMOTE]: "Reusable air strike",
  [CollectibleType.CUPIDS_ARROW]: "Piercing shots",
  [CollectibleType.SHOOP_DA_WHOOP]: "BLLLARRRRGGG!",
  [CollectibleType.STEVEN]: "DMG up",
  [CollectibleType.PENTAGRAM]: "DMG up",
  [CollectibleType.DR_FETUS]: "???",
  [CollectibleType.MAGNETO]: "Item snatcher",
  [CollectibleType.TREASURE_MAP]: "Full visible map",
  [CollectibleType.MOMS_EYE]: "Eye in the back of your head",
  [CollectibleType.LEMON_MISHAP]: "Oops...",
  [CollectibleType.DISTANT_ADMIRATION]: "Attack fly",
  [CollectibleType.BOOK_OF_SHADOWS]: "Temporary invincibility",
  [CollectibleType.BOOK_OF_BELIAL_BIRTHRIGHT]: "Temporary DMG up",
  [CollectibleType.LADDER]: "Building bridges",
  // There is no `CollectibleType` with a value of 61.
  [CollectibleType.CHARM_OF_THE_VAMPIRE]: "Kills heal",
  [CollectibleType.BATTERY]: "Stores energy",
  [CollectibleType.STEAM_SALE]: "50% off",
  [CollectibleType.ANARCHIST_COOKBOOK]: "Summon bombs",
  [CollectibleType.HOURGLASS]: "Temporary enemy slowdown",
  [CollectibleType.SISTER_MAGGY]: "Friends 'till the end",
  [CollectibleType.TECHNOLOGY]: "Laser tears",
  [CollectibleType.CHOCOLATE_MILK]: "Charge shots",
  [CollectibleType.GROWTH_HORMONES]: "Speed + DMG up",
  [CollectibleType.MINI_MUSH]: "Speed + range up",
  [CollectibleType.ROSARY]: "Tears + faith up",
  [CollectibleType.CUBE_OF_MEAT]: "Gotta meat 'em all",
  [CollectibleType.QUARTER]: "+25 coins",
  [CollectibleType.PHD]: "Better pills",
  [CollectibleType.XRAY_VISION]: "I've seen everything",
  [CollectibleType.MY_LITTLE_UNICORN]: "Temporary badass",
  [CollectibleType.BOOK_OF_REVELATIONS]: "Reusable soul protection",
  [CollectibleType.MARK]: "DMG + speed up",
  [CollectibleType.PACT]: "DMG + tears up",
  [CollectibleType.DEAD_CAT]: "9 lives",
  [CollectibleType.LORD_OF_THE_PIT]: "Demon wings",
  [CollectibleType.NAIL]: "Temporary demon form",
  [CollectibleType.WE_NEED_TO_GO_DEEPER]: "Reusable level skip",
  [CollectibleType.DECK_OF_CARDS]: "Reusable card generator ",
  [CollectibleType.MONSTROS_TOOTH]: "Summon Monstro",
  [CollectibleType.LOKIS_HORNS]: "Cross tears",
  [CollectibleType.LITTLE_CHUBBY]: "Attack buddy",
  [CollectibleType.SPIDER_BITE]: "Slow effect",
  [CollectibleType.SMALL_ROCK]: "DMG up",
  [CollectibleType.SPELUNKER_HAT]: "See-through doors",
  [CollectibleType.SUPER_BANDAGE]: "+2 hearts",
  [CollectibleType.GAMEKID]: "Temporary Man-Pac",
  [CollectibleType.SACK_OF_PENNIES]: "Gives money",
  [CollectibleType.ROBO_BABY]: "Friends 'till the bbbbzzzt",
  [CollectibleType.LITTLE_CHAD]: "Gives kisses",
  [CollectibleType.BOOK_OF_SIN]: "Reusable item generator",
  [CollectibleType.RELIC]: "Soul generator",
  [CollectibleType.LITTLE_GISH]: "Sticky friend",
  [CollectibleType.LITTLE_STEVEN]: "Psychic friend",
  [CollectibleType.HALO]: "All stats up",
  [CollectibleType.MOMS_BOTTLE_OF_PILLS]: "Reusable pill generator",
  [CollectibleType.COMMON_COLD]: "Poison damage",
  [CollectibleType.PARASITE]: "Split shot",
  [CollectibleType.D6]: "Reroll your destiny",
  [CollectibleType.MR_MEGA]: "Bigger boom",
  [CollectibleType.PINKING_SHEARS]: "Cut and run",
  [CollectibleType.WAFER]: "Damage resistance",
  [CollectibleType.MONEY_EQUALS_POWER]: "$$$ = DMG",
  [CollectibleType.MOMS_CONTACTS]: "Freeze effect",
  [CollectibleType.BEAN]: "Toot on command",
  [CollectibleType.GUARDIAN_ANGEL]: "Extra protection",
  [CollectibleType.DEMON_BABY]: "Auto-turret friend",
  [CollectibleType.MOMS_KNIFE]: "Stab stab stab",
  [CollectibleType.OUIJA_BOARD]: "Spectral tears",
  [CollectibleType.NINE_VOLT]: "Quicker charge",
  [CollectibleType.DEAD_BIRD]: "Protective buddy",
  [CollectibleType.BRIMSTONE]: "Blood laser barrage",
  [CollectibleType.BLOOD_BAG]: "HP up",
  [CollectibleType.ODD_MUSHROOM_THIN]: "Tears + speed up, DMG down",
  [CollectibleType.ODD_MUSHROOM_LARGE]: "HP + DMG up, speed down",
  [CollectibleType.WHORE_OF_BABYLON]: "Curse up",
  [CollectibleType.MONSTER_MANUAL]: "Temporary buddy generator",
  [CollectibleType.DEAD_SEA_SCROLLS]: "It's a mystery",
  [CollectibleType.BOBBY_BOMB]: "Homing bombs",
  [CollectibleType.RAZOR_BLADE]: "Feel my pain",
  [CollectibleType.FORGET_ME_NOW]: "I don't remember...",
  [CollectibleType.FOREVER_ALONE]: "Attack fly",
  [CollectibleType.BUCKET_OF_LARD]: "HP up",
  [CollectibleType.PONY]: "Flight + dash attack",
  [CollectibleType.BOMB_BAG]: "Gives bombs",
  [CollectibleType.LUMP_OF_COAL]: "My Xmas present",
  [CollectibleType.GUPPYS_PAW]: "Soul converter",
  [CollectibleType.GUPPYS_TAIL]: "Cursed?",
  [CollectibleType.IV_BAG]: "Portable blood bank",
  [CollectibleType.BEST_FRIEND]: "Friends 'till the end",
  [CollectibleType.REMOTE_DETONATOR]: "Remote bomb detonation",
  [CollectibleType.STIGMATA]: "DMG + HP up",
  [CollectibleType.MOMS_PURSE]: "More trinket room",
  [CollectibleType.BOBS_CURSE]: "+5 poison bombs",
  [CollectibleType.PAGEANT_BOY]: "Ultimate grand supreme",
  [CollectibleType.SCAPULAR]: "Pray for a miracle",
  [CollectibleType.SPEED_BALL]: "Speed + shot speed up",
  [CollectibleType.BUM_FRIEND]: "He's greedy",
  [CollectibleType.GUPPYS_HEAD]: "Reusable fly hive",
  [CollectibleType.PRAYER_CARD]: "Reusable eternity ",
  [CollectibleType.NOTCHED_AXE]: "Rocks don't stand a chance",
  [CollectibleType.INFESTATION]: "Fly revenge",
  [CollectibleType.IPECAC]: "Explosive shots",
  [CollectibleType.TOUGH_LOVE]: "Tooth shot",
  [CollectibleType.MULLIGAN]: "They grow inside",
  [CollectibleType.TECHNOLOGY_2]: "Extra laser",
  [CollectibleType.MUTANT_SPIDER]: "Quad shot",
  [CollectibleType.CHEMICAL_PEEL]: "DMG up",
  [CollectibleType.PEEPER]: "Plop!",
  [CollectibleType.HABIT]: "Item martyr",
  [CollectibleType.BLOODY_LUST]: "RAGE!",
  [CollectibleType.CRYSTAL_BALL]: "I see my future",
  [CollectibleType.SPIRIT_OF_THE_NIGHT]: "Scary",
  [CollectibleType.CRACK_THE_SKY]: "Holy white death",
  [CollectibleType.ANKH]: "Eternal life?",
  [CollectibleType.CELTIC_CROSS]: "Blessing of protection",
  [CollectibleType.GHOST_BABY]: "Spectral buddy",
  [CollectibleType.CANDLE]: "Reusable flames",
  [CollectibleType.CAT_O_NINE_TAILS]: "Shot speed + damage up",
  [CollectibleType.D20]: "Reroll the basics",
  [CollectibleType.HARLEQUIN_BABY]: "Double shot buddy",
  [CollectibleType.EPIC_FETUS]: "On-demand air strike",
  [CollectibleType.POLYPHEMUS]: "Mega tears",
  [CollectibleType.DADDY_LONGLEGS]: "Daddy's love",
  [CollectibleType.SPIDER_BUTT]: "Mass enemy slowdown + damage",
  [CollectibleType.SACRIFICIAL_DAGGER]: "My fate protects me",
  [CollectibleType.MITRE]: "Blessing of purity",
  [CollectibleType.RAINBOW_BABY]: "Random buddy",
  [CollectibleType.DADS_KEY]: "Opens all doors...",
  [CollectibleType.STEM_CELLS]: "HP + shot speed up",
  [CollectibleType.PORTABLE_SLOT]: "Gamble 24/7",
  [CollectibleType.HOLY_WATER]: "Splash!",
  [CollectibleType.FATE]: "Flight eternal",
  [CollectibleType.BLACK_BEAN]: "Toot on touch",
  [CollectibleType.WHITE_PONY]: "Flight + holy death",
  [CollectibleType.SACRED_HEART]: "Homing shots + DMG up",
  [CollectibleType.TOOTH_PICKS]: "Tears + shot speed up",
  [CollectibleType.HOLY_GRAIL]: "Flight + HP up",
  [CollectibleType.DEAD_DOVE]: "Flight + spectral tears",
  [CollectibleType.BLOOD_RIGHTS]: "Mass enemy damage at a cost",
  [CollectibleType.GUPPYS_HAIRBALL]: "Swing it",
  [CollectibleType.ABEL]: "Mirrored buddy",
  [CollectibleType.SMB_SUPER_FAN]: "All stats up",
  [CollectibleType.PYRO]: "99 bombs",
  [CollectibleType.THREE_DOLLAR_BILL]: "Rainbow tears",
  [CollectibleType.TELEPATHY_BOOK]: "Temporary psychic shot",
  [CollectibleType.MEAT]: "DMG + HP up",
  [CollectibleType.MAGIC_8_BALL]: "Shot speed up",
  [CollectibleType.MOMS_COIN_PURSE]: "What's all this...?",
  [CollectibleType.SQUEEZY]: "Tears up",
  [CollectibleType.JESUS_JUICE]: "Damage + range up",
  [CollectibleType.BOX]: "Stuff",
  [CollectibleType.MOMS_KEY]: "Better chest loot +2 keys",
  [CollectibleType.MOMS_EYESHADOW]: "Charm tears",
  [CollectibleType.IRON_BAR]: "DMG up + concussive tears",
  [CollectibleType.MIDAS_TOUCH]: "Golden touch",
  [CollectibleType.HUMBLING_BUNDLE]: "1+1 free 4Evar",
  [CollectibleType.FANNY_PACK]: "Filled with goodies",
  [CollectibleType.SHARP_PLUG]: "Infinite charge... at a cost",
  [CollectibleType.GUILLOTINE]: "DMG + tears up. An out-of-body experience!",
  [CollectibleType.BALL_OF_BANDAGES]: "Gotta lick 'em all!",
  [CollectibleType.CHAMPION_BELT]: "DMG + challenge up",
  [CollectibleType.BUTT_BOMBS]: "Toxic blast +5 bombs",
  [CollectibleType.GNAWED_LEAF]: "Unbreakable",
  [CollectibleType.SPIDERBABY]: "Spider revenge",
  [CollectibleType.GUPPYS_COLLAR]: "Eternal life?",
  [CollectibleType.LOST_CONTACT]: "Shielded tears",
  [CollectibleType.ANEMIC]: "Toxic blood",
  [CollectibleType.GOAT_HEAD]: "He accepts your offering",
  [CollectibleType.CEREMONIAL_ROBES]: "DMG + evil up",
  [CollectibleType.MOMS_WIG]: "You feel itchy...",
  [CollectibleType.PLACENTA]: "Regeneration + HP up",
  [CollectibleType.OLD_BANDAGE]: "HP up",
  [CollectibleType.SAD_BOMBS]: "Tear blasts +5 bombs",
  [CollectibleType.RUBBER_CEMENT]: "Bouncing tears",
  [CollectibleType.ANTI_GRAVITY]: "Anti-gravity tears + tears up",
  [CollectibleType.PYROMANIAC]: "It hurts so good +5 bombs",
  [CollectibleType.CRICKETS_BODY]: "Bursting shots + tears up",
  [CollectibleType.GIMPY]: "Sweet suffering",
  [CollectibleType.BLACK_LOTUS]: "HP up x3",
  [CollectibleType.PIGGY_BANK]: "My life savings",
  [CollectibleType.MOMS_PERFUME]: "Fear shot + tears up",
  [CollectibleType.MONSTROS_LUNG]: "Charged burst attack",
  [CollectibleType.ABADDON]: "Evil + DMG up + fear shot",
  [CollectibleType.BALL_OF_TAR]: "Sticky feet...",
  [CollectibleType.STOP_WATCH]: "Let's slow this down a bit...",
  [CollectibleType.TINY_PLANET]: "Orbiting tears + range up",
  [CollectibleType.INFESTATION_2]: "Infestation shot",
  // There is no `CollectibleType` with a value of 235.
  [CollectibleType.E_COLI]: "Turdy touch",
  [CollectibleType.DEATHS_TOUCH]: "Piercing shots + DMG up",
  [CollectibleType.KEY_PIECE_1]: "???",
  [CollectibleType.KEY_PIECE_2]: "???",
  [CollectibleType.EXPERIMENTAL_TREATMENT]: "Some stats up, some stats down",
  [CollectibleType.CONTRACT_FROM_BELOW]: "Wealth... but at what cost?",
  [CollectibleType.INFAMY]: "Blocks damage... sometimes",
  [CollectibleType.TRINITY_SHIELD]: "You feel guarded",
  [CollectibleType.TECH_5]: "It's still being tested...",
  [CollectibleType.TWENTY_TWENTY]: "Double shot",
  [CollectibleType.BLUE_MAP]: "Secrets",
  [CollectibleType.BFFS]: "Your friends rule",
  [CollectibleType.HIVE_MIND]: "Giant spiders and flies",
  [CollectibleType.THERES_OPTIONS]: "More options",
  [CollectibleType.BOGO_BOMBS]: "1+1 BOOM!",
  [CollectibleType.STARTER_DECK]: "Extra card room",
  [CollectibleType.LITTLE_BAGGY]: "Extra pill room",
  [CollectibleType.MAGIC_SCAB]: "HP + luck up",
  [CollectibleType.BLOOD_CLOT]: "DMG + range up",
  [CollectibleType.SCREW]: "Tears + shot speed up",
  [CollectibleType.HOT_BOMBS]: "Burning blast +5 bombs",
  [CollectibleType.FIRE_MIND]: "Flaming tears",
  [CollectibleType.MISSING_NO]: "Syntax error",
  [CollectibleType.DARK_MATTER]: "DMG up + fear shot",
  [CollectibleType.BLACK_CANDLE]: "Curse immunity + evil up",
  [CollectibleType.PROPTOSIS]: "Short range mega tears",
  [CollectibleType.MISSING_PAGE_2]: "Evil up. Your enemies will pay!",
  [CollectibleType.CLEAR_RUNE]: "Rune mimic",
  [CollectibleType.SMART_FLY]: "Revenge fly",
  [CollectibleType.DRY_BABY]: "Immortal friend",
  [CollectibleType.JUICY_SACK]: "Sticky babies",
  [CollectibleType.ROBO_BABY_2]: "We worked out all the kinks",
  [CollectibleType.ROTTEN_BABY]: "Infested friend",
  [CollectibleType.HEADLESS_BABY]: "Bloody friend",
  [CollectibleType.LEECH]: "Blood sucker",
  [CollectibleType.MYSTERY_SACK]: "?",
  [CollectibleType.BBF]: "Big Beautiful Fly",
  [CollectibleType.BOBS_BRAIN]: "Explosive thoughts",
  [CollectibleType.BEST_BUD]: "Sworn protector",
  [CollectibleType.LIL_BRIMSTONE]: "Evil friend",
  [CollectibleType.ISAACS_HEART]: "Protect it",
  [CollectibleType.LIL_HAUNT]: "Fear him",
  [CollectibleType.DARK_BUM]: "He wants to take your life",
  [CollectibleType.BIG_FAN]: "Fat protector",
  [CollectibleType.SISSY_LONGLEGS]: "She loves you",
  [CollectibleType.PUNCHING_BAG]: "Scape goat",
  [CollectibleType.HOW_TO_JUMP]: "It's time you learned how",
  [CollectibleType.D100]: "REEROLLLLL!",
  [CollectibleType.D4]: "Reroll into something else",
  [CollectibleType.D10]: "Reroll enemies",
  [CollectibleType.BLANK_CARD]: "Card mimic",
  [CollectibleType.BOOK_OF_SECRETS]: "Tome of knowledge",
  [CollectibleType.BOX_OF_SPIDERS]: "It's a box of spiders",
  [CollectibleType.RED_CANDLE]: "Flame on",
  [CollectibleType.JAR]: "Save your life",
  [CollectibleType.FLUSH]: "...",
  [CollectibleType.SATANIC_BIBLE]: "Reusable evil... but at what cost?",
  [CollectibleType.HEAD_OF_KRAMPUS]: "Krampus rage",
  [CollectibleType.BUTTER_BEAN]: "Reusable knock-back",
  [CollectibleType.MAGIC_FINGERS]: "Pay to win",
  [CollectibleType.CONVERTER]: "Convert your soul",
  [CollectibleType.BLUE_BOX]: "? ?",
  [CollectibleType.UNICORN_STUMP]: "You feel stumped",
  [CollectibleType.TAURUS]: "Speed down + rage is building",
  [CollectibleType.ARIES]: "Ramming speed",
  [CollectibleType.CANCER]: "HP up + you feel protected",
  [CollectibleType.LEO]: "Stompy",
  [CollectibleType.VIRGO]: "You feel refreshed and protected",
  [CollectibleType.LIBRA]: "You feel balanced",
  [CollectibleType.SCORPIO]: "Poison tears",
  [CollectibleType.SAGITTARIUS]: "Piercing shots + speed up",
  [CollectibleType.CAPRICORN]: "All stats up",
  [CollectibleType.AQUARIUS]: "Trail of tears",
  [CollectibleType.PISCES]: "Tears up + knock-back shot",
  [CollectibleType.EVES_MASCARA]: "DMG up, tears + shot speed down",
  [CollectibleType.JUDAS_SHADOW]: "Sweet revenge",
  [CollectibleType.MAGGYS_BOW]: "HP up + you feel healthy",
  [CollectibleType.HOLY_MANTLE]: "Holy shield",
  [CollectibleType.THUNDER_THIGHS]: "HP up + speed down + you feel stompy",
  [CollectibleType.STRANGE_ATTRACTOR]: "Magnetic tears",
  [CollectibleType.CURSED_EYE]: "Cursed charge shot",
  [CollectibleType.MYSTERIOUS_LIQUID]: "Toxic splash damage",
  [CollectibleType.GEMINI]: "Conjoined friend",
  [CollectibleType.CAINS_OTHER_EYE]: "Near-sighted friend",
  [CollectibleType.BLUE_BABYS_ONLY_FRIEND]: "Controlled friend",
  [CollectibleType.SAMSONS_CHAINS]: "The ol' ball and chain",
  [CollectibleType.MONGO_BABY]: "Mongo friend",
  [CollectibleType.ISAACS_TEARS]: "Collected tears",
  [CollectibleType.UNDEFINED]: "Undefined",
  [CollectibleType.SCISSORS]: "Lose your head",
  [CollectibleType.BREATH_OF_LIFE]: "Invincibility at a cost",
  [CollectibleType.POLAROID]: "Fate chosen",
  [CollectibleType.NEGATIVE]: "Fate chosen",
  [CollectibleType.LUDOVICO_TECHNIQUE]: "Controlled tears",
  [CollectibleType.SOY_MILK]: "DMG down + tears way up",
  [CollectibleType.GODHEAD]: "God tears",
  [CollectibleType.LAZARUS_RAGS]: "Eternal life?",
  [CollectibleType.MIND]: "I know all",
  [CollectibleType.BODY]: "I feel all",
  [CollectibleType.SOUL]: "I am all",
  [CollectibleType.DEAD_ONION]: "Toxic aura tears",
  [CollectibleType.BROKEN_WATCH]: "I think it's broken",
  [CollectibleType.BOOMERANG]: "It will never leave you",
  [CollectibleType.SAFETY_PIN]: "Evil + range + shot speed up",
  [CollectibleType.CAFFEINE_PILL]: "Speed up + size down",
  [CollectibleType.TORN_PHOTO]: "Tears + shot speed up",
  [CollectibleType.BLUE_CAP]: "HP + tears up + shot speed down",
  [CollectibleType.LATCH_KEY]: "Luck up",
  [CollectibleType.MATCH_BOOK]: "Evil up",
  [CollectibleType.SYNTHOIL]: "DMG + range up",
  [CollectibleType.SNACK]: "HP up",
  [CollectibleType.DIPLOPIA]: "Double item vision",
  [CollectibleType.PLACEBO]: "Pill mimic",
  [CollectibleType.WOODEN_NICKEL]: "Flip a coin",
  [CollectibleType.TOXIC_SHOCK]: "Mass poison",
  [CollectibleType.MEGA_BEAN]: "Giga fart!",
  [CollectibleType.GLASS_CANNON]: "Be gentle...",
  [CollectibleType.BOMBER_BOY]: "Cross blast + 5 bombs",
  [CollectibleType.CRACK_JACKS]: "HP up. Don't swallow the prize!",
  [CollectibleType.MOMS_PEARLS]: "Range + luck up",
  [CollectibleType.CAR_BATTERY]: "Active power up",
  [CollectibleType.BOX_OF_FRIENDS]: "Double your friends",
  [CollectibleType.WIZ]: "Double wiz shot!",
  [CollectibleType.EIGHT_INCH_NAILS]: "Stick it to 'em!",
  [CollectibleType.INCUBUS]: "Dark friend",
  [CollectibleType.FATES_REWARD]: "Your fate beside you",
  [CollectibleType.LIL_CHEST]: "What's in the box?",
  [CollectibleType.SWORN_PROTECTOR]: "Protective friend",
  [CollectibleType.FRIEND_ZONE]: "Friendly fly",
  [CollectibleType.LOST_FLY]: "Lost protector",
  [CollectibleType.SCATTER_BOMBS]: "We put bombs in your bombs!",
  [CollectibleType.STICKY_BOMBS]: "Egg sack bombs!",
  [CollectibleType.EPIPHORA]: "Intensifying tears",
  [CollectibleType.CONTINUUM]: "Transcendent tears",
  [CollectibleType.MR_DOLLY]: "Range + tears up",
  [CollectibleType.CURSE_OF_THE_TOWER]: "Embrace chaos",
  [CollectibleType.CHARGED_BABY]: "Bbbzzzzzt! ",
  [CollectibleType.DEAD_EYE]: "Accuracy brings power",
  [CollectibleType.HOLY_LIGHT]: "Holy death shot",
  [CollectibleType.HOST_HAT]: "Blast resistance",
  [CollectibleType.RESTOCK]: "Never ending stores!",
  [CollectibleType.BURSTING_SACK]: "Spider love",
  [CollectibleType.NUMBER_TWO]: "Uh oh...",
  [CollectibleType.PUPULA_DUPLEX]: "Wide shot",
  [CollectibleType.PAY_TO_PLAY]: "Money talks",
  [CollectibleType.EDENS_BLESSING]: "Tears up + your future shines brighter",
  [CollectibleType.FRIEND_BALL]: "Gotta fetch 'em all!",
  [CollectibleType.TEAR_DETONATOR]: "Remote tear detonation",
  [CollectibleType.LIL_GURDY]: "A gurd of your own!",
  [CollectibleType.BUMBO]: "Bumbo want coin!",
  [CollectibleType.D12]: "Rerolls rocks",
  [CollectibleType.CENSER]: "Peace be with you",
  [CollectibleType.KEY_BUM]: "He wants your keys!",
  [CollectibleType.RUNE_BAG]: "Rune generator",
  [CollectibleType.SERAPHIM]: "Sworn friend",
  [CollectibleType.BETRAYAL]: "Turn your enemy",
  [CollectibleType.ZODIAC]: "The heavens will change you",
  [CollectibleType.SERPENTS_KISS]: "The kiss of death",
  [CollectibleType.MARKED]: "Directed tears",
  [CollectibleType.TECH_X]: "Laser ring tears",
  [CollectibleType.VENTRICLE_RAZOR]: "Short cutter",
  [CollectibleType.TRACTOR_BEAM]: "Controlled tears",
  [CollectibleType.GODS_FLESH]: "Shrink shot!",
  [CollectibleType.MAW_OF_THE_VOID]: "Consume thy enemy!",
  [CollectibleType.SPEAR_OF_DESTINY]: "Your destiny",
  [CollectibleType.EXPLOSIVO]: "Sticky bomb shot",
  [CollectibleType.CHAOS]: "!!!",
  [CollectibleType.SPIDER_MOD]: "Mod buddy",
  [CollectibleType.FARTING_BABY]: "He farts",
  [CollectibleType.GB_BUG]: "Double tap glitch",
  [CollectibleType.D8]: "Reroll stats",
  [CollectibleType.PURITY]: "Aura stat boost",
  [CollectibleType.ATHAME]: "Call to the void",
  [CollectibleType.EMPTY_VESSEL]: "I reward an empty vessel",
  [CollectibleType.EVIL_EYE]: "Eye shot",
  [CollectibleType.LUSTY_BLOOD]: "Their blood brings rage!",
  [CollectibleType.CAMBION_CONCEPTION]: "Feed them hate",
  [CollectibleType.IMMACULATE_CONCEPTION]: "Feed them love",
  [CollectibleType.MORE_OPTIONS]: "There's options",
  [CollectibleType.CROWN_OF_LIGHT]: "The untainted gain power",
  [CollectibleType.DEEP_POCKETS]: "More money!",
  [CollectibleType.SUCCUBUS]: "Damage booster",
  [CollectibleType.FRUIT_CAKE]: "Rainbow effects!",
  [CollectibleType.TELEPORT_2]: "I-Teleport!",
  [CollectibleType.BLACK_POWDER]: "Spin the black circle!",
  [CollectibleType.KIDNEY_BEAN]: "Love toots",
  [CollectibleType.GLOWING_HOUR_GLASS]: "Turn back time",
  [CollectibleType.CIRCLE_OF_PROTECTION]: "Protect me from myself",
  [CollectibleType.SACK_HEAD]: "More sacks!",
  [CollectibleType.NIGHT_LIGHT]: "Scared of the dark?",
  [CollectibleType.OBSESSED_FAN]: "Follows my every move...",
  [CollectibleType.MINE_CRAFTER]: "Booom!",
  [CollectibleType.PJS]: "You feel cozy",
  [CollectibleType.HEAD_OF_THE_KEEPER]: "Penny tears",
  [CollectibleType.PAPA_FLY]: "Turret follower",
  [CollectibleType.MULTIDIMENSIONAL_BABY]: "ydduB Buddy",
  [CollectibleType.GLITTER_BOMBS]: "Prize bombs",
  [CollectibleType.MY_SHADOW]: "Me! And my shaaaadow!",
  [CollectibleType.JAR_OF_FLIES]: "Bug catcher",
  [CollectibleType.LIL_LOKI]: "4-way buddy!",
  [CollectibleType.MILK]: "Don't cry over it...",
  [CollectibleType.D7]: "Roll again",
  [CollectibleType.BINKY]: "Tears up",
  [CollectibleType.MOMS_BOX]: "What's inside?",
  [CollectibleType.KIDNEY_STONE]: "Matt's kidney stone",
  [CollectibleType.MEGA_BLAST]: "Laser breath",
  [CollectibleType.DARK_PRINCES_CROWN]: "Loss is power",
  [CollectibleType.APPLE]: "Trick or treat?",
  [CollectibleType.LEAD_PENCIL]: "He's a bleeder!",
  [CollectibleType.DOG_TOOTH]: "Bark at the moon!",
  [CollectibleType.DEAD_TOOTH]: "Toxic breath",
  [CollectibleType.LINGER_BEAN]: "Crying makes me toot",
  [CollectibleType.SHARD_OF_GLASS]: "Blood and guts!",
  [CollectibleType.METAL_PLATE]: "It itches...",
  [CollectibleType.EYE_OF_GREED]: "Gold tears!",
  [CollectibleType.TAROT_CLOTH]: "I see the future",
  [CollectibleType.VARICOSE_VEINS]: "I'm leaking...",
  [CollectibleType.COMPOUND_FRACTURE]: "Bone tears!",
  [CollectibleType.POLYDACTYLY]: "Hold me!",
  [CollectibleType.DADS_LOST_COIN]: "I remember this...",
  [CollectibleType.MIDNIGHT_SNACK]: "HP up",
  [CollectibleType.CONE_HEAD]: "Hard headed!",
  [CollectibleType.BELLY_BUTTON]: "What's in there?",
  [CollectibleType.SINUS_INFECTION]: "Booger tears!",
  [CollectibleType.GLAUCOMA]: "Blind tears!",
  [CollectibleType.PARASITOID]: "Egg tears!",
  [CollectibleType.EYE_OF_BELIAL]: "Possessed tears!",
  [CollectibleType.SULFURIC_ACID]: "Acid tears!",
  [CollectibleType.GLYPH_OF_BALANCE]: "A gift from above",
  [CollectibleType.ANALOG_STICK]: "360 tears!",
  [CollectibleType.CONTAGION]: "Outbreak!",
  [CollectibleType.FINGER]: "Watch where you point that!",
  [CollectibleType.SHADE]: "It follows",
  [CollectibleType.DEPRESSION]: ":(",
  [CollectibleType.HUSHY]: "Lil hush!",
  [CollectibleType.LIL_MONSTRO]: "Ain't he cute?",
  [CollectibleType.KING_BABY]: "Hail to the king baby",
  [CollectibleType.BIG_CHUBBY]: "Chub chub",
  [CollectibleType.BROKEN_GLASS_CANNON]: "You broke it!",
  [CollectibleType.PLAN_C]: "My last resort",
  [CollectibleType.D1]: "What will it be?",
  [CollectibleType.VOID]: "Consume",
  [CollectibleType.PAUSE]: "Stop!",
  [CollectibleType.SMELTER]: "Trinket melter!",
  [CollectibleType.COMPOST]: "Gain more friends!",
  [CollectibleType.DATAMINER]: "109",
  [CollectibleType.CLICKER]: "Change",
  [CollectibleType.MAMA_MEGA]: "BOOOOOOOOOM!",
  [CollectibleType.WAIT_WHAT]: "I can't believe it's not butter bean!",
  [CollectibleType.CROOKED_PENNY]: "50/50",
  [CollectibleType.DULL_RAZOR]: "I feel numb...",
  [CollectibleType.POTATO_PEELER]: "A pound of flesh...",
  [CollectibleType.METRONOME]: "Waggles a finger",
  [CollectibleType.D_INFINITY]: "Reroll forever",
  [CollectibleType.EDENS_SOUL]: "...",
  [CollectibleType.ACID_BABY]: "Pills pills pills!",
  [CollectibleType.YO_LISTEN]: "Yo listen!",
  [CollectibleType.ADRENALINE]: "Panic = power",
  [CollectibleType.JACOBS_LADDER]: "Electric tears",
  [CollectibleType.GHOST_PEPPER]: "Flame tears",
  [CollectibleType.EUTHANASIA]: "Needle shot",
  [CollectibleType.CAMO_UNDIES]: "Camo kid",
  [CollectibleType.DUALITY]: "You feel very balanced",
  [CollectibleType.EUCHARIST]: "Peace be with you",
  [CollectibleType.SACK_OF_SACKS]: "Gives sacks",
  [CollectibleType.GREEDS_GULLET]: "Money = health!",
  [CollectibleType.LARGE_ZIT]: "Creep shots",
  [CollectibleType.LITTLE_HORN]: "Big brother is watching",
  [CollectibleType.BROWN_NUGGET]: "Friendly fly",
  [CollectibleType.POKE_GO]: "Gotta catch em...",
  [CollectibleType.BACKSTABBER]: "Watch your back!",
  [CollectibleType.SHARP_STRAW]: "More blood!",
  [CollectibleType.MOMS_RAZOR]: "It's sharp!",
  [CollectibleType.BLOODSHOT_EYE]: "Bloody friend",
  [CollectibleType.DELIRIOUS]: "Unleash the power!",
  [CollectibleType.ANGRY_FLY]: "He's violent",
  [CollectibleType.BLACK_HOLE]: "Nothing can escape",
  [CollectibleType.BOZO]: "Party time!",
  [CollectibleType.BROKEN_MODEM]: "Lag!",
  [CollectibleType.MYSTERY_GIFT]: "Wrapped up nice for you!",
  [CollectibleType.SPRINKLER]: "Sprinkles.",
  [CollectibleType.FAST_BOMBS]: "Rapid bomb drops",
  [CollectibleType.BUDDY_IN_A_BOX]: "What could it be?!",
  [CollectibleType.LIL_DELIRIUM]: "Delirious friend",
  [CollectibleType.JUMPER_CABLES]: "Bloody recharge",
  [CollectibleType.COUPON]: "Allow 6 weeks for delivery",
  [CollectibleType.TELEKINESIS]: "Power of the mind",
  [CollectibleType.MOVING_BOX]: "Pack and unpack",
  [CollectibleType.TECHNOLOGY_ZERO]: "Static tears",
  [CollectibleType.LEPROSY]: "You're tearing me apart!",
  [CollectibleType.SEVEN_SEALS]: "Lil harbingers!",
  [CollectibleType.MR_ME]: "Caaan do!",
  [CollectibleType.ANGELIC_PRISM]: "Eclipsed by the moon",
  [CollectibleType.POP]: "Eyeball tears",
  [CollectibleType.DEATHS_LIST]: "Just hope you're not next...",
  [CollectibleType.HAEMOLACRIA]: "I'm seeing red...",
  [CollectibleType.LACHRYPHAGY]: "Feed them!",
  [CollectibleType.TRISAGION]: "Smite thy enemy",
  [CollectibleType.SCHOOLBAG]: "Extra active item room",
  [CollectibleType.BLANKET]: "You feel safe",
  [CollectibleType.SACRIFICIAL_ALTAR]: "He demands a sacrifice",
  [CollectibleType.LIL_SPEWER]: "Puking buddy",
  [CollectibleType.MARBLES]: "Choking hazard",
  [CollectibleType.MYSTERY_EGG]: "Sacrificial insemination",
  [CollectibleType.FLAT_STONE]: "Skipping tears",
  [CollectibleType.MARROW]: "HP up?",
  [CollectibleType.SLIPPED_RIB]: "Projectile shield",
  [CollectibleType.HALLOWED_GROUND]: "Portable sanctuary",
  [CollectibleType.POINTY_RIB]: "Stabbing time",
  [CollectibleType.BOOK_OF_THE_DEAD]: "Rise from the grave",
  [CollectibleType.DADS_RING]: "Father's blessing",
  [CollectibleType.DIVORCE_PAPERS]: "Tears up + you feel empty",
  [CollectibleType.JAW_BONE]: "Fetch!",
  [CollectibleType.BRITTLE_BONES]: "Everything hurts",
  [CollectibleType.BROKEN_SHOVEL_1]: "It feels cursed",
  [CollectibleType.BROKEN_SHOVEL_2]: "It feels cursed",
  [CollectibleType.MOMS_SHOVEL]: "Lost but not forgotten",
  [CollectibleType.MUCORMYCOSIS]: "Spore shot",
  [CollectibleType.TWO_SPOOKY]: "4me",
  [CollectibleType.GOLDEN_RAZOR]: "Pain from gain",
  [CollectibleType.SULFUR]: "Temporary demon form",
  [CollectibleType.FORTUNE_COOKIE]: "Reusable fortunes",
  [CollectibleType.EYE_SORE]: "More eyes",
  [CollectibleType.ONE_HUNDRED_TWENTY_VOLT]: "Zap!",
  [CollectibleType.IT_HURTS]: "No it doesn't...",
  [CollectibleType.ALMOND_MILK]: "DMG down + tears up + you feel nutty",
  [CollectibleType.ROCK_BOTTOM]: "It's only up from there",
  [CollectibleType.NANCY_BOMBS]: "Random blast +5 bombs",
  [CollectibleType.BAR_OF_SOAP]: "Tears + shot speed up",
  [CollectibleType.BLOOD_PUPPY]: "What a cute little thing!",
  [CollectibleType.DREAM_CATCHER]: "Sweet dreams",
  [CollectibleType.PASCHAL_CANDLE]: "Keep the flame burning",
  [CollectibleType.DIVINE_INTERVENTION]: "Double tap shield",
  [CollectibleType.BLOOD_OATH]: "Bleed me dry",
  [CollectibleType.PLAYDOUGH_COOKIE]: "Tasty rainbow",
  [CollectibleType.SOCKS]: "Speed up + your feet feel stronger",
  [CollectibleType.EYE_OF_THE_OCCULT]: "DMG up + range up + controlled tears",
  [CollectibleType.IMMACULATE_HEART]: "Halo of tears",
  [CollectibleType.MONSTRANCE]: "Purifying light",
  [CollectibleType.INTRUDER]: "Invasive friend",
  [CollectibleType.DIRTY_MIND]: "Filthy friends",
  [CollectibleType.DAMOCLES]: "A king's fortune... but at what cost?",
  [CollectibleType.FREE_LEMONADE]: "Party time!",
  [CollectibleType.SPIRIT_SWORD]: "Divine blade",
  [CollectibleType.RED_KEY]: "Explore the other side",
  [CollectibleType.PSY_FLY]: "Flamboyant protector",
  [CollectibleType.WAVY_CAP]: "Tears up. A mind changing experience!",
  [CollectibleType.ROCKET_IN_A_JAR]: "Rocket propulsion +5 bombs",
  [CollectibleType.BOOK_OF_VIRTUES]: "Spiritual companionship",
  [CollectibleType.ALABASTER_BOX]: "A sacred offering",
  [CollectibleType.STAIRWAY]: "May you get what you came for",
  // There is no `CollectibleType` with a value of 587.
  [CollectibleType.SOL]: "Radiant victory",
  [CollectibleType.LUNA]: "The moon's blessing shines upon you",
  [CollectibleType.MERCURIUS]: "Speed up + you feel elusive",
  [CollectibleType.VENUS]: "HP up + you feel pretty",
  [CollectibleType.TERRA]: "Born to rock",
  [CollectibleType.MARS]: "Double tap dash",
  [CollectibleType.JUPITER]: "You're a gas giant!",
  [CollectibleType.SATURNUS]: "Ring of tears",
  [CollectibleType.URANUS]: "Ice tears",
  [CollectibleType.NEPTUNUS]: "Open the floodgates",
  [CollectibleType.PLUTO]: "Size down",
  [CollectibleType.VOODOO_HEAD]: "Extra curse rooms",
  [CollectibleType.EYE_DROPS]: "Tears up",
  [CollectibleType.ACT_OF_CONTRITION]: "Tears up, you feel forgiven",
  [CollectibleType.MEMBER_CARD]: "Exclusive access!",
  [CollectibleType.BATTERY_PACK]: "Instant energy!",
  [CollectibleType.MOMS_BRACELET]: "Mother's strength",
  [CollectibleType.SCOOPER]: "Plop!",
  [CollectibleType.OCULAR_RIFT]: "Stare into the abyss",
  [CollectibleType.BOILED_BABY]: "Messy friend",
  [CollectibleType.FREEZER_BABY]: "Iced iced baby",
  [CollectibleType.ETERNAL_D6]: "???",
  [CollectibleType.BIRD_CAGE]: "Fat buddy",
  [CollectibleType.LARYNX]: "Hear my pain",
  [CollectibleType.LOST_SOUL]: "Protect him",
  // There is no `CollectibleType` with a value of 613.
  [CollectibleType.BLOOD_BOMBS]: "Bloody blast + HP up",
  [CollectibleType.LIL_DUMPY]: "Puffy buddy",
  [CollectibleType.BIRDS_EYE]: "It burns",
  [CollectibleType.LODESTONE]: "Magnetizing tears",
  [CollectibleType.ROTTEN_TOMATO]: "Delicious!",
  [CollectibleType.BIRTHRIGHT]: "???",
  // There is no `CollectibleType` with a value of 620.
  [CollectibleType.RED_STEW]: "Full HP + temporary DMG up",
  [CollectibleType.GENESIS]: "In the beginning",
  [CollectibleType.SHARP_KEY]: "Open your enemies",
  [CollectibleType.BOOSTER_PACK]: "Collect them all!",
  [CollectibleType.MEGA_MUSH]: "I'm a big boy now!",
  [CollectibleType.KNIFE_PIECE_1]: "???",
  [CollectibleType.KNIFE_PIECE_2]: "???",
  [CollectibleType.DEATH_CERTIFICATE]: "Where am I?",
  [CollectibleType.BOT_FLY]: "Defense drone",
  // There is no `CollectibleType` with a value of 630.
  [CollectibleType.MEAT_CLEAVER]: "Slice but no dice",
  [CollectibleType.EVIL_CHARM]: "Luck up + you feel protected",
  [CollectibleType.DOGMA]: "Ascended",
  [CollectibleType.PURGATORY]: "Help from beyond",
  [CollectibleType.STITCHES]: "Bait and switch",
  [CollectibleType.R_KEY]: "Time to start over",
  [CollectibleType.KNOCKOUT_DROPS]: "They pack a punch!",
  [CollectibleType.ERASER]: "Erase thy enemy",
  [CollectibleType.YUCK_HEART]: "Gross!",
  [CollectibleType.URN_OF_SOULS]: "Unleash their sorrow",
  [CollectibleType.AKELDAMA]: "Spill your guts",
  [CollectibleType.MAGIC_SKIN]: "All your desires fulfilled",
  [CollectibleType.REVELATION]: "Awaken your faith",
  [CollectibleType.CONSOLATION_PRIZE]: "+1 to lowest stat",
  [CollectibleType.TINYTOMA]: "Itching for revenge",
  [CollectibleType.BRIMSTONE_BOMBS]: "Demon blast +5 bombs",
  [CollectibleType.FOUR_FIVE_VOLT]: "Beat the juice out of them!",
  // There is no `CollectibleType` with a value of 648.
  [CollectibleType.FRUITY_PLUM]: "Bouncy friend",
  [CollectibleType.PLUM_FLUTE]: "Play time!",
  [CollectibleType.STAR_OF_BETHLEHEM]: "Follow the light",
  [CollectibleType.CUBE_BABY]: "Kick it!",
  [CollectibleType.VADE_RETRO]: "Begone!",
  [CollectibleType.FALSE_PHD]: "Worse pills + evil up",
  [CollectibleType.SPIN_TO_WIN]: "Let it rip!",
  // There is no `CollectibleType` with a value of 656.
  [CollectibleType.DAMOCLES_PASSIVE]: "A king's fortune... but at what cost?",
  [CollectibleType.VASCULITIS]: "Clogged enemies",
  [CollectibleType.GIANT_CELL]: "Micro friends",
  [CollectibleType.TROPICAMIDE]: "Tear size + range up",
  [CollectibleType.CARD_READING]: "A link to your future",
  [CollectibleType.QUINTS]: "They lurk inside",
  // There is no `CollectibleType` with a value of 662.
  [CollectibleType.TOOTH_AND_NAIL]: "You feel prickly",
  [CollectibleType.BINGE_EATER]: "All you can eat",
  [CollectibleType.GUPPYS_EYE]: "An eye for secrets",
  // There is no `CollectibleType` with a value of 666.
  [CollectibleType.STRAWMAN]: "A helping hand",
  [CollectibleType.DADS_NOTE]: "...",
  [CollectibleType.SAUSAGE]: "All stats up",
  [CollectibleType.OPTIONS]: "There might be options",
  [CollectibleType.CANDY_HEART]: "Power of love",
  [CollectibleType.POUND_OF_FLESH]: "Blood money",
  [CollectibleType.REDEMPTION]: "Deliver me from evil",
  [CollectibleType.SPIRIT_SHACKLES]: "Unfinished business",
  [CollectibleType.CRACKED_ORB]: "Shards of knowledge",
  [CollectibleType.EMPTY_HEART]: "It multiplies",
  [CollectibleType.ASTRAL_PROJECTION]: "The true out-of-body experience!",
  [CollectibleType.C_SECTION]: "Fetus shots",
  [CollectibleType.LIL_ABADDON]: "Abyssal friend",
  [CollectibleType.MONTEZUMAS_REVENGE]: "Oh no...",
  [CollectibleType.LIL_PORTAL]: "It hungers",
  [CollectibleType.WORM_FRIEND]: "Clingy buddy",
  [CollectibleType.BONE_SPURS]: "Break your enemies",
  [CollectibleType.HUNGRY_SOUL]: "Out for blood",
  [CollectibleType.JAR_OF_WISPS]: "Your faith grows",
  [CollectibleType.SOUL_LOCKET]: "Power of faith",
  [CollectibleType.FRIEND_FINDER]: "Best friends forever!",
  [CollectibleType.INNER_CHILD]: "Let him free",
  [CollectibleType.GLITCHED_CROWN]: "?????",
  [CollectibleType.JELLY_BELLY]: "Bounce away!",
  [CollectibleType.SACRED_ORB]: "Destined for greatness",
  [CollectibleType.SANGUINE_BOND]: "He awaits your offering",
  [CollectibleType.SWARM]: "Infest",
  [CollectibleType.HEARTBREAK]: "Eternal sorrow",
  [CollectibleType.BLOODY_GUST]: "May your rage bring haste",
  [CollectibleType.SALVATION]: "Divine protection",
  [CollectibleType.VANISHING_TWIN]: "He wants revenge",
  [CollectibleType.TWISTED_PAIR]: "Double trouble!",
  [CollectibleType.AZAZELS_RAGE]: "Ancient power",
  [CollectibleType.ECHO_CHAMBER]: "I can see see the future future future",
  [CollectibleType.ISAACS_TOMB]: "Buried memories",
  [CollectibleType.VENGEFUL_SPIRIT]: "Hot blooded",
  [CollectibleType.ESAU_JR]: "Lost brother",
  [CollectibleType.BERSERK]: "Rip and tear",
  [CollectibleType.DARK_ARTS]: "One with the shadows",
  [CollectibleType.ABYSS]: "Come forth from the depths",
  [CollectibleType.SUPPER]: "HP up",
  [CollectibleType.STAPLER]: "DMG up",
  [CollectibleType.SUPLEX]: "Angel breaker",
  [CollectibleType.BAG_OF_CRAFTING]: "Make your destiny",
  [CollectibleType.FLIP]: "Life and death",
  [CollectibleType.LEMEGETON]: "Item summoner",
  [CollectibleType.SUMPTORIUM]: "Return",
  [CollectibleType.RECALL]: "Come back",
  [CollectibleType.HOLD]: "Saved for later",
  [CollectibleType.KEEPERS_SACK]: "Spending power",
  [CollectibleType.KEEPERS_KIN]: "Under a rock",
  // There is no `CollectibleType` with a value of 718.
  [CollectibleType.KEEPERS_BOX]: "Portable shop",
  [CollectibleType.EVERYTHING_JAR]: "Anything is possible",
  [CollectibleType.TMTRAINER]:
    "Isaac and his mother lived alone in a small house on a hill",
  [CollectibleType.ANIMA_SOLA]: "Repent",
  [CollectibleType.SPINDOWN_DICE]: "-1",
  [CollectibleType.HYPERCOAGULATION]: "Thick blooded",
  [CollectibleType.IBS]: "Your stomach rumbles",
  [CollectibleType.HEMOPTYSIS]: "Double tap sneeze",
  [CollectibleType.GHOST_BOMBS]: "Spooky blast +5 bombs",
  [CollectibleType.GELLO]: "Demonic gestation",
  [CollectibleType.DECAP_ATTACK]: "Chuck away!",
  [CollectibleType.GLASS_EYE]: "DMG + luck up",
  [CollectibleType.STYE]: "DMG + range up",
  [CollectibleType.MOMS_RING]: "DMG up",
} as const satisfies Record<CollectibleType, string>;
