/* cspell:disable */

import { TrinketType } from "isaac-typescript-definitions";

export const DEFAULT_TRINKET_DESCRIPTION = "Unknown";

/** Maps trinket types to the real English descriptions from the "stringtable.sta" file. */
export const TRINKET_DESCRIPTIONS = {
  [TrinketType.NULL]: DEFAULT_TRINKET_DESCRIPTION,
  [TrinketType.SWALLOWED_PENNY]: "Gulp!",
  [TrinketType.PETRIFIED_POOP]: "It feels lucky?",
  [TrinketType.AAA_BATTERY]: "Trickle charge",
  [TrinketType.BROKEN_REMOTE]: "It's broken",
  [TrinketType.PURPLE_HEART]: "Challenge up",
  [TrinketType.BROKEN_MAGNET]: "It kinda works",
  [TrinketType.ROSARY_BEAD]: "Faith up",
  [TrinketType.CARTRIDGE]: "I remember these",
  [TrinketType.PULSE_WORM]: "Wub wub!",
  [TrinketType.WIGGLE_WORM]: "Wiggle waggle!",
  [TrinketType.RING_WORM]: "Woop woop!",
  [TrinketType.FLAT_WORM]: "Blub blub!",
  [TrinketType.STORE_CREDIT]: "YES!",
  [TrinketType.CALLUS]: "Your feet feel stronger",
  [TrinketType.LUCKY_ROCK]: "There's something inside it",
  [TrinketType.MOMS_TOENAIL]: "???",
  [TrinketType.BLACK_LIPSTICK]: "Evil up",
  [TrinketType.BIBLE_TRACT]: "Faith up",
  [TrinketType.PAPER_CLIP]: "Master of lockpicking",
  [TrinketType.MONKEY_PAW]: "Wish granted",
  [TrinketType.MYSTERIOUS_PAPER]: "???",
  [TrinketType.DAEMONS_TAIL]: "Evil up",
  [TrinketType.MISSING_POSTER]: "???",
  [TrinketType.BUTT_PENNY]: "Wealth of gas",
  [TrinketType.MYSTERIOUS_CANDY]: "Uh-oh!",
  [TrinketType.HOOK_WORM]: "Zip zoop!",
  [TrinketType.WHIP_WORM]: "Wooosh!",
  [TrinketType.BROKEN_ANKH]: "Eternal life?",
  [TrinketType.FISH_HEAD]: "It stinks",
  [TrinketType.PINKY_EYE]: "Poison shots",
  [TrinketType.PUSH_PIN]: "Piercing shots",
  [TrinketType.LIBERTY_CAP]: "Touch fuzzy, get dizzy",
  [TrinketType.UMBILICAL_CORD]: "Fetal protection",
  [TrinketType.CHILDS_HEART]: "It calls out to its brothers",
  [TrinketType.CURVED_HORN]: "DMG up",
  [TrinketType.RUSTED_KEY]: "It feels lucky?",
  [TrinketType.GOAT_HOOF]: "Speed up",
  [TrinketType.MOMS_PEARL]: "It emanates purity ",
  [TrinketType.CANCER]: "Yay, cancer!",
  [TrinketType.RED_PATCH]: "Your rage grows",
  [TrinketType.MATCH_STICK]: "Tastes like burning",
  [TrinketType.LUCKY_TOE]: "Luck up!",
  [TrinketType.CURSED_SKULL]: "Cursed?",
  [TrinketType.SAFETY_CAP]: "Don't swallow it",
  [TrinketType.ACE_OF_SPADES]: "Luck of the draw",
  [TrinketType.ISAACS_FORK]: "Consume thy enemy",
  [TrinketType.MISSING_PAGE]: "It glows with power",
  [TrinketType.BLOODY_PENNY]: "Wealth of health",
  [TrinketType.BURNT_PENNY]: "Wealth of chaos",
  [TrinketType.FLAT_PENNY]: "Wealth of answers",
  [TrinketType.COUNTERFEIT_PENNY]: "Wealth of wealth",
  [TrinketType.TICK]: "Well, that's not coming off",
  [TrinketType.ISAACS_HEAD]: "Dead friend",
  [TrinketType.MAGGYS_FAITH]: "Faith's reward",
  [TrinketType.JUDAS_TONGUE]: "Payment received ",
  [TrinketType.BLUE_BABYS_SOUL]: "Imaginary friend",
  [TrinketType.SAMSONS_LOCK]: "Your rage grows",
  [TrinketType.CAINS_EYE]: "May you see your destination",
  [TrinketType.EVES_BIRD_FOOT]: "Revenge from beyond",
  [TrinketType.LEFT_HAND]: "The left-hand path reaps dark rewards",
  [TrinketType.SHINY_ROCK]: "It shines for its brothers",
  [TrinketType.SAFETY_SCISSORS]: "Fuse cutter",
  [TrinketType.RAINBOW_WORM]: "Bleep bloop blop",
  [TrinketType.TAPE_WORM]: "Floooooooooop!",
  [TrinketType.LAZY_WORM]: "Pft",
  [TrinketType.CRACKED_DICE]: "You feel cursed... kinda.",
  [TrinketType.SUPER_MAGNET]: "It pulls",
  [TrinketType.FADED_POLAROID]: "You feel faded",
  [TrinketType.LOUSE]: "Itchy, tasty...",
  [TrinketType.BOBS_BLADDER]: "Creepy bombs",
  [TrinketType.WATCH_BATTERY]: "Lil charge",
  [TrinketType.BLASTING_CAP]: "Pop! Pop!",
  [TrinketType.STUD_FINDER]: "The ground below feels hollow...",
  [TrinketType.ERROR]: "Effect not found?",
  [TrinketType.POKER_CHIP]: "It's double down time!",
  [TrinketType.BLISTER]: "Bounce back!",
  [TrinketType.SECOND_HAND]: "Extended stat effect time!",
  [TrinketType.ENDLESS_NAMELESS]: "I'm stuck in a loop...",
  [TrinketType.BLACK_FEATHER]: "With darkness comes power",
  [TrinketType.BLIND_RAGE]: "Blind to damage",
  [TrinketType.GOLDEN_HORSE_SHOE]: "Feel lucky?",
  [TrinketType.STORE_KEY]: "Stores are open",
  [TrinketType.RIB_OF_GREED]: "Feels greedy",
  [TrinketType.KARMA]: "Karma up",
  [TrinketType.LIL_LARVA]: "The poop is moving...",
  [TrinketType.MOMS_LOCKET]: "You feel her love",
  [TrinketType.NO]: "Never again!",
  [TrinketType.CHILD_LEASH]: "Keep your friends close...",
  [TrinketType.BROWN_CAP]: "Fartoom!",
  [TrinketType.MECONIUM]: "Eww",
  [TrinketType.CRACKED_CROWN]: "Stat booster",
  [TrinketType.USED_DIAPER]: "You stink",
  [TrinketType.FISH_TAIL]: "It also stinks!",
  [TrinketType.BLACK_TOOTH]: "It looks dead",
  [TrinketType.OUROBOROS_WORM]: "Foop foop!",
  [TrinketType.TONSIL]: "Sick...",
  [TrinketType.NOSE_GOBLIN]: "Seems magic...",
  [TrinketType.SUPER_BALL]: "Boing!",
  [TrinketType.VIBRANT_BULB]: "It needs power",
  [TrinketType.DIM_BULB]: "I think it's broken",
  [TrinketType.FRAGMENTED_CARD]: "Double moon",
  [TrinketType.EQUALITY]: "=",
  [TrinketType.WISH_BONE]: "Make a wish",
  [TrinketType.BAG_LUNCH]: "I wonder what it is",
  [TrinketType.LOST_CORK]: "Uncorked",
  [TrinketType.CROW_HEART]: "Drain me",
  [TrinketType.WALNUT]: "That's a hard nut to crack!",
  [TrinketType.DUCT_TAPE]: "Stuck!",
  [TrinketType.SILVER_DOLLAR]: "Feels lucky...",
  [TrinketType.BLOODY_CROWN]: "Drips with blood...",
  [TrinketType.PAY_TO_WIN]: "...",
  [TrinketType.LOCUST_OF_WRATH]: "I bring War",
  [TrinketType.LOCUST_OF_PESTILENCE]: "I bring Pestilence",
  [TrinketType.LOCUST_OF_FAMINE]: "I bring Famine",
  [TrinketType.LOCUST_OF_DEATH]: "I bring Death",
  [TrinketType.LOCUST_OF_CONQUEST]: "I bring Conquest",
  [TrinketType.BAT_WING]: "They are growing...",
  [TrinketType.STEM_CELL]: "Regen!",
  [TrinketType.HAIRPIN]: "Danger charge",
  [TrinketType.WOODEN_CROSS]: "My faith protects me",
  [TrinketType.BUTTER]: "Can't hold it!",
  [TrinketType.FILIGREE_FEATHERS]: "Angelic spoils",
  [TrinketType.DOOR_STOP]: "Hold the door",
  [TrinketType.EXTENSION_CORD]: "Charged friends",
  [TrinketType.ROTTEN_PENNY]: "Wealth of flies",
  [TrinketType.BABY_BENDER]: "Feed them magic!",
  [TrinketType.FINGER_BONE]: "It looks brittle",
  [TrinketType.JAW_BREAKER]: "Don't chew on it",
  [TrinketType.CHEWED_PEN]: "It's leaking",
  [TrinketType.BLESSED_PENNY]: "Wealth of purity",
  [TrinketType.BROKEN_SYRINGE]: "Mystery medicine",
  [TrinketType.SHORT_FUSE]: "Faster explosions",
  [TrinketType.GIGANTE_BEAN]: "Mega farts",
  [TrinketType.LIGHTER]: "Watch the world burn",
  [TrinketType.BROKEN_PADLOCK]: "Bombs are key",
  [TrinketType.MYOSOTIS]: "Forget me not...",
  [TrinketType.M]: "t's broken9Reroll your dest       ",
  [TrinketType.TEARDROP_CHARM]: "It feels lucky",
  [TrinketType.APPLE_OF_SODOM]: "It feels empty",
  [TrinketType.FORGOTTEN_LULLABY]: "Sing for your friends",
  [TrinketType.BETHS_FAITH]: "My faith protects me",
  [TrinketType.OLD_CAPACITOR]: "Voltage starving",
  [TrinketType.BRAIN_WORM]: "Ding!",
  [TrinketType.PERFECTION]: "Luck way up. Don't lose it!",
  [TrinketType.DEVILS_CROWN]: "His special customer",
  [TrinketType.CHARGED_PENNY]: "Wealth of power",
  [TrinketType.FRIENDSHIP_NECKLACE]: "Gather round",
  [TrinketType.PANIC_BUTTON]: "Push in case of emergency",
  [TrinketType.BLUE_KEY]: "Look between the rooms",
  [TrinketType.FLAT_FILE]: "No more spikes",
  [TrinketType.TELESCOPE_LENS]: "Seek the stars",
  [TrinketType.MOMS_LOCK]: "A piece of her love",
  [TrinketType.DICE_BAG]: "Bonus roll",
  [TrinketType.HOLY_CROWN]: "Walk the path of the saint",
  [TrinketType.MOTHERS_KISS]: "HP up",
  [TrinketType.TORN_CARD]: "Death awaits",
  [TrinketType.TORN_POCKET]: "A hole in your pocket",
  [TrinketType.GILDED_KEY]: "Less is more",
  [TrinketType.LUCKY_SACK]: "Free goodies!",
  [TrinketType.WICKED_CROWN]: "Walk the path of the wicked",
  [TrinketType.AZAZELS_STUMP]: "Unleash your inner demon",
  [TrinketType.DINGLE_BERRY]: "Oops!",
  [TrinketType.RING_CAP]: "Twice the bang!",
  [TrinketType.NUH_UH]: "Don't want!",
  [TrinketType.MODELING_CLAY]: "???",
  [TrinketType.POLISHED_BONE]: "Friends from beyond",
  [TrinketType.HOLLOW_HEART]: "A brittle blessing",
  [TrinketType.KIDS_DRAWING]: "Looks familiar...",
  [TrinketType.CRYSTAL_KEY]: "Call to the other side",
  [TrinketType.KEEPERS_BARGAIN]: "Money talks",
  [TrinketType.CURSED_PENNY]: "Wealth of misery",
  [TrinketType.YOUR_SOUL]: "Give it to me",
  [TrinketType.NUMBER_MAGNET]: "6",
  [TrinketType.STRANGE_KEY]: "What could it open?",
  [TrinketType.LIL_CLOT]: "Mini friend",
  [TrinketType.TEMPORARY_TATTOO]: "You feel braver",
  [TrinketType.SWALLOWED_M80]: "Bang!",
  [TrinketType.RC_REMOTE]: "Controllable buddies!",
  [TrinketType.FOUND_SOUL]: "Finally!",
  [TrinketType.EXPANSION_PACK]: "Fun extras",
  [TrinketType.BETHS_ESSENCE]: "Virtue's reward",
  [TrinketType.TWINS]: "I'm seeing double...",
  [TrinketType.ADOPTION_PAPERS]: "Give them a home",
  [TrinketType.CRICKET_LEG]: "Infested",
  [TrinketType.APOLLYONS_BEST_FRIEND]: "Attack buddy",
  [TrinketType.BROKEN_GLASSES]: "Double vision?",
  [TrinketType.ICE_CUBE]: "Stay frosty",
  [TrinketType.SIGIL_OF_BAPHOMET]: "Revel in death",
} as const satisfies Record<TrinketType, string>;
