import { TrinketType } from "isaac-typescript-definitions";

export const DEFAULT_TRINKET_NAME = "Unknown";

/**
 * Maps trinket types to the real English names from the "stringtable.sta" file.
 *
 * For a mapping of name to `TrinketType`, see `TRINKET_NAME_TO_TYPE_MAP`.
 */
export const TRINKET_NAMES = {
  [TrinketType.NULL]: DEFAULT_TRINKET_NAME,
  [TrinketType.SWALLOWED_PENNY]: "Swallowed Penny",
  [TrinketType.PETRIFIED_POOP]: "Petrified Poop",
  [TrinketType.AAA_BATTERY]: "AAA Battery",
  [TrinketType.BROKEN_REMOTE]: "Broken Remote",
  [TrinketType.PURPLE_HEART]: "Purple Heart",
  [TrinketType.BROKEN_MAGNET]: "Broken Magnet",
  [TrinketType.ROSARY_BEAD]: "Rosary Bead",
  [TrinketType.CARTRIDGE]: "Cartridge",
  [TrinketType.PULSE_WORM]: "Pulse Worm",
  [TrinketType.WIGGLE_WORM]: "Wiggle Worm",
  [TrinketType.RING_WORM]: "Ring Worm",
  [TrinketType.FLAT_WORM]: "Flat Worm",
  [TrinketType.STORE_CREDIT]: "Store Credit",
  [TrinketType.CALLUS]: "Callus",
  [TrinketType.LUCKY_ROCK]: "Lucky Rock",
  [TrinketType.MOMS_TOENAIL]: "Mom's Toenail",
  [TrinketType.BLACK_LIPSTICK]: "Black Lipstick",
  [TrinketType.BIBLE_TRACT]: "Bible Tract",
  [TrinketType.PAPER_CLIP]: "Paper Clip",
  [TrinketType.MONKEY_PAW]: "Monkey Paw",
  [TrinketType.MYSTERIOUS_PAPER]: "Mysterious Paper",
  [TrinketType.DAEMONS_TAIL]: "Daemon's Tail",
  [TrinketType.MISSING_POSTER]: "Missing Poster",
  [TrinketType.BUTT_PENNY]: "Butt Penny",
  [TrinketType.MYSTERIOUS_CANDY]: "Mysterious Candy",
  [TrinketType.HOOK_WORM]: "Hook Worm",
  [TrinketType.WHIP_WORM]: "Whip Worm",
  [TrinketType.BROKEN_ANKH]: "Broken Ankh",
  [TrinketType.FISH_HEAD]: "Fish Head",
  [TrinketType.PINKY_EYE]: "Pinky Eye",
  [TrinketType.PUSH_PIN]: "Push Pin",
  [TrinketType.LIBERTY_CAP]: "Liberty Cap",
  [TrinketType.UMBILICAL_CORD]: "Umbilical Cord",
  [TrinketType.CHILDS_HEART]: "Child's Heart",
  [TrinketType.CURVED_HORN]: "Curved Horn",
  [TrinketType.RUSTED_KEY]: "Rusted Key",
  [TrinketType.GOAT_HOOF]: "Goat Hoof",
  [TrinketType.MOMS_PEARL]: "Mom's Pearl",
  [TrinketType.CANCER]: "Cancer",
  [TrinketType.RED_PATCH]: "Red Patch",
  [TrinketType.MATCH_STICK]: "Match Stick",
  [TrinketType.LUCKY_TOE]: "Lucky Toe",
  [TrinketType.CURSED_SKULL]: "Cursed Skull",
  [TrinketType.SAFETY_CAP]: "Safety Cap",
  [TrinketType.ACE_OF_SPADES]: "Ace of Spades",
  [TrinketType.ISAACS_FORK]: "Isaac's Fork",
  // There is no `TrinketType` with a value of 47.
  [TrinketType.MISSING_PAGE]: "A Missing Page",
  [TrinketType.BLOODY_PENNY]: "Bloody Penny",
  [TrinketType.BURNT_PENNY]: "Burnt Penny",
  [TrinketType.FLAT_PENNY]: "Flat Penny",
  [TrinketType.COUNTERFEIT_PENNY]: "Counterfeit Penny",
  [TrinketType.TICK]: "Tick",
  [TrinketType.ISAACS_HEAD]: "Isaac's Head",
  [TrinketType.MAGGYS_FAITH]: "Maggy's Faith",
  [TrinketType.JUDAS_TONGUE]: "Judas' Tongue",
  [TrinketType.BLUE_BABYS_SOUL]: "???'s Soul",
  [TrinketType.SAMSONS_LOCK]: "Samson's Lock",
  [TrinketType.CAINS_EYE]: "Cain's Eye",
  [TrinketType.EVES_BIRD_FOOT]: "Eve's Bird Foot",
  [TrinketType.LEFT_HAND]: "The Left Hand",
  [TrinketType.SHINY_ROCK]: "Shiny Rock",
  [TrinketType.SAFETY_SCISSORS]: "Safety Scissors",
  [TrinketType.RAINBOW_WORM]: "Rainbow Worm",
  [TrinketType.TAPE_WORM]: "Tape Worm",
  [TrinketType.LAZY_WORM]: "Lazy Worm",
  [TrinketType.CRACKED_DICE]: "Cracked Dice",
  [TrinketType.SUPER_MAGNET]: "Super Magnet",
  [TrinketType.FADED_POLAROID]: "Faded Polaroid",
  [TrinketType.LOUSE]: "Louse",
  [TrinketType.BOBS_BLADDER]: "Bob's Bladder",
  [TrinketType.WATCH_BATTERY]: "Watch Battery",
  [TrinketType.BLASTING_CAP]: "Blasting Cap",
  [TrinketType.STUD_FINDER]: "Stud Finder",
  [TrinketType.ERROR]: "Error",
  [TrinketType.POKER_CHIP]: "Poker Chip",
  [TrinketType.BLISTER]: "Blister",
  [TrinketType.SECOND_HAND]: "Second Hand",
  [TrinketType.ENDLESS_NAMELESS]: "Endless Nameless",
  [TrinketType.BLACK_FEATHER]: "Black Feather",
  [TrinketType.BLIND_RAGE]: "Blind Rage",
  [TrinketType.GOLDEN_HORSE_SHOE]: "Golden Horse Shoe",
  [TrinketType.STORE_KEY]: "Store Key",
  [TrinketType.RIB_OF_GREED]: "Rib of Greed",
  [TrinketType.KARMA]: "Karma",
  [TrinketType.LIL_LARVA]: "Lil Larva",
  [TrinketType.MOMS_LOCKET]: "Mom's Locket",
  [TrinketType.NO]: "NO!",
  [TrinketType.CHILD_LEASH]: "Child Leash",
  [TrinketType.BROWN_CAP]: "Brown Cap",
  [TrinketType.MECONIUM]: "Meconium",
  [TrinketType.CRACKED_CROWN]: "Cracked Crown",
  [TrinketType.USED_DIAPER]: "Used Diaper",
  [TrinketType.FISH_TAIL]: "Fish Tail",
  [TrinketType.BLACK_TOOTH]: "Black Tooth",
  [TrinketType.OUROBOROS_WORM]: "Ouroboros Worm",
  [TrinketType.TONSIL]: "Tonsil",
  [TrinketType.NOSE_GOBLIN]: "Nose Goblin",
  [TrinketType.SUPER_BALL]: "Super Ball",
  [TrinketType.VIBRANT_BULB]: "Vibrant Bulb",
  [TrinketType.DIM_BULB]: "Dim Bulb",
  [TrinketType.FRAGMENTED_CARD]: "Fragmented Card",
  [TrinketType.EQUALITY]: "Equality!",
  [TrinketType.WISH_BONE]: "Wish Bone",
  [TrinketType.BAG_LUNCH]: "Bag Lunch",
  [TrinketType.LOST_CORK]: "Lost Cork",
  [TrinketType.CROW_HEART]: "Crow Heart",
  [TrinketType.WALNUT]: "Walnut",
  [TrinketType.DUCT_TAPE]: "Duct Tape",
  [TrinketType.SILVER_DOLLAR]: "Silver Dollar",
  [TrinketType.BLOODY_CROWN]: "Bloody Crown",
  [TrinketType.PAY_TO_WIN]: "Pay To Win",
  [TrinketType.LOCUST_OF_WRATH]: "Locust of War",
  [TrinketType.LOCUST_OF_PESTILENCE]: "Locust of Pestilence",
  [TrinketType.LOCUST_OF_FAMINE]: "Locust of Famine",
  [TrinketType.LOCUST_OF_DEATH]: "Locust of Death",
  [TrinketType.LOCUST_OF_CONQUEST]: "Locust of Conquest",
  [TrinketType.BAT_WING]: "Bat Wing",
  [TrinketType.STEM_CELL]: "Stem Cell",
  [TrinketType.HAIRPIN]: "Hairpin",
  [TrinketType.WOODEN_CROSS]: "Wooden Cross",
  [TrinketType.BUTTER]: "Butter!",
  [TrinketType.FILIGREE_FEATHERS]: "Filigree Feather",
  [TrinketType.DOOR_STOP]: "Door Stop",
  [TrinketType.EXTENSION_CORD]: "Extension Cord",
  [TrinketType.ROTTEN_PENNY]: "Rotten Penny",
  [TrinketType.BABY_BENDER]: "Baby-Bender",
  [TrinketType.FINGER_BONE]: "Finger Bone",
  [TrinketType.JAW_BREAKER]: "Jawbreaker",
  [TrinketType.CHEWED_PEN]: "Chewed Pen",
  [TrinketType.BLESSED_PENNY]: "Blessed Penny",
  [TrinketType.BROKEN_SYRINGE]: "Broken Syringe",
  [TrinketType.SHORT_FUSE]: "Short Fuse",
  [TrinketType.GIGANTE_BEAN]: "Gigante Bean",
  [TrinketType.LIGHTER]: "A Lighter",
  [TrinketType.BROKEN_PADLOCK]: "Broken Padlock",
  [TrinketType.MYOSOTIS]: "Myosotis",
  [TrinketType.M]: " 'M",
  [TrinketType.TEARDROP_CHARM]: "Teardrop Charm",
  [TrinketType.APPLE_OF_SODOM]: "Apple of Sodom",
  [TrinketType.FORGOTTEN_LULLABY]: "Forgotten Lullaby",
  [TrinketType.BETHS_FAITH]: "Beth's Faith",
  [TrinketType.OLD_CAPACITOR]: "Old Capacitor",
  [TrinketType.BRAIN_WORM]: "Brain Worm",
  [TrinketType.PERFECTION]: "Perfection",
  [TrinketType.DEVILS_CROWN]: "Devil's Crown",
  [TrinketType.CHARGED_PENNY]: "Charged Penny",
  [TrinketType.FRIENDSHIP_NECKLACE]: "Friendship Necklace",
  [TrinketType.PANIC_BUTTON]: "Panic Button",
  [TrinketType.BLUE_KEY]: "Blue Key",
  [TrinketType.FLAT_FILE]: "Flat File",
  [TrinketType.TELESCOPE_LENS]: "Telescope Lens",
  [TrinketType.MOMS_LOCK]: "Mom's Lock",
  [TrinketType.DICE_BAG]: "Dice Bag",
  [TrinketType.HOLY_CROWN]: "Holy Crown",
  [TrinketType.MOTHERS_KISS]: "Mother's Kiss",
  [TrinketType.TORN_CARD]: "Torn Card",
  [TrinketType.TORN_POCKET]: "Torn Pocket",
  [TrinketType.GILDED_KEY]: "Gilded Key",
  [TrinketType.LUCKY_SACK]: "Lucky Sack",
  [TrinketType.WICKED_CROWN]: "Wicked Crown",
  [TrinketType.AZAZELS_STUMP]: "Azazel's Stump",
  [TrinketType.DINGLE_BERRY]: "Dingle Berry",
  [TrinketType.RING_CAP]: "Ring Cap",
  [TrinketType.NUH_UH]: "Nuh Uh!",
  [TrinketType.MODELING_CLAY]: "Modeling Clay",
  [TrinketType.POLISHED_BONE]: "Polished Bone",
  [TrinketType.HOLLOW_HEART]: "Hollow Heart",
  [TrinketType.KIDS_DRAWING]: "Kid's Drawing",
  [TrinketType.CRYSTAL_KEY]: "Crystal Key",
  [TrinketType.KEEPERS_BARGAIN]: "Keeper's Bargain",
  [TrinketType.CURSED_PENNY]: "Cursed Penny",
  [TrinketType.YOUR_SOUL]: "Your Soul",
  [TrinketType.NUMBER_MAGNET]: "Number Magnet",
  [TrinketType.STRANGE_KEY]: "Strange Key",
  [TrinketType.LIL_CLOT]: "Lil Clot",
  [TrinketType.TEMPORARY_TATTOO]: "Temporary Tattoo",
  [TrinketType.SWALLOWED_M80]: "Swallowed M80",
  [TrinketType.RC_REMOTE]: "RC Remote",
  [TrinketType.FOUND_SOUL]: "Found Soul",
  [TrinketType.EXPANSION_PACK]: "Expansion Pack",
  [TrinketType.BETHS_ESSENCE]: "Beth's Essence",
  [TrinketType.TWINS]: "The Twins",
  [TrinketType.ADOPTION_PAPERS]: "Adoption Papers",
  [TrinketType.CRICKET_LEG]: "Cricket Leg",
  [TrinketType.APOLLYONS_BEST_FRIEND]: "Apollyon's Best Friend",
  [TrinketType.BROKEN_GLASSES]: "Broken Glasses",
  [TrinketType.ICE_CUBE]: "Ice Cube",
  [TrinketType.SIGIL_OF_BAPHOMET]: "Sigil of Baphomet",
} as const satisfies Record<TrinketType, string>;
