runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: lts/*
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash # Composite jobs must specify the shell.
