runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

    - name: Install dependencies
      # TODO: Update dependencies to latest.
      #run: npm ci
      run: npm install --force
      shell: bash # Composite jobs must specify the shell.
