import { Card } from "isaac-typescript-definitions";

export const DEFAULT_CARD_NAME = "Unknown";

// This is a temporary map due to missing features in the vanilla API.
export const CARD_NAMES: { readonly [key in Card]: string } = {
  [Card.NULL]: DEFAULT_CARD_NAME,
  [Card.FOOL]: "0 - The Fool",
  [Card.MAGICIAN]: "I - The Magician",
  [Card.HIGH_PRIESTESS]: "II - The High Priestess",
  [Card.EMPRESS]: "III - The Empress",
  [Card.EMPEROR]: "IV - The Emperor",
  [Card.HIEROPHANT]: "V - The Hierophant",
  [Card.LOVERS]: "VI - The Lovers",
  [Card.CHARIOT]: "VII - The Chariot",
  [Card.JUSTICE]: "VIII - Justice",
  [Card.HERMIT]: "IX - The Hermit",
  [Card.WHEEL_OF_FORTUNE]: "X - Wheel of Fortune",
  [Card.STRENGTH]: "XI - Strength",
  [Card.HANGED_MAN]: "XII - The Hanged Man",
  [Card.DEATH]: "XIII - Death",
  [Card.TEMPERANCE]: "XIV - Temperance",
  [Card.DEVIL]: "XV - The Devil",
  [Card.TOWER]: "XVI - The Tower",
  [Card.STARS]: "XVII - The Stars",
  [Card.MOON]: "XVIII - The Moon",
  [Card.SUN]: "XIX - The Sun",
  [Card.JUDGEMENT]: "XX - Judgement",
  [Card.WORLD]: "XXI - The World",
  [Card.CLUBS_2]: "2 of Clubs",
  [Card.DIAMONDS_2]: "2 of Diamonds",
  [Card.SPADES_2]: "2 of Spades",
  [Card.HEARTS_2]: "2 of Hearts",
  [Card.ACE_OF_CLUBS]: "Ace of Clubs",
  [Card.ACE_OF_DIAMONDS]: "Ace of Diamonds",
  [Card.ACE_OF_SPADES]: "Ace of Spades",
  [Card.ACE_OF_HEARTS]: "Ace of Hearts",
  [Card.JOKER]: "Joker",
  [Card.RUNE_HAGALAZ]: "Hagalaz",
  [Card.RUNE_JERA]: "Jera",
  [Card.RUNE_EHWAZ]: "Ehwaz",
  [Card.RUNE_DAGAZ]: "Dagaz",
  [Card.RUNE_ANSUZ]: "Ansuz",
  [Card.RUNE_PERTHRO]: "Perthro",
  [Card.RUNE_BERKANO]: "Berkano",
  [Card.RUNE_ALGIZ]: "Algiz",
  [Card.RUNE_BLANK]: "Blank Rune",
  [Card.RUNE_BLACK]: "Black Rune",
  [Card.CHAOS]: "Chaos Card",
  [Card.CREDIT]: "Credit Card",
  [Card.RULES]: "Rules Card",
  [Card.AGAINST_HUMANITY]: "A Card Against Humanity",
  [Card.SUICIDE_KING]: "Suicide King",
  [Card.GET_OUT_OF_JAIL_FREE]: "Get Out Of Jail Free Card",
  [Card.QUESTION_MARK]: "? Card",
  [Card.DICE_SHARD]: "Dice Shard",
  [Card.EMERGENCY_CONTACT]: "Emergency Contact",
  [Card.HOLY]: "Holy Card",
  [Card.HUGE_GROWTH]: "Huge Growth",
  [Card.ANCIENT_RECALL]: "Ancient Recall",
  [Card.ERA_WALK]: "Era Walk",
  [Card.RUNE_SHARD]: "Rune Shard",
  [Card.REVERSE_FOOL]: "0 - The Fool?",
  [Card.REVERSE_MAGICIAN]: "I - The Magician?",
  [Card.REVERSE_HIGH_PRIESTESS]: "II - The High Priestess?",
  [Card.REVERSE_EMPRESS]: "III - The Empress?",
  [Card.REVERSE_EMPEROR]: "IV - The Emperor?",
  [Card.REVERSE_HIEROPHANT]: "V - The Hierophant?",
  [Card.REVERSE_LOVERS]: "VI - The Lovers?",
  [Card.REVERSE_CHARIOT]: "VII - The Chariot?",
  [Card.REVERSE_JUSTICE]: "VIII - Justice?",
  [Card.REVERSE_HERMIT]: "IX - The Hermit?",
  [Card.REVERSE_WHEEL_OF_FORTUNE]: "X - Wheel of Fortune?",
  [Card.REVERSE_STRENGTH]: "XI - Strength?",
  [Card.REVERSE_HANGED_MAN]: "XII - The Hanged Man?",
  [Card.REVERSE_DEATH]: "XIII - Death?",
  [Card.REVERSE_TEMPERANCE]: "XIV - Temperance?",
  [Card.REVERSE_DEVIL]: "XV - The Devil?",
  [Card.REVERSE_TOWER]: "XVI - The Tower?",
  [Card.REVERSE_STARS]: "XVII - The Stars?",
  [Card.REVERSE_MOON]: "XVIII - The Moon?",
  [Card.REVERSE_SUN]: "XIX - The Sun?",
  [Card.REVERSE_JUDGEMENT]: "XX - Judgement?",
  [Card.REVERSE_WORLD]: "XXI - The World?",
  [Card.CRACKED_KEY]: "Cracked Key",
  [Card.QUEEN_OF_HEARTS]: "Queen of Hearts",
  [Card.WILD]: "Wild Card",
  [Card.SOUL_ISAAC]: "Soul of Isaac",
  [Card.SOUL_MAGDALENE]: "Soul of Magdalene",
  [Card.SOUL_CAIN]: "Soul of Cain",
  [Card.SOUL_JUDAS]: "Soul of Judas",
  [Card.SOUL_BLUE_BABY]: "Soul of ???",
  [Card.SOUL_EVE]: "Soul of Eve",
  [Card.SOUL_SAMSON]: "Soul of Samson",
  [Card.SOUL_AZAZEL]: "Soul of Azazel",
  [Card.SOUL_LAZARUS]: "Soul of Lazarus",
  [Card.SOUL_EDEN]: "Soul of Eden",
  [Card.SOUL_LOST]: "Soul of the Lost",
  [Card.SOUL_LILITH]: "Soul of Lilith",
  [Card.SOUL_KEEPER]: "Soul of the Keeper",
  [Card.SOUL_APOLLYON]: "Soul of Apollyon",
  [Card.SOUL_FORGOTTEN]: "Soul of the Forgotten",
  [Card.SOUL_BETHANY]: "Soul of Bethany",
  [Card.SOUL_JACOB]: "Soul of Jacob and Esau",
};
