import {
  ItemConfigPillEffectClass,
  PillEffect,
} from "isaac-typescript-definitions";

export const DEFAULT_PILL_EFFECT_CLASS = ItemConfigPillEffectClass.MODDED;

export const PILL_EFFECT_CLASSES: {
  readonly [key in PillEffect]: ItemConfigPillEffectClass;
} = {
  [PillEffect.BAD_GAS]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.BAD_TRIP]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.BALLS_OF_STEEL]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.BOMBS_ARE_KEYS]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.EXPLOSIVE_DIARRHEA]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.FULL_HEALTH]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.HEALTH_DOWN]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.HEALTH_UP]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.I_FOUND_PILLS]: ItemConfigPillEffectClass.JOKE,
  [PillEffect.PUBERTY]: ItemConfigPillEffectClass.JOKE,
  [PillEffect.PRETTY_FLY]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.RANGE_DOWN]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.RANGE_UP]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.SPEED_DOWN]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.SPEED_UP]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.TEARS_DOWN]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.TEARS_UP]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.LUCK_DOWN]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.LUCK_UP]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.TELEPILLS]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.FORTY_EIGHT_HOUR_ENERGY]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.HEMATEMESIS]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.PARALYSIS]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.I_CAN_SEE_FOREVER]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.PHEROMONES]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.AMNESIA]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.LEMON_PARTY]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.R_U_A_WIZARD]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.PERCS]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.ADDICTED]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.RELAX]: ItemConfigPillEffectClass.JOKE,
  [PillEffect.QUESTION_MARKS]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.ONE_MAKES_YOU_LARGER]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.ONE_MAKES_YOU_SMALL]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.INFESTED_EXCLAMATION]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.INFESTED_QUESTION]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.POWER]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.RETRO_VISION]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.FRIENDS_TILL_THE_END]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.X_LAX]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.SOMETHINGS_WRONG]: ItemConfigPillEffectClass.JOKE,
  [PillEffect.IM_DROWSY]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.IM_EXCITED]: ItemConfigPillEffectClass.MINOR,
  [PillEffect.GULP]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.HORF]: ItemConfigPillEffectClass.JOKE,
  [PillEffect.FEELS_LIKE_IM_WALKING_ON_SUNSHINE]:
    ItemConfigPillEffectClass.MINOR,
  [PillEffect.VURP]: ItemConfigPillEffectClass.MEDIUM,
  [PillEffect.SHOT_SPEED_DOWN]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.SHOT_SPEED_UP]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.EXPERIMENTAL]: ItemConfigPillEffectClass.MAJOR,
  [PillEffect.EXPERIMENTAL]: ItemConfigPillEffectClass.MAJOR,
};
