/* eslint-disable isaacscript/format-line-comments */
/* eslint-disable isaacscript/complete-sentences-line-comments */

export enum ISCFeature {
  // Callback logic
  CUSTOM_REVIVE = "CustomRevive",
  ESAU_JR_DETECTION = "EsauJrDetection",
  FLIP_DETECTION = "FlipDetection",
  GRID_ENTITY_COLLISION_DETECTION = "GridEntityCollisionDetection",
  GRID_ENTITY_DETECTION = "GridEntityDetection",
  GAME_REORDERED_CALLBACKS = "GameReorderedCallbacks",
  PLAYER_REORDERED_CALLBACKS = "PlayerReorderedCallbacks",

  // Extra features
  // CHARACTER_HEALTH_CONVERSION = "CharacterHealthConversion",
  // CHARACTER_STATS = "CharacterStats",
  // COLLECTIBLE_ITEM_POOL_TYPE = "CollectibleItemPoolType",
  CUSTOM_GRID_ENTITIES = "CustomGridEntities",
  // CUSTOM_HOTKEYS = "CustomHotkeys",
  // CUSTOM_PICKUPS = "CustomPickups",
  // CUSTOM_STAGES = "CustomStages",
  // CUSTOM_TRAPDOORS = "CustomTrapdoors",
  // DEBUG_DISPLAY = "DebugDisplay",
  // DEPLOY_JSON_ROOM = "DeployJSONRoom",
  // DISABLE_ALL_SOUND = "DisplayAllSound",
  // DISABLE_INPUTS = "DisableInputs",
  // FADE_IN_REMOVER = "FadeInRemover",
  // FAST_RESET = "FastReset",
  // FIRST_LAST = "FirstLast",
  // FORGOTTEN_SWITCH = "ForgottenSwitch",
  // EXTRA_CONSOLE_COMMANDS = "ExtraConsoleCommands",
  // PAUSE = "Pause",
  // PERSISTENT_ENTITIES = "PersistentEntities",
  // PICKUP_INDEX = "PickupIndex",
  // PLAYER_INVENTORY = "PlayerInventory",
  // PONY_DETECTION = "PonyDetection",
  // PREVENT_CHILD_ENTITIES = "PreventChildEntities",
  // PREVENT_COLLECTIBLE_ROTATION = "PreventCollectibleRotation",
  // ROOM_CLEAR_FRAME = "RoomClearFrame",
  // ROOM_HISTORY = "RoomHistory",
  RUN_IN_N_FRAMES = "RunInNFrames",
  // RUN_NEXT_ROOM = "RunNextRoom",
  SAVE_DATA_MANAGER = "SaveDataManager",
  // SIREN_HELPERS = "SirenHelpers",
  // STAGE_HISTORY = "StageHistory",
  // TAINTED_LAZARUS_PLAYERS = "TaintedLazarusPlayers",
}
