/* eslint-disable isaacscript/format-line-comments */
/* eslint-disable isaacscript/complete-sentences-line-comments */

export enum ISCFeature {
  // Callback logic
  CUSTOM_REVIVE = "CustomRevive",
  ESAU_JR_DETECTION = "EsauJrDetection",
  FLIP_DETECTION = "FlipDetection",
  GRID_ENTITY_COLLISION_DETECTION = "GridEntityCollisionDetection",
  GRID_ENTITY_DETECTION = "GridEntityDetection",
  GAME_REORDERED_CALLBACKS = "GameReorderedCallbacks",
  PLAYER_REORDERED_CALLBACKS = "PlayerReorderedCallbacks",

  // Extra features
  // CHARACTER_HEALTH_CONVERSION = "characterHealthConversion",
  // CHARACTER_STATS = "characterStats",
  // COLLECTIBLE_ITEM_POOL_TYPE = "collectibleItemPoolType",
  CUSTOM_GRID_ENTITIES = "CustomGridEntities",
  // CUSTOM_HOTKEYS = "customHotkeys",
  // CUSTOM_PICKUP = "customPickup",
  // CUSTOM_STAGE = "customStage",
  // CUSTOM_TRAPDOOR = "customTrapdoor",
  // DEBUG_DISPLAY = "debugDisplay",
  // DEPLOY_JSON_ROOM = "deployJSONRoom",
  // DISABLE_ALL_SOUND = "displayAllSound",
  // DISABLE_INPUTS = "disableInputs",
  // FADE_IN_REMOVER = "fadeInRemover",
  // FAST_RESET = "fastReset",
  // FIRST_LAST = "firstLast",
  // FORGOTTEN_SWITCH = "forgottenSwitch",
  // EXTRA_CONSOLE_COMMANDS = "extraConsoleCommands",
  // PAUSE = "pause",
  // PERSISTENT_ENTITIES = "persistentEntities",
  // PICKUP_INDEX = "pickupIndex",
  // PLAYER_INVENTORY = "playerInventory",
  // PONY_DETECTION = "ponyDetection",
  // PREVENT_CHILD_ENTITIES = "preventChildEntities",
  // PREVENT_COLLECTIBLE_ROTATION = "preventCollectibleRotation",
  // ROOM_CLEAR_FRAME = "roomClearFrame",
  // ROOM_HISTORY = "roomHistory",
  RUN_IN_N_FRAMES = "runInNFrames",
  // RUN_NEXT_ROOM = "runNextRoom",
  // SAVE_DATA_MANAGER = "saveDataManager",
  // SIREN_HELPERS = "sirenHelpers",
  // STAGE_HISTORY = "stageHistory",
  // TAINTED_LAZARUS_PLAYERS = "taintedLazarusPlayers",
}
