/** TODO */
export enum ModCallbackCustom2 {
  POST_AMBUSH_FINISHED,
  POST_AMBUSH_STARTED,
  POST_BOMB_EXPLODED,
  POST_BOMB_INIT_LATE,
  POST_BONE_SWING,
  POST_COLLECTIBLE_EMPTY,
  POST_COLLECTIBLE_INIT_FIRST,
  POST_CURSED_TELEPORT,
  POST_CUSTOM_REVIVE,
  POST_DICE_ROOM_ACTIVATED,
  POST_DOOR_RENDER,
  POST_DOOR_UPDATE,
  POST_EFFECT_INIT_LATE,
  POST_EFFECT_STATE_CHANGED,

  POST_KNIFE_INIT_LATE,
  POST_NEW_ROOM_EARLY,
  POST_PIT_RENDER,
  POST_ROOM_CLEAR_CHANGED,
  POST_SPIKES_RENDER,
  PRE_CUSTOM_REVIVE,
}
