/** TODO */
export enum ModCallbackCustom2 {
  POST_AMBUSH_FINISHED,
  POST_AMBUSH_STARTED,
  POST_BOMB_EXPLODED,
  POST_BOMB_INIT_LATE,
  POST_BONE_SWING,
  POST_COLLECTIBLE_EMPTY,
  POST_COLLECTIBLE_INIT_FIRST,
  POST_CURSED_TELEPORT,
  POST_CUSTOM_DOOR_ENTER,

  POST_NEW_ROOM_EARLY,
  POST_PIT_RENDER,
  POST_ROOM_CLEAR_CHANGED,
  POST_SPIKES_RENDER,
}
