/** Used with the `Game.GetStateFlag` and `Game.SetStateFlag` methods. */
export enum GameStateFlag {
  FAMINE_SPAWNED = 0,
  PESTILENCE_SPAWNED = 1,
  WAR_SPAWNED = 2,
  DEATH_SPAWNED = 3,
  BOSS_POOL_SWITCHED = 4,
  DEVIL_ROOM_SPAWNED = 5,
  DEVIL_ROOM_VISITED = 6,
  BOOK_REVELATIONS_USED = 7,
  BOOK_PICKED_UP = 8,
  WRATH_SPAWNED = 9,
  GLUTTONY_SPAWNED = 10,
  LUST_SPAWNED = 11,
  SLOTH_SPAWNED = 12,
  ENVY_SPAWNED = 13,
  PRIDE_SPAWNED = 14,
  GREED_SPAWNED = 15,
  SUPER_GREED_SPAWNED = 16,
  DONATION_SLOT_BROKEN = 17,
  DONATION_SLOT_JAMMED = 18,
  HEAVEN_PATH = 19,
  REBIRTH_BOSS_SWITCHED = 20,
  HAUNT_SELECTED = 21,
  ADVERSARY_SELECTED = 22,
  MR_FRED_SELECTED = 23,
  MAMA_GURDY_SELECTED = 24,
  URIEL_SPAWNED = 25,
  GABRIEL_SPAWNED = 26,
  FALLEN_SPAWNED = 27,
  HEADLESS_HORSEMAN_SPAWNED = 28,
  KRAMPUS_SPAWNED = 29,
  DONATION_SLOT_BLOWN = 30,
  SHOPKEEPER_KILLED = 31,
  ULTRA_PRIDE_SPAWNED = 32,
  BOSS_RUSH_DONE = 33,
  GREED_SLOT_JAMMED = 34,
  AFTERBIRTH_BOSS_SWITCHED = 35,
  BROWNIE_SELECTED = 36,
  SUPER_BUM_APPEARED = 37,
  BOSS_RUSH_DOOR_SPAWNED = 38,
  BLUE_WOMB_DOOR_SPAWNED = 39,
  BLUE_WOMB_DONE = 40,
  HEART_BOMB_COIN_PICKED = 41,
  AFTERBIRTH_PLUS_BOSS_SWITCHED = 42,
  SISTERS_VIS_SELECTED = 43,
  MAX_COINS_OBTAINED = 43,
  SECRET_PATH = 44,
  PERFECTION_SPAWNED = 45,
  MAUSOLEUM_HEART_KILLED = 46,

  /**
   * The "backwards path" refers to the Ascent. This flag is set when the player enters the trapdoor
   * after the strange door on Depths 2.
   */
  BACKWARDS_PATH_INIT = 47,

  /**
   * The "backwards path" refers to the Ascent. This flag is set when the player takes Dad's Note.
   */
  BACKWARDS_PATH = 48,
}
