export const DEFAULT_CARD_NAME = "Unknown";

export const CARD_NAMES: { readonly [key in Card]: string } = {
  [Card.CARD_RANDOM]: DEFAULT_CARD_NAME,
  [Card.CARD_NULL]: DEFAULT_CARD_NAME,
  [Card.CARD_FOOL]: "0 - The Fool",
  [Card.CARD_MAGICIAN]: "I - The Magician",
  [Card.CARD_HIGH_PRIESTESS]: "II - The High Priestess",
  [Card.CARD_EMPRESS]: "III - The Empress",
  [Card.CARD_EMPEROR]: "IV - The Emperor",
  [Card.CARD_HIEROPHANT]: "V - The Hierophant",
  [Card.CARD_LOVERS]: "VI - The Lovers",
  [Card.CARD_CHARIOT]: "VII - The Chariot",
  [Card.CARD_JUSTICE]: "VIII - Justice",
  [Card.CARD_HERMIT]: "IX - The Hermit",
  [Card.CARD_WHEEL_OF_FORTUNE]: "X - Wheel of Fortune",
  [Card.CARD_STRENGTH]: "XI - Strength",
  [Card.CARD_HANGED_MAN]: "XII - The Hanged Man",
  [Card.CARD_DEATH]: "XIII - Death",
  [Card.CARD_TEMPERANCE]: "XIV - Temperance",
  [Card.CARD_DEVIL]: "XV - The Devil",
  [Card.CARD_TOWER]: "XVI - The Tower",
  [Card.CARD_STARS]: "XVII - The Stars",
  [Card.CARD_MOON]: "XVIII - The Moon",
  [Card.CARD_SUN]: "XIX - The Sun",
  [Card.CARD_JUDGEMENT]: "XX - Judgement",
  [Card.CARD_WORLD]: "XXI - The World",
  [Card.CARD_CLUBS_2]: "2 of Clubs",
  [Card.CARD_DIAMONDS_2]: "2 of Diamonds",
  [Card.CARD_SPADES_2]: "2 of Spades",
  [Card.CARD_HEARTS_2]: "2 of Hearts",
  [Card.CARD_ACE_OF_CLUBS]: "Ace of Clubs",
  [Card.CARD_ACE_OF_DIAMONDS]: "Ace of Diamonds",
  [Card.CARD_ACE_OF_SPADES]: "Ace of Spades",
  [Card.CARD_ACE_OF_HEARTS]: "Ace of Hearts",
  [Card.CARD_JOKER]: "Joker",
  [Card.RUNE_HAGALAZ]: "Hagalaz",
  [Card.RUNE_JERA]: "Jera",
  [Card.RUNE_EHWAZ]: "Ehwaz",
  [Card.RUNE_DAGAZ]: "Dagaz",
  [Card.RUNE_ANSUZ]: "Ansuz",
  [Card.RUNE_PERTHRO]: "Perthro",
  [Card.RUNE_BERKANO]: "Berkano",
  [Card.RUNE_ALGIZ]: "Algiz",
  [Card.RUNE_BLANK]: "Blank Rune",
  [Card.RUNE_BLACK]: "Black Rune",
  [Card.CARD_CHAOS]: "Chaos Card",
  [Card.CARD_CREDIT]: "Credit Card",
  [Card.CARD_RULES]: "Rules Card",
  [Card.CARD_HUMANITY]: "A Card Against Humanity",
  [Card.CARD_SUICIDE_KING]: "Suicide King",
  [Card.CARD_GET_OUT_OF_JAIL]: "Get Out Of Jail Free Card",
  [Card.CARD_QUESTIONMARK]: "? Card",
  [Card.CARD_DICE_SHARD]: "Dice Shard",
  [Card.CARD_EMERGENCY_CONTACT]: "Emergency Contact",
  [Card.CARD_HOLY]: "Holy Card",
  [Card.CARD_HUGE_GROWTH]: "Huge Growth",
  [Card.CARD_ANCIENT_RECALL]: "Ancient Recall",
  [Card.CARD_ERA_WALK]: "Era Walk",
  [Card.RUNE_SHARD]: "Rune Shard",
  [Card.CARD_REVERSE_FOOL]: "0 - The Fool?",
  [Card.CARD_REVERSE_MAGICIAN]: "I - The Magician?",
  [Card.CARD_REVERSE_HIGH_PRIESTESS]: "II - The High Priestess?",
  [Card.CARD_REVERSE_EMPRESS]: "III - The Empress?",
  [Card.CARD_REVERSE_EMPEROR]: "IV - The Emperor?",
  [Card.CARD_REVERSE_HIEROPHANT]: "V - The Hierophant?",
  [Card.CARD_REVERSE_LOVERS]: "VI - The Lovers?",
  [Card.CARD_REVERSE_CHARIOT]: "VII - The Chariot?",
  [Card.CARD_REVERSE_JUSTICE]: "VIII - Justice?",
  [Card.CARD_REVERSE_HERMIT]: "IX - The Hermit?",
  [Card.CARD_REVERSE_WHEEL_OF_FORTUNE]: "X - Wheel of Fortune?",
  [Card.CARD_REVERSE_STRENGTH]: "XI - Strength?",
  [Card.CARD_REVERSE_HANGED_MAN]: "XII - The Hanged Man?",
  [Card.CARD_REVERSE_DEATH]: "XIII - Death?",
  [Card.CARD_REVERSE_TEMPERANCE]: "XIV - Temperance?",
  [Card.CARD_REVERSE_DEVIL]: "XV - The Devil?",
  [Card.CARD_REVERSE_TOWER]: "XVI - The Tower?",
  [Card.CARD_REVERSE_STARS]: "XVII - The Stars?",
  [Card.CARD_REVERSE_MOON]: "XVIII - The Moon?",
  [Card.CARD_REVERSE_SUN]: "XIX - The Sun?",
  [Card.CARD_REVERSE_JUDGEMENT]: "XX - Judgement?",
  [Card.CARD_REVERSE_WORLD]: "XXI - The World?",
  [Card.CARD_CRACKED_KEY]: "Cracked Key",
  [Card.CARD_QUEEN_OF_HEARTS]: "Queen of Hearts",
  [Card.CARD_WILD]: "Wild Card",
  [Card.CARD_SOUL_ISAAC]: "Soul of Isaac",
  [Card.CARD_SOUL_MAGDALENE]: "Soul of Magdalene",
  [Card.CARD_SOUL_CAIN]: "Soul of Cain",
  [Card.CARD_SOUL_JUDAS]: "Soul of Judas",
  [Card.CARD_SOUL_BLUEBABY]: "Soul of ???",
  [Card.CARD_SOUL_EVE]: "Soul of Eve",
  [Card.CARD_SOUL_SAMSON]: "Soul of Samson",
  [Card.CARD_SOUL_AZAZEL]: "Soul of Azazel",
  [Card.CARD_SOUL_LAZARUS]: "Soul of Lazarus",
  [Card.CARD_SOUL_EDEN]: "Soul of Eden",
  [Card.CARD_SOUL_LOST]: "Soul of the Lost",
  [Card.CARD_SOUL_LILITH]: "Soul of Lilith",
  [Card.CARD_SOUL_KEEPER]: "Soul of the Keeper",
  [Card.CARD_SOUL_APOLLYON]: "Soul of Apollyon",
  [Card.CARD_SOUL_FORGOTTEN]: "Soul of the Forgotten",
  [Card.CARD_SOUL_BETHANY]: "Soul of Bethany",
  [Card.CARD_SOUL_JACOB]: "Soul of Jacob and Esau",
  [Card.NUM_CARDS]: DEFAULT_CARD_NAME,
};
