/* eslint-disable sort-exports/sort-exports */

import { Card, ItemConfigCardType } from "isaac-typescript-definitions";

export const DEFAULT_CARD_TYPE = ItemConfigCardType.MODDED;

export const CARD_TYPES: { readonly [key in Card]: ItemConfigCardType } = {
  [Card.NULL]: ItemConfigCardType.NULL, // 0
  [Card.FOOL]: ItemConfigCardType.TAROT, // 1
  [Card.MAGICIAN]: ItemConfigCardType.TAROT, // 2
  [Card.HIGH_PRIESTESS]: ItemConfigCardType.TAROT, // 3
  [Card.EMPRESS]: ItemConfigCardType.TAROT, // 4
  [Card.EMPEROR]: ItemConfigCardType.TAROT, // 5
  [Card.HIEROPHANT]: ItemConfigCardType.TAROT, // 6
  [Card.LOVERS]: ItemConfigCardType.TAROT, // 7
  [Card.CHARIOT]: ItemConfigCardType.TAROT, // 8
  [Card.JUSTICE]: ItemConfigCardType.TAROT, // 9
  [Card.HERMIT]: ItemConfigCardType.TAROT, // 10
  [Card.WHEEL_OF_FORTUNE]: ItemConfigCardType.TAROT, // 11
  [Card.STRENGTH]: ItemConfigCardType.TAROT, // 12
  [Card.HANGED_MAN]: ItemConfigCardType.TAROT, // 13
  [Card.DEATH]: ItemConfigCardType.TAROT, // 14
  [Card.TEMPERANCE]: ItemConfigCardType.TAROT, // 15
  [Card.DEVIL]: ItemConfigCardType.TAROT, // 16
  [Card.TOWER]: ItemConfigCardType.TAROT, // 17
  [Card.STARS]: ItemConfigCardType.TAROT, // 18
  [Card.MOON]: ItemConfigCardType.TAROT, // 19
  [Card.SUN]: ItemConfigCardType.TAROT, // 20
  [Card.JUDGEMENT]: ItemConfigCardType.TAROT, // 21
  [Card.WORLD]: ItemConfigCardType.TAROT, // 22
  [Card.CLUBS_2]: ItemConfigCardType.SUIT, // 23
  [Card.DIAMONDS_2]: ItemConfigCardType.SUIT, // 24
  [Card.SPADES_2]: ItemConfigCardType.SUIT, // 25
  [Card.HEARTS_2]: ItemConfigCardType.SUIT, // 26
  [Card.ACE_OF_CLUBS]: ItemConfigCardType.SUIT, // 27
  [Card.ACE_OF_DIAMONDS]: ItemConfigCardType.SUIT, // 28
  [Card.ACE_OF_SPADES]: ItemConfigCardType.SUIT, // 29
  [Card.ACE_OF_HEARTS]: ItemConfigCardType.SUIT, // 30
  [Card.JOKER]: ItemConfigCardType.SUIT, // 31
  [Card.RUNE_HAGALAZ]: ItemConfigCardType.RUNE, // 32
  [Card.RUNE_JERA]: ItemConfigCardType.RUNE, // 33
  [Card.RUNE_EHWAZ]: ItemConfigCardType.RUNE, // 34
  [Card.RUNE_DAGAZ]: ItemConfigCardType.RUNE, // 35
  [Card.RUNE_ANSUZ]: ItemConfigCardType.RUNE, // 36
  [Card.RUNE_PERTHRO]: ItemConfigCardType.RUNE, // 37
  [Card.RUNE_BERKANO]: ItemConfigCardType.RUNE, // 38
  [Card.RUNE_ALGIZ]: ItemConfigCardType.RUNE, // 39
  [Card.RUNE_BLANK]: ItemConfigCardType.RUNE, // 40
  [Card.RUNE_BLACK]: ItemConfigCardType.RUNE, // 41
  [Card.CHAOS]: ItemConfigCardType.SPECIAL, // 42
  [Card.CREDIT]: ItemConfigCardType.SPECIAL, // 43
  [Card.RULES]: ItemConfigCardType.SPECIAL, // 44
  [Card.HUMANITY]: ItemConfigCardType.SPECIAL, // 45
  [Card.SUICIDE_KING]: ItemConfigCardType.SPECIAL, // 46
  [Card.GET_OUT_OF_JAIL_FREE]: ItemConfigCardType.SPECIAL, // 47
  [Card.QUESTION_MARK]: ItemConfigCardType.SPECIAL, // 48
  [Card.DICE_SHARD]: ItemConfigCardType.SPECIAL_OBJECT, // 49
  [Card.EMERGENCY_CONTACT]: ItemConfigCardType.SPECIAL_OBJECT, // 50
  [Card.HOLY]: ItemConfigCardType.SPECIAL, // 51
  [Card.HUGE_GROWTH]: ItemConfigCardType.SPECIAL, // 52
  [Card.ANCIENT_RECALL]: ItemConfigCardType.SPECIAL, // 53
  [Card.ERA_WALK]: ItemConfigCardType.SPECIAL, // 54
  [Card.RUNE_SHARD]: ItemConfigCardType.RUNE, // 55
  [Card.REVERSE_FOOL]: ItemConfigCardType.TAROT_REVERSE, // 56
  [Card.REVERSE_MAGICIAN]: ItemConfigCardType.TAROT_REVERSE, // 57
  [Card.REVERSE_HIGH_PRIESTESS]: ItemConfigCardType.TAROT_REVERSE, // 58
  [Card.REVERSE_EMPRESS]: ItemConfigCardType.TAROT_REVERSE, // 59
  [Card.REVERSE_EMPEROR]: ItemConfigCardType.TAROT_REVERSE, // 60
  [Card.REVERSE_HIEROPHANT]: ItemConfigCardType.TAROT_REVERSE, // 61
  [Card.REVERSE_LOVERS]: ItemConfigCardType.TAROT_REVERSE, // 62
  [Card.REVERSE_CHARIOT]: ItemConfigCardType.TAROT_REVERSE, // 63
  [Card.REVERSE_JUSTICE]: ItemConfigCardType.TAROT_REVERSE, // 64
  [Card.REVERSE_HERMIT]: ItemConfigCardType.TAROT_REVERSE, // 65
  [Card.REVERSE_WHEEL_OF_FORTUNE]: ItemConfigCardType.TAROT_REVERSE, // 66
  [Card.REVERSE_STRENGTH]: ItemConfigCardType.TAROT_REVERSE, // 67
  [Card.REVERSE_HANGED_MAN]: ItemConfigCardType.TAROT_REVERSE, // 68
  [Card.REVERSE_DEATH]: ItemConfigCardType.TAROT_REVERSE, // 69
  [Card.REVERSE_TEMPERANCE]: ItemConfigCardType.TAROT_REVERSE, // 70
  [Card.REVERSE_DEVIL]: ItemConfigCardType.TAROT_REVERSE, // 71
  [Card.REVERSE_TOWER]: ItemConfigCardType.TAROT_REVERSE, // 72
  [Card.REVERSE_STARS]: ItemConfigCardType.TAROT_REVERSE, // 73
  [Card.REVERSE_MOON]: ItemConfigCardType.TAROT_REVERSE, // 74
  [Card.REVERSE_SUN]: ItemConfigCardType.TAROT_REVERSE, // 75
  [Card.REVERSE_JUDGEMENT]: ItemConfigCardType.TAROT_REVERSE, // 76
  [Card.REVERSE_WORLD]: ItemConfigCardType.TAROT_REVERSE, // 77
  [Card.CRACKED_KEY]: ItemConfigCardType.SPECIAL_OBJECT, // 78
  [Card.QUEEN_OF_HEARTS]: ItemConfigCardType.SUIT, // 79
  [Card.WILD]: ItemConfigCardType.SPECIAL, // 80
  [Card.SOUL_ISAAC]: ItemConfigCardType.RUNE, // 81
  [Card.SOUL_MAGDALENE]: ItemConfigCardType.RUNE, // 82
  [Card.SOUL_CAIN]: ItemConfigCardType.RUNE, // 83
  [Card.SOUL_JUDAS]: ItemConfigCardType.RUNE, // 84
  [Card.SOUL_BLUE_BABY]: ItemConfigCardType.RUNE, // 85
  [Card.SOUL_EVE]: ItemConfigCardType.RUNE, // 86
  [Card.SOUL_SAMSON]: ItemConfigCardType.RUNE, // 87
  [Card.SOUL_AZAZEL]: ItemConfigCardType.RUNE, // 88
  [Card.SOUL_LAZARUS]: ItemConfigCardType.RUNE, // 89
  [Card.SOUL_EDEN]: ItemConfigCardType.RUNE, // 90
  [Card.SOUL_LOST]: ItemConfigCardType.RUNE, // 91
  [Card.SOUL_LILITH]: ItemConfigCardType.RUNE, // 92
  [Card.SOUL_KEEPER]: ItemConfigCardType.RUNE, // 93
  [Card.SOUL_APOLLYON]: ItemConfigCardType.RUNE, // 94
  [Card.SOUL_FORGOTTEN]: ItemConfigCardType.RUNE, // 95
  [Card.SOUL_BETHANY]: ItemConfigCardType.RUNE, // 96
  [Card.SOUL_JACOB]: ItemConfigCardType.RUNE, // 97
};
