import { PillEffectType } from "../types/PillEffectType";

export const DEFAULT_PILL_EFFECT_TYPE = PillEffectType.MODDED;

export const PILL_EFFECT_TYPES: {
  readonly [key in PillEffect]: PillEffectType;
} = {
  [PillEffect.PILLEFFECT_NULL]: PillEffectType.NULL,
  [PillEffect.PILLEFFECT_BAD_GAS]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_BAD_TRIP]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_BALLS_OF_STEEL]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_BOMBS_ARE_KEYS]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_EXPLOSIVE_DIARRHEA]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_FULL_HEALTH]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_HEALTH_DOWN]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_HEALTH_UP]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_I_FOUND_PILLS]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_PUBERTY]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_PRETTY_FLY]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_RANGE_DOWN]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_RANGE_UP]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_SPEED_DOWN]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_SPEED_UP]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_TEARS_DOWN]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_TEARS_UP]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_LUCK_DOWN]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_LUCK_UP]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_TELEPILLS]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_48HOUR_ENERGY]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_HEMATEMESIS]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_PARALYSIS]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_SEE_FOREVER]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_PHEROMONES]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_AMNESIA]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_LEMON_PARTY]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_WIZARD]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_PERCS]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_ADDICTED]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_RELAX]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_QUESTIONMARK]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_LARGER]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_SMALLER]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_INFESTED_EXCLAMATION]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_INFESTED_QUESTION]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_POWER]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_RETRO_VISION]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_FRIENDS_TILL_THE_END]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_X_LAX]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_SOMETHINGS_WRONG]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_IM_DROWSY]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_IM_EXCITED]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_GULP]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_HORF]: PillEffectType.NEUTRAL,
  [PillEffect.PILLEFFECT_SUNSHINE]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_VURP]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_SHOT_SPEED_DOWN]: PillEffectType.NEGATIVE,
  [PillEffect.PILLEFFECT_SHOT_SPEED_UP]: PillEffectType.POSITIVE,
  [PillEffect.PILLEFFECT_EXPERIMENTAL]: PillEffectType.NEUTRAL,
  [PillEffect.NUM_PILL_EFFECTS]: PillEffectType.MODDED,
};
