/* eslint-disable isaacscript/limit-slash-slash-comments */

// THIS CODE WAS AUTOMATICALLY GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
// YOU CAN REGENERATE IT USING:
// npm run generate:configs

export const recommended = {
  plugins: ["isaacscript"],
  rules: {
    eqeqeq: "off",
    "no-template-curly-in-string": "off",
    "no-useless-return": "off",
    "isaacscript/eqeqeq-fix": "error",
    "isaacscript/limit-jsdoc-comments": "error",
    "isaacscript/limit-slash-slash-comments": "error",
    "isaacscript/no-implicit-map-set-loops": "error",
    "isaacscript/no-let-any": "error",
    "isaacscript/no-object-any": "error",
    "isaacscript/no-template-curly-in-string-fix": "error",
    "isaacscript/no-useless-return-no-fix": "error",
    "isaacscript/no-void-return-type": "error",
  },
};
