declare enum EntityGridCollisionClass {
  GRIDCOLL_NONE = 0,
  GRIDCOLL_WALLS_X = 1,
  GRIDCOLL_WALLS_Y = 2,
  GRIDCOLL_WALLS = 3,
  GRIDCOLL_BULLET = 4,
  GRIDCOLL_GROUND = 5,
  GRIDCOLL_NOPITS = 6,
  GRIDCOLL_PITSONLY = 7,
}
