declare enum GridRooms {
  NO_ROOM_IDX = -99999,

  ROOM_DEVIL_IDX = -1,
  ROOM_ERROR_IDX = -2,
  ROOM_DEBUG_IDX = -3,
  ROOM_DUNGEON_IDX = -4,
  ROOM_BOSSRUSH_IDX = -5,
  ROOM_BLACK_MARKET_IDX = -6,
  ROOM_MEGA_SATAN_IDX = -7,
  ROOM_BLUE_WOOM_IDX = -8,
  ROOM_THE_VOID_IDX = -9,
  ROOM_SECRET_EXIT_IDX = -10,
  ROOM_GIDEON_DUNGEON_IDX = -11,
  ROOM_GENESIS_IDX = -12,
  ROOM_SECRET_SHOP_IDX = -13,
  ROOM_ROTGUT_DUNGEON1_IDX = -14,
  ROOM_ROTGUT_DUNGEON2_IDX = -15,
  ROOM_BLUE_ROOM_IDX = -16,
  ROOM_EXTRA_BOSS_IDX = -17,
  ROOM_ANGEL_SHOP_IDX = -18,

  NUM_OFF_GRID_ROOMS = 18,

  MAX_GRID_ROOMS = 507,
  MAX_ROOMS = 525,

  ROOM_MIRROR_IDX = -100,
  ROOM_MINESHAFT_IDX = -101,
}
