declare enum PoopSpellType {
  SPELL_NONE = 0,
  SPELL_POOP = 1,
  SPELL_CORNY = 2,
  SPELL_BURNING = 3,
  SPELL_STONE = 4,
  SPELL_STINKY = 5,
  SPELL_BLACK = 6,
  SPELL_HOLY = 7,
  SPELL_LIQUID = 8,
  SPELL_FART = 9,
  SPELL_BOMB = 10,
  SPELL_DIARRHEA = 11,

  NUM_POOP_SPELLS = 12,
  SPELL_BAG_SIZE = 20,
  SPELL_QUEUE_SIZE = 6,
}
