declare enum WeaponType {
  WEAPON_TEARS = 1,
  WEAPON_BRIMSTONE = 2,
  WEAPON_LASER = 3,
  WEAPON_KNIFE = 4,
  WEAPON_BOMBS = 5,
  WEAPON_ROCKETS = 6,
  WEAPON_MONSTROS_LUNGS = 7,
  WEAPON_LUDOVICO_TECHNIQUE = 8,
  WEAPON_TECH_X = 9,
  WEAPON_BONE = 10,
  WEAPON_NOTCHED_AXE = 11,
  WEAPON_URN_OF_SOULS = 12,
  WEAPON_SPIRIT_SWORD = 13,
  WEAPON_FETUS = 14,
  WEAPON_UMBILICAL_WHIP = 15,

  NUM_WEAPON_TYPES = 16,
}
