/**
 * From: https://www.w3schools.com/js/js_reserved.asp
 *
 * - Some words that would not typically start a line are manually removed.
 * - `console` is added.
 */
export const JAVASCRIPT_RESERVED_WORDS_SET: ReadonlySet<string> = new Set([
  "abstract",
  // "arguments",
  "await",
  // "boolean",
  "break",
  // "byte",
  "case",
  "catch",
  // "char",
  "class",
  "console", // Manually added.
  "const",
  "continue",
  "debugger",
  // "default", "delete",
  "do",
  // "double",
  "else",
  "enum",
  // "eval",
  "export",
  // "extends", "false", "final",
  "finally",
  // - "float",
  "for",
  "function",
  "goto",
  "if",
  // "implements",
  "import",
  // "in", "instanceof" "int",
  "interface",
  "let",
  // "long", "native",
  "new",
  // "null", "package",
  "private",
  "protected",
  "public",
  "return",
  // "short",
  "static",
  "super",
  "switch",
  // "synchronized", "this",
  "throw",
  // "throws", "transient", "true",
  "try",
  // "typeof", "var", "void", "volatile",
  "while",
  // "with",
  "yield",
]);
