/// THIS FILE IS AUTOMATICALLY GENERATED BY THE "generate.ts" SCRIPT.
/// DO NOT EDIT THIS FILE! YOU CAN REGENERATE IT WITH:
/// npm run generate

import { completeSentencesJSDoc } from "./rules/complete-sentences-jsdoc.js";
import { completeSentencesLineComments } from "./rules/complete-sentences-line-comments.js";
import { consistentEnumValues } from "./rules/consistent-enum-values.js";
import { consistentNamedTuples } from "./rules/consistent-named-tuples.js";
import { enumMemberNumberSeparation } from "./rules/enum-member-number-separation.js";
import { eqeqeqFix } from "./rules/eqeqeq-fix.js";
import { formatJSDocComments } from "./rules/format-jsdoc-comments.js";
import { formatLineComments } from "./rules/format-line-comments.js";
import { jsdocCodeBlockLanguage } from "./rules/jsdoc-code-block-language.js";
import { newlineBetweenSwitchCase } from "./rules/newline-between-switch-case.js";
import { noConfusingSetMethods } from "./rules/no-confusing-set-methods.js";
import { noEmptyJSDoc } from "./rules/no-empty-jsdoc.js";
import { noEmptyLineComments } from "./rules/no-empty-line-comments.js";
import { noExplicitArrayLoops } from "./rules/no-explicit-array-loops.js";
import { noExplicitMapSetLoops } from "./rules/no-explicit-map-set-loops.js";
import { noForIn } from "./rules/no-for-in.js";
import { noInvalidDefaultMap } from "./rules/no-invalid-default-map.js";
import { noLetAny } from "./rules/no-let-any.js";
import { noMutableReturn } from "./rules/no-mutable-return.js";
import { noNumberEnums } from "./rules/no-number-enums.js";
import { noObjectAny } from "./rules/no-object-any.js";
import { noObjectMethodsWithMapSet } from "./rules/no-object-methods-with-map-set.js";
import { noStringLength0 } from "./rules/no-string-length-0.js";
import { noTemplateCurlyInStringFix } from "./rules/no-template-curly-in-string-fix.js";
import { noThrow } from "./rules/no-throw.js";
import { noUndefinedReturnType } from "./rules/no-undefined-return-type.js";
import { noUnnecessaryAssignment } from "./rules/no-unnecessary-assignment.js";
import { noUnsafePlusplus } from "./rules/no-unsafe-plusplus.js";
import { noVoidReturnType } from "./rules/no-void-return-type.js";
import { preferPlusplus } from "./rules/prefer-plusplus.js";
import { preferPostfixPlusplus } from "./rules/prefer-postfix-plusplus.js";
import { preferReadonlyParameterTypes } from "./rules/prefer-readonly-parameter-types.js";
import { requireBreak } from "./rules/require-break.js";
import { requireCapitalConstAssertions } from "./rules/require-capital-const-assertions.js";
import { requireCapitalReadOnly } from "./rules/require-capital-read-only.js";
import { requireUnannotatedConstAssertions } from "./rules/require-unannotated-const-assertions.js";
import { requireVRegistration } from "./rules/require-v-registration.js";
import { requireVariadicFunctionArgument } from "./rules/require-variadic-function-argument.js";
import { strictArrayMethods } from "./rules/strict-array-methods.js";
import { strictEnums } from "./rules/strict-enums.js";
import { strictUndefinedFunctions } from "./rules/strict-undefined-functions.js";
import { strictVoidFunctions } from "./rules/strict-void-functions.js";

export const rules = {
  "complete-sentences-jsdoc": completeSentencesJSDoc,
  "complete-sentences-line-comments": completeSentencesLineComments,
  "consistent-enum-values": consistentEnumValues,
  "consistent-named-tuples": consistentNamedTuples,
  "enum-member-number-separation": enumMemberNumberSeparation,
  "eqeqeq-fix": eqeqeqFix,
  "format-jsdoc-comments": formatJSDocComments,
  "format-line-comments": formatLineComments,
  "jsdoc-code-block-language": jsdocCodeBlockLanguage,
  "newline-between-switch-case": newlineBetweenSwitchCase,
  "no-confusing-set-methods": noConfusingSetMethods,
  "no-empty-jsdoc": noEmptyJSDoc,
  "no-empty-line-comments": noEmptyLineComments,
  "no-explicit-array-loops": noExplicitArrayLoops,
  "no-explicit-map-set-loops": noExplicitMapSetLoops,
  "no-for-in": noForIn,
  "no-invalid-default-map": noInvalidDefaultMap,
  "no-let-any": noLetAny,
  "no-mutable-return": noMutableReturn,
  "no-number-enums": noNumberEnums,
  "no-object-any": noObjectAny,
  "no-object-methods-with-map-set": noObjectMethodsWithMapSet,
  "no-string-length-0": noStringLength0,
  "no-template-curly-in-string-fix": noTemplateCurlyInStringFix,
  "no-throw": noThrow,
  "no-undefined-return-type": noUndefinedReturnType,
  "no-unnecessary-assignment": noUnnecessaryAssignment,
  "no-unsafe-plusplus": noUnsafePlusplus,
  "no-void-return-type": noVoidReturnType,
  "prefer-plusplus": preferPlusplus,
  "prefer-postfix-plusplus": preferPostfixPlusplus,
  "prefer-readonly-parameter-types": preferReadonlyParameterTypes,
  "require-break": requireBreak,
  "require-capital-const-assertions": requireCapitalConstAssertions,
  "require-capital-read-only": requireCapitalReadOnly,
  "require-unannotated-const-assertions": requireUnannotatedConstAssertions,
  "require-v-registration": requireVRegistration,
  "require-variadic-function-argument": requireVariadicFunctionArgument,
  "strict-array-methods": strictArrayMethods,
  "strict-enums": strictEnums,
  "strict-undefined-functions": strictUndefinedFunctions,
  "strict-void-functions": strictVoidFunctions,
};
