/// THIS FILE IS AUTOMATICALLY GENERATED BY THE "generate.mts" SCRIPT.
/// DO NOT EDIT THIS FILE! YOU CAN REGENERATE IT WITH:
/// npm run generate

import { completeSentencesJSDoc } from "./rules/complete-sentences-jsdoc";
import { completeSentencesLineComments } from "./rules/complete-sentences-line-comments";
import { consistentEnumValues } from "./rules/consistent-enum-values";
import { enumMemberNumberSeparation } from "./rules/enum-member-number-separation";
import { eqeqeqFix } from "./rules/eqeqeq-fix";
import { formatJSDocComments } from "./rules/format-jsdoc-comments";
import { formatLineComments } from "./rules/format-line-comments";
import { jsdocCodeBlockLanguage } from "./rules/jsdoc-code-block-language";
import { newlineBetweenSwitchCase } from "./rules/newline-between-switch-case";
import { noConfusingSetMethods } from "./rules/no-confusing-set-methods";
import { noEmptyJSDoc } from "./rules/no-empty-jsdoc";
import { noEmptyLineComments } from "./rules/no-empty-line-comments";
import { noExplicitArrayLoops } from "./rules/no-explicit-array-loops";
import { noExplicitMapSetLoops } from "./rules/no-explicit-map-set-loops";
import { noForIn } from "./rules/no-for-in";
import { noInvalidDefaultMap } from "./rules/no-invalid-default-map";
import { noLetAny } from "./rules/no-let-any";
import { noMutableReturn } from "./rules/no-mutable-return";
import { noNumberEnums } from "./rules/no-number-enums";
import { noObjectAny } from "./rules/no-object-any";
import { noObjectMethodsWithMapSet } from "./rules/no-object-methods-with-map-set";
import { noStringLength0 } from "./rules/no-string-length-0";
import { noTemplateCurlyInStringFix } from "./rules/no-template-curly-in-string-fix";
import { noThrow } from "./rules/no-throw";
import { noUnsafePlusplus } from "./rules/no-unsafe-plusplus";
import { noVoidReturnType } from "./rules/no-void-return-type";
import { preferPlusplus } from "./rules/prefer-plusplus";
import { preferPostfixPlusplus } from "./rules/prefer-postfix-plusplus";
import { preferReadonlyParameterTypes } from "./rules/prefer-readonly-parameter-types";
import { requireBreak } from "./rules/require-break";
import { requireCapitalConstAssertions } from "./rules/require-capital-const-assertions";
import { requireCapitalReadOnly } from "./rules/require-capital-read-only";
import { requireUnannotatedConstAssertions } from "./rules/require-unannotated-const-assertions";
import { requireVRegistration } from "./rules/require-v-registration";
import { requireVariadicFunctionArgument } from "./rules/require-variadic-function-argument";
import { strictArrayMethods } from "./rules/strict-array-methods";
import { strictEnums } from "./rules/strict-enums";
import { strictUndefinedFunctions } from "./rules/strict-undefined-functions";
import { strictVoidFunctions } from "./rules/strict-void-functions";

export const rules = {
  "complete-sentences-jsdoc": completeSentencesJSDoc,
  "complete-sentences-line-comments": completeSentencesLineComments,
  "consistent-enum-values": consistentEnumValues,
  "enum-member-number-separation": enumMemberNumberSeparation,
  "eqeqeq-fix": eqeqeqFix,
  "format-jsdoc-comments": formatJSDocComments,
  "format-line-comments": formatLineComments,
  "jsdoc-code-block-language": jsdocCodeBlockLanguage,
  "newline-between-switch-case": newlineBetweenSwitchCase,
  "no-confusing-set-methods": noConfusingSetMethods,
  "no-empty-jsdoc": noEmptyJSDoc,
  "no-empty-line-comments": noEmptyLineComments,
  "no-explicit-array-loops": noExplicitArrayLoops,
  "no-explicit-map-set-loops": noExplicitMapSetLoops,
  "no-for-in": noForIn,
  "no-invalid-default-map": noInvalidDefaultMap,
  "no-let-any": noLetAny,
  "no-mutable-return": noMutableReturn,
  "no-number-enums": noNumberEnums,
  "no-object-any": noObjectAny,
  "no-object-methods-with-map-set": noObjectMethodsWithMapSet,
  "no-string-length-0": noStringLength0,
  "no-template-curly-in-string-fix": noTemplateCurlyInStringFix,
  "no-throw": noThrow,
  "no-unsafe-plusplus": noUnsafePlusplus,
  "no-void-return-type": noVoidReturnType,
  "prefer-plusplus": preferPlusplus,
  "prefer-postfix-plusplus": preferPostfixPlusplus,
  "prefer-readonly-parameter-types": preferReadonlyParameterTypes,
  "require-break": requireBreak,
  "require-capital-const-assertions": requireCapitalConstAssertions,
  "require-capital-read-only": requireCapitalReadOnly,
  "require-unannotated-const-assertions": requireUnannotatedConstAssertions,
  "require-v-registration": requireVRegistration,
  "require-variadic-function-argument": requireVariadicFunctionArgument,
  "strict-array-methods": strictArrayMethods,
  "strict-enums": strictEnums,
  "strict-undefined-functions": strictUndefinedFunctions,
  "strict-void-functions": strictVoidFunctions,
};
