/// THIS FILE IS AUTOMATICALLY GENERATED BY THE "build.ts" SCRIPT.
/// IT IS COPIED FROM THE "isaacscript-common" package.
/// DO NOT EDIT THIS FILE!

/**
 * The standard library has the feature to deploy a new room on-the-fly with the `deployJSONRoom`
 * helper function. It requires a `JSONRoomsFile` as an argument, which is simply an XML file
 * converted to JSON. (You can create XML room files using the Basement Renovator program.)
 *
 * You can convert your XML files using the following command:
 *
 * ```sh
 * npx convert-xml-to-json foo.xml foo.json
 * ```
 *
 * Note that the custom stages feature of the standard library uses real XML/STB files, not JSON
 * rooms, so you would only need to do this if you are using the `deployJSONRoom` command
 * specifically.
 */
export interface JSONRoomsFile {
  readonly rooms: JSONRooms;
}

/** Part of `JSONRoomsFile`. */
export interface JSONRooms {
  readonly room: readonly JSONRoom[];
}

/** Part of `JSONRoomsFile`. */
export interface JSONRoom {
  readonly $: {
    /** Needs to be converted to an `int`. */
    readonly difficulty: string;

    /** Needs to be converted to an `int`. */
    readonly height: string;

    readonly name: string;

    /** Needs to be converted to an `int`. */
    readonly shape: string;

    /** Needs to be converted to an `int`. */
    readonly subtype: string;

    /** Needs to be converted to an `int`. */
    readonly type: string;

    /** Needs to be converted to an `int`. */
    readonly variant: string;

    /** Needs to be converted to a `float`. */
    readonly weight: string;

    /** Needs to be converted to an `int`. */
    readonly width: string;
  };

  readonly door: readonly JSONDoor[];
  readonly spawn: readonly JSONSpawn[];
}

/** Part of `JSONRoomsFile`. */
export interface JSONDoor {
  readonly $: {
    /** Equal to "True" or "False". Needs to be converted to an `boolean`. */
    readonly exists: string;

    /** Needs to be converted to an `int`. */
    readonly x: string;

    /** Needs to be converted to an `int`. */
    readonly y: string;
  };
}

/** Part of `JSONRoomsFile`. */
export interface JSONSpawn {
  readonly $: {
    /** Needs to be converted to an `int`. */
    readonly x: string;

    /** Needs to be converted to an `int`. */
    readonly y: string;
  };

  readonly entity: readonly JSONEntity[];
}

/** Part of `JSONRoomsFile`. */
export interface JSONEntity {
  readonly $: {
    /** Needs to be converted to an `int`. */
    readonly type: string;

    /** Needs to be converted to an `int`. */
    readonly variant: string;

    /** Needs to be converted to an `int`. */
    readonly subtype: string;

    /** Needs to be converted to a `float`. */
    readonly weight: string;
  };
}
