#!/bin/bash

set -e # Exit on any errors

# Get the directory of this script
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$DIR"

OUT_DIR="$DIR/../../dist/packages/docs"

rm -rf "$DIR/docs/api" # Generated by the TypeDoc plugin
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
npm run build

# Change the automatically generated titles of some pages.
#sed --in-place 's/types="packages\/isaac-typescript-definitions\/src\/types"/path="types\/index.d.ts"/' "$OUT_DIR/isaacscript-common/index.d.ts"
