import { customReviveCallbacksInit } from "./callbacks/customRevive";
import { itemPickupCallbacksInit } from "./callbacks/itemPickup";
import { postAmbushCallbacksInit } from "./callbacks/postAmbush";
import { postBombExplodedInit } from "./callbacks/postBombExploded";
import { postBombInitLateInit } from "./callbacks/postBombInitLate";
import { postBoneSwingInit } from "./callbacks/postBoneSwing";
import { postCollectibleEmptyInit } from "./callbacks/postCollectibleEmpty";
import { postCollectibleInitFirstInit } from "./callbacks/postCollectibleInitFirst";
import { postCursedTeleportInit } from "./callbacks/postCursedTeleport";
import { postCustomDoorEnterInit } from "./callbacks/postCustomDoorEnter";
import { postDiceRoomActivatedInit } from "./callbacks/postDiceRoomActivated";
import { postDoorRenderInit } from "./callbacks/postDoorRender";
import { postDoorUpdateInit } from "./callbacks/postDoorUpdate";
import { postEffectInitLateInit } from "./callbacks/postEffectInitLate";
import { postEffectStateChangedInit } from "./callbacks/postEffectStateChanged";
import { postEsauJrCallbacksInit } from "./callbacks/postEsauJr";
import { postFamiliarInitLateInit } from "./callbacks/postFamiliarInitLate";
import { postFamiliarStateChangedInit } from "./callbacks/postFamiliarStateChanged";
import { postFlipCallbacksInit } from "./callbacks/postFlip";
import { postGreedModeWaveInit } from "./callbacks/postGreedModeWave";
import { postGridEntityCallbacksInit } from "./callbacks/postGridEntity";
import { postGridEntityCollisionInit } from "./callbacks/postGridEntityCollision";
import { postGridEntityRenderInit } from "./callbacks/postGridEntityRender";
import { postHolyMantleRemovedInit } from "./callbacks/postHolyMantleRemoved";
import { postItemDischargeInit } from "./callbacks/postItemDischarged";
import { postKnifeInitLateInit } from "./callbacks/postKnifeInitLate";
import { postLaserInitLateInit } from "./callbacks/postLaserInitLate";
import { postNPCInitLateInit } from "./callbacks/postNPCInitLate";
import { postNPCStateChangedInit } from "./callbacks/postNPCStateChanged";
import { postPickupCollectInit } from "./callbacks/postPickupCollect";
import { postPickupInitFirstInit } from "./callbacks/postPickupInitFirst";
import { postPickupInitLateInit } from "./callbacks/postPickupInitLate";
import { postPickupStateChangedInit } from "./callbacks/postPickupStateChanged";
import { postPitRenderInit } from "./callbacks/postPitRender";
import { postPitUpdateInit } from "./callbacks/postPitUpdate";
import { postPlayerChangeHealthInit } from "./callbacks/postPlayerChangeHealth";
import { postPlayerChangeTypeInit } from "./callbacks/postPlayerChangeType";
import { postPlayerCollectibleCallbacksInit } from "./callbacks/postPlayerCollectible";
import { postPlayerFatalDamageInit } from "./callbacks/postPlayerFatalDamage";
import { postPlayerInitLateInit } from "./callbacks/postPlayerInitLate";
import { postPlayerReorderedCallbacksInit } from "./callbacks/postPlayerReordered";
import { postPoopRenderInit } from "./callbacks/postPoopRender";
import { postPoopUpdateInit } from "./callbacks/postPoopUpdate";
import { postPressurePlateRenderInit } from "./callbacks/postPressurePlateRender";
import { postPressurePlateUpdateInit } from "./callbacks/postPressurePlateUpdate";
import { postProjectileInitLateInit } from "./callbacks/postProjectileInitLate";
import { postPurchaseInit } from "./callbacks/postPurchase";
import { postRockRenderInit } from "./callbacks/postRockRender";
import { postRockUpdateInit } from "./callbacks/postRockUpdate";
import { postRoomClearChangedInit } from "./callbacks/postRoomClearChanged";
import { postSacrificeInit } from "./callbacks/postSacrifice";
import { postSlotDestroyedInit } from "./callbacks/postSlotDestroyed";
import { postSlotInitUpdateCallbacksInit } from "./callbacks/postSlotInitUpdate";
import { postSlotRenderCallbacksInit } from "./callbacks/postSlotRender";
import { postSpikesRenderInit } from "./callbacks/postSpikesRender";
import { postSpikesUpdateInit } from "./callbacks/postSpikesUpdate";
import { postTearInitLateInit } from "./callbacks/postTearInitLate";
import { postTearInitVeryLateInit } from "./callbacks/postTearInitVeryLate";
import { postTNTRenderInit } from "./callbacks/postTNTRender";
import { postTNTUpdateInit } from "./callbacks/postTNTUpdate";
import { postTransformationInit } from "./callbacks/postTransformation";
import { postTrinketBreakInit } from "./callbacks/postTrinketBreak";
import { preBerserkDeathInit } from "./callbacks/preBerserkDeath";
import { preNewLevelInit } from "./callbacks/preNewLevel";
import { reorderedCallbacksInit } from "./callbacks/reorderedCallbacks";
import { ModUpgraded } from "./classes/ModUpgraded";

export function initCustomCallbacks(mod: ModUpgraded): void {
  customReviveCallbacksInit(mod);
  itemPickupCallbacksInit(mod);
  postAmbushCallbacksInit(mod);
  postBombExplodedInit(mod);
  postBombInitLateInit(mod);
  postBoneSwingInit(mod);
  postCollectibleEmptyInit(mod);
  postCollectibleInitFirstInit(mod);
  postCursedTeleportInit(mod);
  postCustomDoorEnterInit();
  postDiceRoomActivatedInit(mod);
  postDoorRenderInit(mod);
  postDoorUpdateInit(mod);
  postEffectInitLateInit(mod);
  postEffectStateChangedInit(mod);
  postEsauJrCallbacksInit(mod);
  postFamiliarInitLateInit(mod);
  postFamiliarStateChangedInit(mod);
  postFlipCallbacksInit(mod);
  postGreedModeWaveInit(mod);
  postGridEntityCallbacksInit(mod);
  postGridEntityCollisionInit(mod);
  postGridEntityRenderInit(mod);
  postHolyMantleRemovedInit(mod);
  postItemDischargeInit(mod);
  postLaserInitLateInit(mod);
  postKnifeInitLateInit(mod);
  postNPCInitLateInit(mod);
  postNPCStateChangedInit(mod);
  postPickupCollectInit(mod);
  postPickupInitFirstInit(mod);
  postPickupInitLateInit(mod);
  postPickupStateChangedInit(mod);
  postPitRenderInit(mod);
  postPitUpdateInit(mod);
  postPlayerChangeHealthInit(mod);
  postPlayerChangeTypeInit(mod);
  postPlayerCollectibleCallbacksInit(mod);
  postPlayerFatalDamageInit(mod);
  postPlayerInitLateInit(mod);
  postPlayerReorderedCallbacksInit(mod);
  postPoopRenderInit(mod);
  postPoopUpdateInit(mod);
  postPressurePlateRenderInit(mod);
  postPressurePlateUpdateInit(mod);
  postProjectileInitLateInit(mod);
  postPurchaseInit(mod);
  postRockRenderInit(mod);
  postRockUpdateInit(mod);
  postRoomClearChangedInit(mod);
  postSacrificeInit(mod);
  postSlotDestroyedInit(mod);
  postSlotInitUpdateCallbacksInit(mod);
  postSlotRenderCallbacksInit(mod);
  postSpikesRenderInit(mod);
  postSpikesUpdateInit(mod);
  postTearInitLateInit(mod);
  postTearInitVeryLateInit(mod);
  postTNTRenderInit(mod);
  postTNTUpdateInit(mod);
  postTransformationInit(mod);
  postTrinketBreakInit(mod);
  preBerserkDeathInit(mod);
  preNewLevelInit(mod);
  reorderedCallbacksInit(mod);
}
