import { ReadonlySet } from "../types/ReadonlySet";

/**
 * The set of vanilla console commands, as documented here:
 * https://bindingofisaacrebirth.fandom.com/wiki/Debug_Console
 */
export const CONSOLE_COMMANDS_SET = new ReadonlySet<string>([
  // Listed commands
  "achievement",
  "challenge",
  "clear",
  "clearcache",
  "clearseeds",
  "combo",
  "copy",
  "costumetest",
  "curse",
  "cutscene",
  "debug",
  "delirious",
  "eggs",
  "g",
  "giveitem",
  "goto",
  "gridspawn",
  "l",
  "listcollectibles",
  "lua",
  "luamem",
  "luamod",
  "luarun",
  "m",
  "macro",
  "metro",
  "playsfx",
  "prof",
  "profstop",
  "r",
  "reloadfx",
  "reloadshaders",
  "remove",
  "repeat",
  "reseed",
  "restart",
  "seed",
  "spawn",
  "stage",
  "time",

  // Unlisted commands
  "addplayer",
  "forceroom",
  "giveitem2",
  "g2",
  "netdelay",
  "netstart",
  "remove2",
  "r2",
  "reloadwisps",
  "restock",
  "rewind",
  "testbosspool",
]);
