export enum RepentogonCompletionMarkType {
  MOMS_HEART = 0,
  ISAAC = 1,
  SATAN = 2,
  BOSS_RUSH = 3,
  BLUE_BABY = 4,
  LAMB = 5,
  MEGA_SATAN = 6,
  ULTRA_GREED = 7,
  HUSH = 9,
  ULTRA_GREEDIER = 11,
  DELIRIUM = 12,
  MOTHER = 13,
  BEAST = 14,
}

export enum RepentogonGiantbookType {
  NECRONOMICON = 1,
  MONSTER_MANUAL = 2,
  WHORE_OF_BABYLON = 3,
  DEAD_SEA_SCROLLS = 4,
  THE_SUN = 5,
  ETERNAL_HEART_SOUL = 6,
  MOMS_BRA = 7,
  MOMS_PAD = 8,
  ANARCHIST_COOKBOOK = 9,
  BIBLE = 10,
  BOOK_OF_REVELATIONS = 11,
  DEATH = 12,
  ETERNAL_HEART = 13,
  HOURGLASS = 14,
  SATANIC_BIBLE = 15,
  BLACK_HEART = 16,
  D4 = 17,
  D10 = 18,
  FLUSH = 19,
  HAGALAZ = 20,
  JERA = 21,
  EHWAZ = 22,
  DAGAZ = 23,
  ANSUZ = 24,
  PERTHRO = 25,
  BERKANO = 26,
  ALGIZ = 27,
  D100 = 28,
  RAINBOW_POOP = 29,
  MISSING_PAGE = 30,
  MISSING_PAGE_2 = 31,
  SPIDER_BUTT = 32,
  SLEEP = 33,
  BOOK_OF_BELIAL = 34,
  BETRAYAL = 35,
  D8 = 36,
  D12 = 37,
  SUPER_BUM = 38,
  CLICKER = 39,
  MAMA_MEGA = 40,
  ETERNAL_HEART_EMPTY = 41,
  REVERSE_EMPRESS = 42,
  REVERSE_SUN = 43,
  DOGMA = 44,
  ETERNAL_HEART_BLACK = 46,
}

/** Represents the type of health corresponding to a player. */
export enum RepentogonHealthType {
  RED = 0,
  SOUL = 1,
  NO_HEALTH = 2,
  COIN = 3,
  BONE = 4,
}
