export enum BackdropType {
  BASEMENT = 1,
  CELLAR = 2,
  BURNING_BASEMENT = 3,
  CAVES = 4,
  CATACOMBS = 5,
  FLOODED_CAVES = 6,
  DEPTHS = 7,
  NECROPOLIS = 8,
  DANK_DEPTHS = 9,
  WOMB = 10,
  UTERO = 11,
  SCARRED_WOMB = 12,
  BLUE_WOMB = 13,
  SHEOL = 14,
  CATHEDRAL = 15,
  DARK_ROOM = 16,
  CHEST = 17,
  MEGA_SATAN = 18,
  LIBRARY = 19,
  SHOP = 20,
  CLEAN_BEDROOM = 21,
  DIRTY_BEDROOM = 22,
  SECRET = 23,
  DICE = 24,
  ARCADE = 25,
  ERROR_ROOM = 26,
  BLUE_WOMB_PASS = 27,
  GREED_SHOP = 28,
  DUNGEON = 29,
  SACRIFICE = 30,
  DOWNPOUR = 31,
  MINES = 32,
  MAUSOLEUM = 33,
  CORPSE = 34,
  PLANETARIUM = 35,
  DOWNPOUR_ENTRANCE = 36,
  MINES_ENTRANCE = 37,
  MAUSOLEUM_ENTRANCE = 38,
  CORPSE_ENTRANCE = 39,
  MAUSOLEUM_2 = 40,
  MAUSOLEUM_3 = 41,
  MAUSOLEUM_4 = 42,
  CORPSE_2 = 43,
  CORPSE_3 = 44,
  DROSS = 45,
  ASHPIT = 46,
  GEHENNA = 47,
  MORTIS = 48,

  /** This corresponds to Isaac's bedroom on the Home floor, not a clean bedroom. */
  ISAACS_BEDROOM = 49,

  HALLWAY = 50,
  MOMS_BEDROOM = 51,

  /** The closet on the right side of the Home floor. */
  CLOSET = 52,

  /** The secret closet on the left side of the Home floor. */
  CLOSET_B = 53,

  DOGMA = 54,
  DUNGEON_GIDEON = 55,
  DUNGEON_ROTGUT = 56,
  DUNGEON_BEAST = 57,
  MINES_SHAFT = 58,
  ASHPIT_SHAFT = 59,
  DARK_CLOSET = 60,
  DEATHMATCH = 61,
  LIL_PORTAL = 62,
}
