export enum LevelStage {
  NULL = 0,
  BASEMENT_1 = 1,
  BASEMENT_2 = 2,
  CAVES_1 = 3,
  CAVES_2 = 4,
  DEPTHS_1 = 5,
  DEPTHS_2 = 6,
  WOMB_1 = 7,
  WOMB_2 = 8,
  BLUE_WOMB = 9,
  SHEOL_CATHEDRAL = 10,
  DARK_ROOM_CHEST = 11,
  THE_VOID = 12,
  HOME = 13,
}
