import {
  AngelVariant,
  BabyLongLegsVariant,
  BabyVariant,
  BeastVariant,
  BegottenVariant,
  BigBonyVariant,
  BigHornVariant,
  BloodPuppyVariant,
  BoilVariant,
  BonyVariant,
  BoomFlyVariant,
  Charger2Variant,
  ChargerSubType,
  ChargerVariant,
  ChimeraVariant,
  ChubVariant,
  ClottyVariant,
  ClutchVariant,
  ConjoinedFattyVariant,
  ConstantStoneShooterSubType,
  ConstantStoneShooterVariant,
  CrazyLongLegsVariant,
  CultistVariant,
  DaddyLongLegsVariant,
  DannyVariant,
  DarkEsauVariant,
  DeathsHeadVariant,
  DeathVariant,
  DingleVariant,
  DipVariant,
  DogmaVariant,
  DopleVariant,
  DukeVariant,
  DumpVariant,
  EntityType,
  EnvyVariant,
  EvisVariant,
  ExorcistVariant,
  EyeVariant,
  FacelessVariant,
  FallenVariant,
  FattyVariant,
  FistulaVariant,
  FlyBombVariant,
  Gaper2Variant,
  GaperVariant,
  GeminiVariant,
  GlobinVariant,
  GluttonyVariant,
  GoatVariant,
  GrimaceVariant,
  GrubVariant,
  GurgleVariant,
  GurglingVariant,
  GusherVariant,
  GutsVariant,
  GuttyFattyVariant,
  GyroVariant,
  HauntVariant,
  HiveVariant,
  HomunculusVariant,
  HopperVariant,
  HostVariant,
  IsaacVariant,
  KnightVariant,
  LambVariant,
  LarryJrVariant,
  LeaperVariant,
  LeechVariant,
  LeperVariant,
  LittleHornVariant,
  LokiVariant,
  LustVariant,
  MamaGurdyVariant,
  MaskVariant,
  MawVariant,
  MegaSatanVariant,
  MemBrainVariant,
  MoleVariant,
  MomsHeartVariant,
  MomVariant,
  Monstro2Variant,
  MotherSubType,
  MotherVariant,
  MoveableTNTVariant,
  MrMawVariant,
  MrMineVariant,
  MulliganVariant,
  NeedleVariant,
  NerveEndingVariant,
  ParaBiteVariant,
  PeeperFattyVariant,
  PeepVariant,
  PinVariant,
  PitfallVariant,
  PokyVariant,
  PoltyVariant,
  PolycephalusVariant,
  PooterVariant,
  PortalVariant,
  PreyVariant,
  PrideVariant,
  RageCreepVariant,
  RaglichVariant,
  RaglingVariant,
  RagManVariant,
  RagMegaVariant,
  RevenantVariant,
  RockSpiderVariant,
  RotgutVariant,
  RoundWormVariant,
  SatanVariant,
  ScourgeVariant,
  SingeVariant,
  SirenVariant,
  SkinnyVariant,
  SlothVariant,
  SpittyVariant,
  SquirtVariant,
  StoneyVariant,
  SubHorfVariant,
  SuckerVariant,
  SwingerVariant,
  TumorVariant,
  UltraCoinVariant,
  UltraGreedVariant,
  VisageVariant,
  VisFattyVariant,
  VisVariant,
  WalkingBoilVariant,
  WallCreepVariant,
  WarVariant,
  WhipperVariant,
  WidowVariant,
  WrathVariant,
} from "isaac-typescript-definitions";
import {
  BloatSubType,
  BrownieSubType,
  CageSubType,
  CarrionQueenSubType,
  ChubSubType,
  DeathSubType,
  DingleSubType,
  DukeOfFliesSubType,
  FamineSubType,
  FistulaSubType,
  ForsakenSubType,
  FrailSubType,
  GateSubType,
  GeminiSubType,
  GurdyJrSubType,
  GurdySubType,
  GurglingSubType,
  HauntSubType,
  HollowSubType,
  HuskSubType,
  LarryJrSubType,
  LittleHornSubType,
  MegaFattySubType,
  MegaMawSubType,
  MomSubType,
  Monstro2SubType,
  MonstroSubType,
  PeepSubType,
  PestilenceSubType,
  PinSubType,
  PolycephalusSubType,
  RagManSubType,
  StainSubType,
  WarSubType,
  WidowSubType,
} from "./collections/subTypes";

/** An enum of EntityIDs which correlate to an NPC. */
// Excluded: Shopkeeper 17, Fireplace 33
export const NPCID = {
  FROWNING_GAPER: `${EntityType.GAPER}.${GaperVariant.FROWNING_GAPER}.0`,
  GAPER: `${EntityType.GAPER}.${GaperVariant.GAPER}.0`,
  FLAMING_GAPER: `${EntityType.GAPER}.${GaperVariant.FLAMING_GAPER}.0`,
  ROTTEN_GAPER: `${EntityType.GAPER}.${GaperVariant.ROTTEN_GAPER}.0`,
  GUSHER: `${EntityType.GUSHER}.${GusherVariant.GUSHER}.0`,
  PACER: `${EntityType.GAPER}.${GusherVariant.PACER}.0`,
  HORF: `${EntityType.HORF}.${SubHorfVariant.SUB_HORF}.0`,
  TAINTED_HORF: `${EntityType.HORF}.${SubHorfVariant.TAINTED_SUB_HORF}.0`,
  FLY: `${EntityType.FLY}.0.0`,
  POOTER: `${EntityType.POOTER}.${PooterVariant.POOTER}.0`,
  SUPER_POOTER: `${EntityType.POOTER}.${PooterVariant.SUPER_POOTER}.0`,
  TAINTED_POOTER: `${EntityType.POOTER}.${PooterVariant.TAINTED_POOTER}.0`,
  BLOB: `${EntityType.CLOTTY}.${ClottyVariant.BLOB}.0`,
  CLOT: `${EntityType.CLOTTY}.${ClottyVariant.CLOT}.0`,
  CLOTTY: `${EntityType.CLOTTY}.${ClottyVariant.CLOTTY}.0`,
  GRILLED_CLOTTY: `${EntityType.CLOTTY}.${ClottyVariant.GRILLED_CLOTTY}.0`,
  MULLIBOOM: `${EntityType.MULLIGAN}.${MulliganVariant.MULLIBOOM}.0`,
  MULLIGAN: `${EntityType.MULLIGAN}.${MulliganVariant.MULLIGAN}.0`,
  MULLIGOON: `${EntityType.MULLIGAN}.${MulliganVariant.MULLIGOON}.0`,
  ATTACK_FLY: `${EntityType.ATTACK_FLY}.0.0`,
  MAGGOT: `${EntityType.MAGGOT}.0.0`,
  DROWNED_HIVE: `${EntityType.HIVE}.${HiveVariant.DROWNED_HIVE}.0`,
  HIVE: `${EntityType.HIVE}.${HiveVariant.HIVE}.0`,
  HOLY_MULLIGAN: `${EntityType.HIVE}.${HiveVariant.HOLY_MULLIGAN}.0`,
  TAINTED_MULLIGAN: `${EntityType.HIVE}.${HiveVariant.TAINTED_MULLIGAN}.0`,
  CARRION_PRINCESS: `${EntityType.CHARGER}.${ChargerVariant.CARRION_PRINCESS}.0`,
  CHARGER: `${EntityType.CHARGER}.${ChargerVariant.CHARGER}.${ChargerSubType.CHARGER}`,
  MY_SHADOW_CHARGER: `${EntityType.CHARGER}.${ChargerVariant.CHARGER}.${ChargerSubType.MY_SHADOW}`,
  DANK_CHARGER: `${EntityType.CHARGER}.${ChargerVariant.DANK_CHARGER}.0`,
  DROWNED_CHARGER: `${EntityType.CHARGER}.${ChargerVariant.DROWNED_CHARGER}.0`,
  CURSED_GLOBIN: `${EntityType.GLOBIN}.${GlobinVariant.CURSED_GLOBIN}.0`,
  DANK_GLOBIN: `${EntityType.GLOBIN}.${GlobinVariant.DANK_GLOBIN}.0`,
  GAZING_GLOBIN: `${EntityType.GLOBIN}.${GlobinVariant.GAZING_GLOBIN}.0`,
  GLOBIN: `${EntityType.GLOBIN}.${GlobinVariant.GLOBIN}.0`,
  BONE_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.BONE_FLY}.0`,
  BOOM_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.BOOM_FLY}.0`,
  DRAGON_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.DRAGON_FLY}.0`,
  DROWNED_BOOM_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.DROWNED_BOOM_FLY}.0`,
  RED_BOOM_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.RED_BOOM_FLY}.0`,
  STICK_BOOM_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.SICK_BOOM_FLY}.0`,
  TAINTED_BOOM_FLY: `${EntityType.BOOM_FLY}.${BoomFlyVariant.TAINTED_BOOM_FLY}.0`,
  MAW: `${EntityType.MAW}.${MawVariant.MAW}.0`,
  PSYCHIC_MAW: `${EntityType.MAW}.${MawVariant.PSYCHIC_MAW}.0`,
  RED_MAW: `${EntityType.MAW}.${MawVariant.RED_MAW}.0`,
  HARD_HOST: `${EntityType.HOST}.${HostVariant.HARD_HOST}.0`,
  HOST: `${EntityType.HOST}.${HostVariant.HOST}.0`,
  RED_HOST: `${EntityType.HOST}.${HostVariant.RED_HOST}.0`,
  MOBILE_HOST: `${EntityType.MOBILE_HOST}.0.0`,
  FLESH_MOBILE_HOST: `${EntityType.FLESH_MOBILE_HOST}.0.0`,
  FLOAST: `${EntityType.FLOATING_HOST}.0.0`,
  EGGY: `${EntityType.HOPPER}.${HopperVariant.EGGY}.0`,
  HOPPER: `${EntityType.HOPPER}.${HopperVariant.HOPPER}.0`,
  FLAMING_HOPPER: `${EntityType.FLAMING_HOPPER}.0.0`,
  TAINTED_HOPPER: `${EntityType.HOPPER}.${HopperVariant.TAINTED_HOPPER}.0`,
  TRITE: `${EntityType.HOPPER}.${HopperVariant.TRITE}.0`,
  BOIL: `${EntityType.BOIL}.${BoilVariant.BOIL}.0`,
  GUT: `${EntityType.BOIL}.${BoilVariant.GUT}.0`,
  SACK: `${EntityType.BOIL}.${BoilVariant.SACK}.0`,
  SPITTY: `${EntityType.SPITTY}.${SpittyVariant.SPITTY}.0`,
  TAINTED_SPITTY: `${EntityType.SPITTY}.${SpittyVariant.TAINTED_SPITTY}.0`,
  BRAIN: `${EntityType.BRAIN}.0.0`,
  LEAPER: `${EntityType.LEAPER}.${LeaperVariant.LEAPER}.0`,
  STICKY_LEAPER: `${EntityType.LEAPER}.${LeaperVariant.STICKY_LEAPER}.0`,
  MR_MAW: `${EntityType.MR_MAW}.${MrMawVariant.MR_MAW}.0`,
  MR_MAW_HEAD: `${EntityType.MR_MAW}.${MrMawVariant.MR_MAW_HEAD}.0`,
  MR_MAW_NECK: `${EntityType.MR_MAW}.${MrMawVariant.MR_MAW_NECK}.0`,
  MR_RED_MAW: `${EntityType.MR_MAW}.${MrMawVariant.MR_RED_MAW}.0`,
  MR_RED_MAW_HEAD: `${EntityType.MR_MAW}.${MrMawVariant.MR_RED_MAW_HEAD}.0`,
  BABY: `${EntityType.BABY}.${BabyVariant.BABY}.0`,
  ANGELIC_BABY: `${EntityType.BABY}.${BabyVariant.ANGELIC_BABY}.0`,
  ULTRA_PRIDE_BABY: `${EntityType.BABY}.${BabyVariant.ULTRA_PRIDE_BABY}.0`,
  WRINKLY_BABY: `${EntityType.BABY}.${BabyVariant.WRINKLY_BABY}.0`,
  CHUBBER: `${EntityType.VIS}.${VisVariant.CHUBBER}.0`,
  CHUBBER_PROJECTILE: `${EntityType.VIS}.${VisVariant.CHUBBER_PROJECTILE}.0`, // ????
  DOUBLE_VIS: `${EntityType.VIS}.${VisVariant.DOUBLE_VIS}.0`,
  SCARRED_DOUBLE_VIS: `${EntityType.VIS}.${VisVariant.SCARRED_DOUBLE_VIS}.0`,
  VIS: `${EntityType.VIS}.${VisVariant.VIS}.0`,
  GUTS: `${EntityType.GUTS}.${GutsVariant.GUTS}.0`,
  SCARRED_GUTS: `${EntityType.GUTS}.${GutsVariant.SCARRED_GUTS}.0`,
  SLOG: `${EntityType.GUTS}.${GutsVariant.SLOG}.0`,
  BLACK_KNIGHT: `${EntityType.KNIGHT}.${KnightVariant.BLACK_KNIGHT}.0`,
  BRAINLESS_KNIGHT: `${EntityType.KNIGHT}.${KnightVariant.BRAINLESS_KNIGHT}.0`,
  KNIGHT: `${EntityType.KNIGHT}.${KnightVariant.KNIGHT}.0`,
  LOOSE_KNIGHT: `${EntityType.KNIGHT}.${KnightVariant.LOOSE_KNIGHT}.0`,
  SELFLESS_KNIGHT: `${EntityType.KNIGHT}.${KnightVariant.SELFLESS_KNIGHT}.0`,
  GURGLE: `${EntityType.GURGLE}.${GurgleVariant.GURGLE}.0`,
  CRACKLE: `${EntityType.GURGLE}.${GurgleVariant.CRACKLE}.0`,
  NULLS: `${EntityType.NULLS}.0.0`,
  GUSH: `${EntityType.GUSH}.0.0`,
  CYCLOPIA: `${EntityType.CYCLOPIA}.0.0`,
  BLUE_GAPER: `${EntityType.HUSH_GAPER}.0.0`,
  GREED_GAPER: `${EntityType.GREED_GAPER}.0.0`,
  POISON_MIND: `${EntityType.POISON_MIND}.0.0`,
  WRAITH: `${EntityType.WRAITH}.0.0`,
  FRED: `${EntityType.FRED}.0.0`,
  DEEP_GAPER: `${EntityType.DEEP_GAPER}.0.0`,
  BLURB: `${EntityType.BLURB}.0.0`,
  LEVEL_2_GAPER: `${EntityType.GAPER_L2}.${Gaper2Variant.GAPER}.0`,
  LEVEL_2_HORF: `${EntityType.GAPER_L2}.${Gaper2Variant.HORF}.0`,
  LEVEL_2_GUSHER: `${EntityType.GAPER_L2}.${Gaper2Variant.GUSHER}.0`,
  PARA_BITE: `${EntityType.PARA_BITE}.${ParaBiteVariant.PARA_BITE}.0`,
  SCARRED_PARA_BITE: `${EntityType.PARA_BITE}.${ParaBiteVariant.SCARRED_PARA_BITE}.0`,
  TWITCHY: `${EntityType.TWITCHY}.0.0`,
  DEAD_ISAAC: `${EntityType.ISAAC}.20.0`,
  FACELESS: `${EntityType.FACELESS}.${FacelessVariant.FACELESS}.0`,
  TAINTED_FACELESS: `${EntityType.FACELESS}.${FacelessVariant.TAINTED_FACELESS}.0`,
  EXORCIST: `${EntityType.EXORCIST}.${ExorcistVariant.EXORCIST}.0`,
  FANATIC: `${EntityType.EXORCIST}.${ExorcistVariant.FANATIC}.0`,
  CANDLER: `${EntityType.CANDLER}.0.0`,
  DUMP: `${EntityType.DUMP}.${DumpVariant.DUMP}.0`,
  DUMP_HEAD: `${EntityType.DUMP}.${DumpVariant.DUMP_HEAD}.0`,
  SPLASHER: `${EntityType.SPLASHER}.0.0`,
  BLACK_GLOBIN_BODY: `${EntityType.BLACK_GLOBIN}.0.0`,
  PSYCHIC_HORF: `${EntityType.PSY_HORF}.0.0`,
  SUB_HORF: `${EntityType.SUB_HORF}.${SubHorfVariant.SUB_HORF}.0`,
  TAINTED_SUB_HORF: `${EntityType.SUB_HORF}.${SubHorfVariant.TAINTED_SUB_HORF}.0`,
  NECRO: `${EntityType.NECRO}.0.0`,
  MOTER: `${EntityType.MOTER}.0.0`,
  ETERNAL_FLY: `${EntityType.ETERNAL_FLY}.0.0`,
  RING_FLY: `${EntityType.RING_OF_FLIES}.0.0`,
  DART_FLY: `${EntityType.DART_FLY}.0.0`,
  SWARM: `${EntityType.SWARM}.0.0`,
  BONE_KNIGHT: `${EntityType.BONE_KNIGHT}.0.0`,
  MEGA_CLOTTY: `${EntityType.MEGA_CLOTTY}.0.0`,
  HUSH_FLY: `${EntityType.HUSH_FLY}.0.0`,
  MOVABLE_TNT: `${EntityType.MOVABLE_TNT}.${MoveableTNTVariant.MOVEABLE_TNT}.0`,
  MOVABLE_TNT_MINECRAFTER: `${EntityType.MOVABLE_TNT}.${MoveableTNTVariant.MINE_CRAFTER}.0`,
  WILLO: `${EntityType.WILLO}.0.0`,
  ARMY_FLY: `${EntityType.ARMY_FLY}.0.0`,
  FLY_BOMB: `${EntityType.FLY_BOMB}.${FlyBombVariant.FLY_BOMB}.0`,
  ETERNAL_FLY_BOMB: `${EntityType.FLY_BOMB}.${FlyBombVariant.ETERNAL_FLY_BOMB}.0`,
  SOUL_SUCKER: `${EntityType.SUCKER}.${SuckerVariant.SOUL_SUCKER}.0`,
  SUCKER: `${EntityType.SUCKER}.${SuckerVariant.SUCKER}.0`,
  MAMA_FLY: `${EntityType.SUCKER}.${SuckerVariant.MAMA_FLY}.0`,
  BULB: `${EntityType.SUCKER}.${SuckerVariant.BULB}.0`,
  BLOOD_FLY: `${EntityType.SUCKER}.${SuckerVariant.BLOOD_FLY}.0`,
  TAINTED_SUCKER: `${EntityType.SUCKER}.${SuckerVariant.TAINTED_SUCKER}.0`,
  SPIT: `${EntityType.SUCKER}.${SuckerVariant.SPIT}.0`,
  INK: `${EntityType.SUCKER}.${SuckerVariant.INK}.0`,
  CLOGGY: `${EntityType.CLOGGY}.0.0`,
  NEST: `${EntityType.NEST}.0.0`,
  LEPER: `${EntityType.LEPER}.${LeperVariant.LEPER}.0`,
  LEPER_FLESH: `${EntityType.LEPER}.${LeperVariant.LEPER_FLESH}.0`,
  MR_MINE: `${EntityType.MR_MINE}.${MrMineVariant.MR_MINE}.0`,
  MR_MINE_NECK: `${EntityType.MR_MINE}.${MrMineVariant.MR_MINE_NECK}.0`,
  PREY: `${EntityType.PREY}.${PreyVariant.PREY}.0`,
  MULLIGHOUL: `${EntityType.PREY}.${PreyVariant.MULLIGHOUL}.0`,
  MUSHROOM: `${EntityType.MUSHROOM}.0.0`,
  BOUNCER: `${EntityType.BOUNCER}.0.0`,
  GAS_DWARF: `${EntityType.GAS_DWARF}.0.0`,
  DANNY: `${EntityType.DANNY}.${DannyVariant.DANNY}.0`,
  COAL_BOY: `${EntityType.DANNY}.${DannyVariant.COAL_BOY}.0`,
  GYRO: `${EntityType.GYRO}.${GyroVariant.GYRO}.0`,
  GRILLED_GYRO: `${EntityType.GYRO}.${GyroVariant.GRILLED_GYRO}.0`,
  BLASTER: `${EntityType.BLASTER}.0.0`,
  LEECH: `${EntityType.LEECH}.${LeechVariant.LEECH}.0`,
  HOLY_LEECH: `${EntityType.LEECH}.${LeechVariant.HOLY_LEECH}.0`,
  KAMIKAZE_LEECH: `${EntityType.LEECH}.${LeechVariant.KAMIKAZE_LEECH}.0`,
  SMALL_LEECH: `${EntityType.SMALL_LEECH}.0.0`,
  SMALL_MAGGOT: `${EntityType.SMALL_MAGGOT}.0.0`,
  ADULT_LEECH: `${EntityType.ADULT_LEECH}.0.0`,
  LEVEL_2_CHARGER: `${EntityType.CHARGER_L2}.${Charger2Variant.CHARGER}.0`,
  GASBAG: `${EntityType.GASBAG}.0.0`,
  COHORT: `${EntityType.COHORT}.0.0`,
  UNBORN: `${EntityType.UNBORN}.0.0`,
  PUSTULE: `${EntityType.PUSTULE}.0.0`,
  ELLEECH: `${EntityType.CHARGER_L2}.${Charger2Variant.ELLEECH}.0`,
  BLOOD_PUPPY_SMALL: `${EntityType.BLOOD_PUPPY}.${BloodPuppyVariant.SMALL}.0`,
  BLOOD_PUPPY_LARGE: `${EntityType.BLOOD_PUPPY}.${BloodPuppyVariant.LARGE}.0`,
  CONJOINED_SPITTY: `${EntityType.CONJOINED_SPITTY}.0.0`,
  BLACK_GLOBIN: `${EntityType.BLACK_GLOBIN}.0.0`,
  FAT_BAT: `${EntityType.FAT_BAT}.0.0`,
  BABY_LONG_LEGS: `${EntityType.BABY_LONG_LEGS}.${BabyLongLegsVariant.BABY_LONG_LEGS}.0`,
  SMALL_BABY_LONG_LEGS: `${EntityType.BABY_LONG_LEGS}.${BabyLongLegsVariant.SMALL_BABY_LONG_LEGS}.0`,
  CRAZY_LONG_LEGS: `${EntityType.CRAZY_LONG_LEGS}.${CrazyLongLegsVariant.CRAZY_LONG_LEGS}.0`,
  SMALL_CRAZY_LONG_LEGS: `${EntityType.CRAZY_LONG_LEGS}.${CrazyLongLegsVariant.SMALL_CRAZY_LONG_LEGS}.0`,
  SWARM_FLY: `${EntityType.SWARM}.0.0`,
  IMP: `${EntityType.IMP}.0.0`,
  HUSH_BOIL: `${EntityType.HUSH_BOIL}.0.0`,
  MEMBRAIN: `${EntityType.MEMBRAIN}.${MemBrainVariant.MEMBRAIN}.0`,
  DEAD_MEAT: `${EntityType.MEMBRAIN}.${MemBrainVariant.DEAD_MEAT}.0`,
  MAMA_GUTS: `${EntityType.MEMBRAIN}.${MemBrainVariant.MAMA_GUTS}.0`,
  BUBBLES: `${EntityType.BUBBLES}.0.0`,
  RAGLING: `${EntityType.RAGLING}.${RaglingVariant.RAGLING}.0`,
  RAG_MAN_RAGLING: `${EntityType.RAGLING}.${RaglingVariant.RAG_MANS_RAGLING}.0`,
  FAT_SACK: `${EntityType.FAT_SACK}.0.0`,
  BLUBBER: `${EntityType.BLUBBER}.0.0`,
  HALF_SACK: `${EntityType.HALF_SACK}.0.0`,
  CONJOINED_FATTY: `${EntityType.CONJOINED_FATTY}.${ConjoinedFattyVariant.CONJOINED_FATTY}.0`,
  BLUE_CONJOINED_FATTY: `${EntityType.CONJOINED_FATTY}.${ConjoinedFattyVariant.BLUE_CONJOINED_FATTY}.0`,
  SWINGER: `${EntityType.SWINGER}.${SwingerVariant.SWINGER}.0`,
  SWINGER_HEAD: `${EntityType.SWINGER}.${SwingerVariant.SWINGER_HEAD}.0`,
  SWINGER_NECK: `${EntityType.SWINGER}.${SwingerVariant.SWINGER_NECK}.0`,
  EYE: `${EntityType.EYE}.${EyeVariant.EYE}.0`,
  BLOODSHOT_EYE: `${EntityType.EYE}.${EyeVariant.BLOODSHOT_EYE}.0`,
  HOLY_EYE: `${EntityType.EYE}.${EyeVariant.HOLY_EYE}.0`,
  EMBRYO: `${EntityType.EMBRYO}.0.0`,
  SPIDER: `${EntityType.SPIDER}.0.0`,
  BIG_SPIDER: `${EntityType.BIG_SPIDER}.0.0`,
  STRIDER: `${EntityType.STRIDER}.0.0`,
  ROCK_SPIDER: `${EntityType.ROCK_SPIDER}.${RockSpiderVariant.ROCK_SPIDER}.0`,
  TINTED_ROCK_SPIDER: `${EntityType.ROCK_SPIDER}.${RockSpiderVariant.TINTED_ROCK_SPIDER}.0`,
  COAL_SPIDER: `${EntityType.ROCK_SPIDER}.${RockSpiderVariant.COAL_SPIDER}.0`,
  SWARM_SPIDER: `${EntityType.SWARM_SPIDER}.0.0`,
  KEEPER: `${EntityType.KEEPER}.0.0`,
  BUTTLICKER: `${EntityType.BUTTLICKER}.0.0`,
  BUTT_SLICKER: `${EntityType.BUTT_SLICKER}.0.0`,
  HANGER: `${EntityType.HANGER}.0.0`,
  SWARMER: `${EntityType.SWARMER}.0.0`,
  MASK: `${EntityType.MASK}.${MaskVariant.MASK}.0`,
  MASK_2: `${EntityType.MASK}.${MaskVariant.MASK_2}.0`,
  FATTY: `${EntityType.FATTY}.${FattyVariant.FATTY}.0`,
  PALE_FATTY: `${EntityType.FATTY}.${FattyVariant.PALE_FATTY}.0`,
  NERVE_ENDING: `${EntityType.NERVE_ENDING}.${NerveEndingVariant.NERVE_ENDING}.0`,
  NERVE_ENDING_2: `${EntityType.NERVE_ENDING}.${NerveEndingVariant.NERVE_ENDING_2}.0`,
  WALL_HUGGER: `${EntityType.WALL_HUGGER}.0.0`,
  WALKING_BOIL: `${EntityType.WALKING_BOIL}.${WalkingBoilVariant.WALKING_BOIL}.0`,
  WALKING_GUT: `${EntityType.WALKING_BOIL}.${WalkingBoilVariant.WALKING_GUT}.0`,
  WALKING_SACK: `${EntityType.WALKING_BOIL}.${WalkingBoilVariant.WALKING_SACK}.0`,
  FLAMING_FATTY: `${EntityType.FATTY}.${FattyVariant.FLAMING_FATTY}.0`,
  STONEY: `${EntityType.STONEY}.${StoneyVariant.STONEY}.0`,
  CROSS_STONEY: `${EntityType.STONEY}.${StoneyVariant.STONEY}.0`,
  BLISTER: `${EntityType.BLISTER}.0.0`,
  QUAKEY: `${EntityType.QUAKEY}.0.0`,
  BIG_BONY: `${EntityType.BIG_BONY}.${BigBonyVariant.BIG_BONE}.0`,
  BIG_BONE: `${EntityType.BIG_BONY}.${BigBonyVariant.BIG_BONE}.0`,
  GUTTED_FATTY: `${EntityType.GUTTED_FATTY}.${GuttyFattyVariant.GUTTED_FATTY}.0`,
  GUTTED_FATTY_EYE: `${EntityType.GUTTED_FATTY}.${GuttyFattyVariant.GUTTY_FATTY_EYE}.0`,
  FESTERING_GUTS: `${EntityType.GUTTED_FATTY}.${GuttyFattyVariant.FESTERING_GUTS}.0`,
  PEEPING_FATTY: `${EntityType.PEEPER_FATTY}.${PeeperFattyVariant.PEEPING_FATTY}.0`,
  PEEPING_FATTY_EYE: `${EntityType.PEEPER_FATTY}.${PeeperFattyVariant.PEEPING_FATTY_EYE}.0`,
  BLOATY: `${EntityType.BLOATY}.0.0`,
  VIS_VERSA: `${EntityType.VIS_VERSA}.0.0`,
  EVIS: `${EntityType.EVIS}.${EvisVariant.EVIS}.0`,
  EVIS_GUTS: `${EntityType.EVIS}.${EvisVariant.EVIS_GUTS}.0`,
  WHIPPER: `${EntityType.WHIPPER}.${WhipperVariant.WHIPPER}.0`,
  SNAPPER: `${EntityType.WHIPPER}.${WhipperVariant.SNAPPER}.0`,
  FLAGELLANT: `${EntityType.WHIPPER}.${WhipperVariant.FLAGELLANT}.0`,
  VIS_FATTY: `${EntityType.VIS_FATTY}.${VisFattyVariant.VIS_FATTY}.0`,
  FETAL_DEMON: `${EntityType.VIS_FATTY}.${VisFattyVariant.FETAL_DEMON}.0`,
  SHADY: `${EntityType.SHADY}.0.0`,
  CLICKETY_CLACK: `${EntityType.CLICKETY_CLACK}.0.0`,
  DEATHS_HEAD: `${EntityType.DEATHS_HEAD}.${DeathsHeadVariant.DEATHS_HEAD}.0`,
  DANK_DEATHS_HEAD: `${EntityType.DEATHS_HEAD}.${DeathsHeadVariant.DANK_DEATHS_HEAD}.0`,
  CURSED_DEATHS_HEAD: `${EntityType.DEATHS_HEAD}.${DeathsHeadVariant.CURSED_DEATHS_HEAD}.0`,
  BRIMSTONE_DEATHS_HEAD: `${EntityType.DEATHS_HEAD}.${DeathsHeadVariant.BRIMSTONE_DEATHS_HEAD}.0`,
  RED_SKULL: `${EntityType.DEATHS_HEAD}.${DeathsHeadVariant.RED_SKULL}.0`,
  FLESH_DEATHS_HEAD: `${EntityType.FLESH_DEATHS_HEAD}.0.0`,
  DUSTY_DEATHS_HEAD: `${EntityType.DUSTY_DEATHS_HEAD}.0.0`,
  MOMS_HAND: `${EntityType.MOMS_HAND}.0.0`,
  MOMS_DEAD_HAND: `${EntityType.MOMS_DEAD_HAND}.0.0`,
  LEVEL_2_FLY: `${EntityType.FLY_L2}.0.0`,
  FULL_FLY: `${EntityType.FULL_FLY}.0.0`,
  PON: `${EntityType.PON}.0.0`,
  LEVEL_2_WILLO: `${EntityType.WILLO_L2}.0.0`,
  LEVEL_2_SPIDER: `${EntityType.SPIDER_L2}.0.0`,
  TICKING_SPIDER: `${EntityType.TICKING_SPIDER}.0.0`,
  MIGRAINE: `${EntityType.MIGRAINE}.0.0`,
  DIP: `${EntityType.DIP}.${DipVariant.DIP}.0`,
  CORN: `${EntityType.DIP}.${DipVariant.CORN}.0`,
  BROWNIE_CORN: `${EntityType.DIP}.${DipVariant.BROWNIE_CORN}0.0`,
  BIG_CORN: `${EntityType.DIP}.${DipVariant.BIG_CORN}.0`,
  DRIP: `${EntityType.DRIP}.0.0`,
  WIZOOB: `${EntityType.WIZOOB}.0.0`,
  RED_GHOST: `${EntityType.RED_GHOST}.0.0`,
  LUMP: `${EntityType.LUMP}.0.0`,
  SQUIRT: `${EntityType.SQUIRT}.${SquirtVariant.SQUIRT}.0`,
  DANK_SQUIRT: `${EntityType.SQUIRT}.${SquirtVariant.DANK_SQUIRT}.0`,
  HARDY: `${EntityType.HARDY}.0.0`,
  SPLURT: `${EntityType.SPLURT}.0.0`,
  COD_WORM: `${EntityType.COD_WORM}.0.0`,
  OOB: `${EntityType.OOB}.0.0`,
  BLACK_MAW: `${EntityType.BLACK_MAW}.0.0`,
  SKINNY: `${EntityType.SKINNY}.${SkinnyVariant.SKINNY}.0`,
  ROTTY: `${EntityType.SKINNY}.${SkinnyVariant.ROTTY}.0`,
  CRISPY: `${EntityType.SKINNY}.${SkinnyVariant.CRISPY}.0`,
  BONY: `${EntityType.BONY}.${BonyVariant.BONY}.0`,
  HOLY_BONY: `${EntityType.BONY}.${BonyVariant.HOLY_BONY}.0`,
  BLACK_BONY: `${EntityType.BLACK_BONY}.0.0`,
  REVENANT: `${EntityType.REVENANT}.${RevenantVariant.REVENANT}.0`,
  QUAD_REVENANT: `${EntityType.REVENANT}.${RevenantVariant.QUAD_REVENANT}.0`,
  MAZE_ROAMER: `${EntityType.MAZE_ROAMER}.0.0`,
  HOMUNCULUS: `${EntityType.HOMUNCULUS}.${HomunculusVariant.HOMUNCULUS}.0`,
  HOMUNCULUS_CORD: `${EntityType.HOMUNCULUS}.${HomunculusVariant.HOMUNCULUS_CORD}.0`,
  BEGOTTEN: `${EntityType.BEGOTTEN}.${BegottenVariant.BEGOTTEN}.0`,
  BEGOTTEN_CHAIN: `${EntityType.BEGOTTEN}.${BegottenVariant.BEGOTTEN_CHAIN}.0`,
  TUMOR: `${EntityType.TUMOR}.${TumorVariant.TUMOR}.0`,
  PLANETOID: `${EntityType.TUMOR}.${TumorVariant.PLANETOID}.0`,
  CAMILLO_JR: `${EntityType.CAMILLO_JR}.0.0`,
  PSY_TUMOR: `${EntityType.PSY_TUMOR}.0.0`,
  POOFER: `${EntityType.POOFER}.0.0`,
  BISHOP: `${EntityType.BISHOP}.0.0`,
  ONE_TOOTH: `${EntityType.ONE_TOOTH}.0.0`,
  GOAT: `${EntityType.GOAT}.${GoatVariant.GOAT}.0`,
  BLACK_GOAT: `${EntityType.GOAT}.${GoatVariant.BLACK_GOAT}.0`,
  CULTIST: `${EntityType.CULTIST}.${CultistVariant.CULTIST}.0`,
  BLOOD_CULTIST: `${EntityType.CULTIST}.${CultistVariant.BLOOD_CULTIST}.0`,
  BONE_TRAP: `${EntityType.CULTIST}.${CultistVariant.BONE_TRAP}.0`,
  GRUB: `${EntityType.GRUB}.${GrubVariant.GRUB}.0`,
  CARRION_RIDER: `${EntityType.GRUB}.${GrubVariant.CARRION_RIDER}.0`,
  CORPSE_EATER: `${EntityType.GRUB}.${GrubVariant.CORPSE_EATER}.0`,
  WALL_CREEP: `${EntityType.WALL_CREEP}.${WallCreepVariant.WALL_CREEP}.0`,
  RAG_CREEP: `${EntityType.WALL_CREEP}.${WallCreepVariant.RAG_CREEP}.0`,
  SOY_CREEP: `${EntityType.WALL_CREEP}.${WallCreepVariant.SOY_CREEP}.0`,
  TAINTED_SOY_CREEP: `${EntityType.WALL_CREEP}.${WallCreepVariant.TAINTED_SOY_CREEP}.0`,
  RAGE_CREEP: `${EntityType.RAGE_CREEP}.${RageCreepVariant.RAGE_CREEP}.0`,
  RAGE_CREEP_SPLIT: `${EntityType.RAGE_CREEP}.${RageCreepVariant.SPLIT_RAGE_CREEP}.0`,
  BLIND_CREEP: `${EntityType.BLIND_CREEP}.0.0`,
  THE_THING: `${EntityType.THE_THING}.0.0`,
  ROUND_WORM: `${EntityType.ROUND_WORM}.${RoundWormVariant.ROUND_WORM}.0`,
  TUBE_WORM: `${EntityType.ROUND_WORM}.${RoundWormVariant.TUBE_WORM}.0`,
  TAINTED_ROUND_WORM: `${EntityType.ROUND_WORM}.${RoundWormVariant.TAINTED_ROUND_WORM}.0`,
  TAINTED_TUBE_WORM: `${EntityType.ROUND_WORM}.${RoundWormVariant.TAINTED_TUBE_WORM}.0`,
  NIGHT_CRAWLER: `${EntityType.NIGHT_CRAWLER}.0.0`,
  FLOATING_KNIGHT: `${EntityType.FLOATING_KNIGHT}.0.0`,
  ROUNDY: `${EntityType.ROUNDY}.0.0`,
  ULCER: `${EntityType.ULCER}.0.0`,
  FIRE_WORM: `${EntityType.FIRE_WORM}.0.0`,
  MOLE: `${EntityType.MOLE}.${MoleVariant.MOLE}.0`,
  TAINTED_MOLE: `${EntityType.MOLE}.${MoleVariant.TAINTED_MOLE}.0`,
  LIL_HAUNT: `${EntityType.THE_HAUNT}.${HauntVariant.LIL_HAUNT}.0`,
  POLTY: `${EntityType.POLTY}.${PoltyVariant.POLTY}.0`,
  KINETI: `${EntityType.POLTY}.${PoltyVariant.KINETI}.0`,
  DUST: `${EntityType.DUST}.0.0`,
  DUKIE: `${EntityType.DUKIE}.0.0`,
  BABY_BEGOTTEN: `${EntityType.BABY_BEGOTTEN}.0.0`,
  MEATBALL: `${EntityType.MEATBALL}.0.0`,
  MINISTRO: `${EntityType.MINISTRO}.0.0`,
  FISTULOID: `${EntityType.FISTULOID}.0.0`,
  FLY_TRAP: `${EntityType.FLY_TRAP}.0.0`,
  POOT_MINE: `${EntityType.POOT_MINE}.0.0`,
  BOMBGAGGER: `${EntityType.BOMBGAGGER}.0.0`,
  FLESH_MAIDEN: `${EntityType.FLESH_MAIDEN}.0.0`,
  MORNINGSTAR: `${EntityType.MORNINGSTAR}.0.0`,
  NEEDLE: `${EntityType.NEEDLE}.${NeedleVariant.NEEDLE}.0`,
  PASTY: `${EntityType.NEEDLE}.${NeedleVariant.PASTY}.0`,
  FISSURE: `${EntityType.FISSURE}.0.0`,
  TAR_BOY: `${EntityType.TAR_BOY}.0.0`,
  PORTAL: `${EntityType.PORTAL}.${PortalVariant.PORTAL}.0`,
  LIL_PORTAL: `${EntityType.PORTAL}.${PortalVariant.LIL_PORTAL}.0`,
  HENRY: `${EntityType.HENRY}.0.0`,
  DOPLE: `${EntityType.DOPLE}.${DopleVariant.DOPLE}.0`,
  EVIL_TWIN: `${EntityType.DOPLE}.${DopleVariant.EVIL_TWIN}.0`,
  STONE_GRIMACE: `${EntityType.GRIMACE}.${GrimaceVariant.STONE_GRIMACE}.0`,
  VOMIT_GRIMACE: `${EntityType.GRIMACE}.${GrimaceVariant.VOMIT_GRIMACE}.0`,
  TRIPLE_GRIMACE: `${EntityType.GRIMACE}.${GrimaceVariant.TRIPLE_GRIMACE}.0`,
  STONE_EYE: `${EntityType.STONE_EYE}.0.0`,
  CROSS_STONE_SHOOTER_ALWAYS_ON_DOWN: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CROSS_STONE_SHOOTER_ALWAYS_ON}.${ConstantStoneShooterSubType.DOWN}`,
  CROSS_STONE_SHOOTER_ALWAYS_ON_LEFT: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CROSS_STONE_SHOOTER_ALWAYS_ON}.${ConstantStoneShooterSubType.LEFT}`,
  CROSS_STONE_SHOOTER_ALWAYS_ON_RIGHT: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CROSS_STONE_SHOOTER_ALWAYS_ON}.${ConstantStoneShooterSubType.RIGHT}`,
  CROSS_STONE_SHOOTER_ALWAYS_ON_UP: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CROSS_STONE_SHOOTER_ALWAYS_ON}.${ConstantStoneShooterSubType.UP}`,
  CROSS_STONE_SHOOTER_DOWN: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CROSS_STONE_SHOOTER}.${ConstantStoneShooterSubType.DOWN}`,
  CROSS_STONE_SHOOTER_LEFT: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CROSS_STONE_SHOOTER}.${ConstantStoneShooterSubType.LEFT}`,
  CROSS_STONE_SHOOTER_RIGHT: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CROSS_STONE_SHOOTER}.${ConstantStoneShooterSubType.RIGHT}`,
  CROSS_STONE_SHOOTER_UP: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CROSS_STONE_SHOOTER}.${ConstantStoneShooterSubType.UP}`,
  CONSTANT_STONE_SHOOTER_UP: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterSubType.UP}`,
  CONSTANT_STONE_SHOOTER_DOWN: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterSubType.DOWN}`,
  CONSTANT_STONE_SHOOTER_LEFT: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterSubType.LEFT}`,
  CONSTANT_STONE_SHOOTER_RIGHT: `${EntityType.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterVariant.CONSTANT_STONE_SHOOTER}.${ConstantStoneShooterSubType.RIGHT}`,
  BRIMSTONE_HEAD: `${EntityType.BRIMSTONE_HEAD}.0.0`,
  GAPING_MAW: `${EntityType.GAPING_MAW}.0.0`,
  BROKEN_GAPING_MAW: `${EntityType.BROKEN_GAPING_MAW}.0.0`,
  QUAKE_GRIMACE: `${EntityType.QUAKE_GRIMACE}.0.0`,
  BOMB_GRIMACE: `${EntityType.BOMB_GRIMACE}.0.0`,
  MOCKULUS: `${EntityType.MOCKULUS}.0.0`,
  POKY: `${EntityType.POKY}.${PokyVariant.POKY}.0`,
  SLIDE: `${EntityType.POKY}.${PokyVariant.SLIDE}.0`,
  GRUDGE: `${EntityType.GRUDGE}.0.0`,
  BALL_AND_CHAIN: `${EntityType.BALL_AND_CHAIN}.0.0`,
  SPIKEBALL: `${EntityType.SPIKEBALL}.0.0`,
  SINGES_BALL: `${EntityType.SINGE}.${SingeVariant.SINGE_BALL}.0`,
  PITFALL: `${EntityType.PITFALL}.${PitfallVariant.PITFALL}.0`,
  SUCTION_PITFALL: `${EntityType.PITFALL}.${PitfallVariant.SUCTION_PITFALL}.0`,
  TELEPORT_PITFALL: `${EntityType.PITFALL}.${PitfallVariant.TELEPORT_PITFALL}.0`,
  CORN_MINE: `${EntityType.CORN_MINE}.0.0`,
  SIREN_MINION: `${EntityType.SIREN}.0.0`,
  SIREN_HELPER: `${EntityType.SIREN_HELPER}.0.0`,
  DARK_ESAU: `${EntityType.DARK_ESAU}.${DarkEsauVariant.DARK_ESAU}.0`,
  MOTHERS_SHADOW: `${EntityType.MOTHERS_SHADOW}.0.0`,
  PIT: `${EntityType.DARK_ESAU}.${DarkEsauVariant.PIT}.0`,
  DARK_BALL: `${EntityType.LITTLE_HORN}.${LittleHornVariant.DARK_BALL}.0`,
  PURPLE_BALL: `${EntityType.RAG_MEGA}.${RagMegaVariant.PURPLE_BALL}.0`,
  THE_VISAGE_PLASMA: `${EntityType.VISAGE}.${VisageVariant.VISAGE_PLASMA}.0`,
  ULTRA_DOOR: `${EntityType.ULTRA_DOOR}.0.0`,
  ULTRA_GREED_COIN_SPINNER: `${EntityType.ULTRA_COIN}.${UltraCoinVariant.SPINNER}.0`,
  ULTRA_GREED_COIN_KEY: `${EntityType.ULTRA_COIN}.${UltraCoinVariant.KEY}.0`,
  ULTRA_GREED_COIN_BOMB: `${EntityType.ULTRA_COIN}.${UltraCoinVariant.BOMB}.0`,
  ULTRA_GREED_COIN_HEART: `${EntityType.ULTRA_COIN}.${UltraCoinVariant.HEART}.0`,
  DUMMY: `${EntityType.DUMMY}.0.0`,
  MONSTRO: `${EntityType.MONSTRO}.0.${MonstroSubType.NORMAL}`,
  MONSTRO_GREY: `${EntityType.MONSTRO}.0.${MonstroSubType.GREY}`,
  MONSTRO_RED: `${EntityType.MONSTRO}.0.${MonstroSubType.RED}`,
  LARRY_JR: `${EntityType.LARRY_JR}.${LarryJrVariant.LARRY_JR}.${LarryJrSubType.NORMAL}`,
  LARRY_JR_BLUE: `${EntityType.LARRY_JR}.${LarryJrVariant.LARRY_JR}.${LarryJrSubType.BLUE}`,
  LARRY_JR_GREEN: `${EntityType.LARRY_JR}.${LarryJrVariant.LARRY_JR}.${LarryJrSubType.GREEN}`,
  THE_HOLLOW: `${EntityType.LARRY_JR}.${LarryJrVariant.THE_HOLLOW}.${HollowSubType.NORMAL}`,
  THE_HOLLOW_BLACK: `${EntityType.LARRY_JR}.${LarryJrVariant.THE_HOLLOW}.${HollowSubType.BLACK}`,
  THE_HOLLOW_GREEN: `${EntityType.LARRY_JR}.${LarryJrVariant.THE_HOLLOW}.${HollowSubType.GREEN}`,
  THE_HOLLOW_YELLOW: `${EntityType.LARRY_JR}.${LarryJrVariant.THE_HOLLOW}.${HollowSubType.YELLOW}`,
  THE_SHELL: `${EntityType.LARRY_JR}.${LarryJrVariant.THE_SHELL}.0`,
  TUFF_TWIN: `${EntityType.LARRY_JR}.${LarryJrVariant.TUFF_TWIN}.0`,
  CHUB: `${EntityType.CHUB}.${ChubVariant.CHUB}.${ChubSubType.NORMAL}`,
  CHUB_BLUE: `${EntityType.CHUB}.${ChubVariant.CHUB}.${ChubSubType.BLUE}`,
  CHUB_ORANGE: `${EntityType.CHUB}.${ChubVariant.CHUB}.${ChubSubType.ORANGE}`,
  CARRION_QUEEN: `${EntityType.CHUB}.${ChubVariant.CARRION_QUEEN}.${CarrionQueenSubType.NORMAL}`,
  CARRION_QUEEN_PINK: `${EntityType.CHUB}.${ChubVariant.CARRION_QUEEN}.${CarrionQueenSubType.PINK}`,
  CHAD: `${EntityType.CHUB}.${ChubVariant.CHAD}.0`,
  GURDY: `${EntityType.GURDY}.0.${GurdySubType.NORMAL}`,
  GURDY_GREEN: `${EntityType.GURDY}.0.${GurdySubType.GREEN}`,
  MONSTRO_2: `${EntityType.MONSTRO_2}.${Monstro2Variant.MONSTRO_2}.${Monstro2SubType.NORMAL}`,
  MONSTRO_2_RED: `${EntityType.MONSTRO_2}.${Monstro2Variant.MONSTRO_2}.${Monstro2SubType.RED}`,
  GISH: `${EntityType.MONSTRO_2}.${Monstro2Variant.GISH}.0`,
  MOM: `${EntityType.MOM}.${MomVariant.MOM}.${MomSubType.NORMAL}`,
  MOM_BLUE: `${EntityType.MOM}.${MomVariant.MOM}.${MomSubType.BLUE}`,
  MOM_RED: `${EntityType.MOM}.${MomVariant.MOM}.${MomSubType.RED}`,
  MOM_STOMP: `${EntityType.MOM}.${MomVariant.STOMP}.0`,
  MOM_STOMP_RED: `${EntityType.MOM}.${MomVariant.STOMP}.${MomSubType.RED}`,
  MOM_STOMP_BLUE: `${EntityType.MOM}.${MomVariant.STOMP}.${MomSubType.BLUE}`,
  SCOLEX: `${EntityType.PIN}.${PinVariant.SCOLEX}.0`,
  MOMS_HEART: `${EntityType.MOMS_HEART}.${MomsHeartVariant.MOMS_HEART}.0`,
  MOMS_GUTS: `${EntityType.MOMS_HEART}.${MomsHeartVariant.MOMS_GUTS}.0`,
  IT_LIVES: `${EntityType.MOMS_HEART}.${MomsHeartVariant.IT_LIVES}.0`,
  FAMINE: `${EntityType.FAMINE}.0.${FamineSubType.NORMAL}`,
  FAMINE_BLUE: `${EntityType.FAMINE}.0.${FamineSubType.BLUE}`,
  PESTILENCE: `${EntityType.FAMINE}.0.${PestilenceSubType.NORMAL}`,
  PESTILENCE_GREY: `${EntityType.FAMINE}.0.${PestilenceSubType.GREY}`,
  WAR: `${EntityType.FAMINE}.${WarVariant.WAR}.${WarSubType.NORMAL}`,
  WAR_GREY: `${EntityType.FAMINE}.${WarVariant.WAR}.${WarSubType.GREY}`,
  WAR_WITHOUT_HORSE: `${EntityType.FAMINE}.${WarVariant.WAR_WITHOUT_HORSE}.0`,
  CONQUEST: `${EntityType.FAMINE}.${WarVariant.CONQUEST}.0`,
  DEATH_BLACK: `${EntityType.DEATH}.${DeathVariant.DEATH}.${DeathSubType.BLACK}`,
  DEATH: `${EntityType.DEATH}.${DeathVariant.DEATH}.${DeathSubType.NORMAL}`,
  DEATH_HORSE: `${EntityType.DEATH}.${DeathVariant.DEATH_HORSE}.${DeathSubType.NORMAL}`,
  DEATH_HORSE_BLACK: `${EntityType.DEATH}.${DeathVariant.DEATH_HORSE}.${DeathSubType.BLACK}`,
  DEATH_SCYTHE: `${EntityType.DEATH}.${DeathVariant.DEATH_SCYTHE}.${DeathSubType.NORMAL}`,
  DEATH_SCYTHE_BLACK: `${EntityType.DEATH}.${DeathVariant.DEATH_SCYTHE}.${DeathSubType.BLACK}`,
  DEATH_WITHOUT_HORSE: `${EntityType.DEATH}.${DeathVariant.DEATH_WITHOUT_HORSE}.${DeathSubType.NORMAL}`,
  DEATH_WITHOUT_HORSE_BLACK: `${EntityType.DEATH}.${DeathVariant.DEATH_WITHOUT_HORSE}.${DeathSubType.BLACK}`,
  DUKE_OF_FLIES: `${EntityType.DUKE}.${DukeVariant.DUKE_OF_FLIES}.${DukeOfFliesSubType.NORMAL}`,
  DUKE_OF_FLIES_GREEN: `${EntityType.DUKE}.${DukeVariant.DUKE_OF_FLIES}.${DukeOfFliesSubType.GREEN}`,
  DUKE_OF_FLIES_ORANGE: `${EntityType.DUKE}.${DukeVariant.DUKE_OF_FLIES}.${DukeOfFliesSubType.ORANGE}`,
  THE_HUSK: `${EntityType.DUKE}.${DukeVariant.THE_HUSK}.${HuskSubType.NORMAL}`,
  THE_HUSK_RED: `${EntityType.DUKE}.${DukeVariant.THE_HUSK}.${HuskSubType.RED}`,
  THE_HUSK_BLACK: `${EntityType.DUKE}.${DukeVariant.THE_HUSK}.${HuskSubType.BLACK}`,
  PEEP: `${EntityType.PEEP}.${PeepVariant.PEEP}.${PeepSubType.NORMAL}`,
  PEEP_CYAN: `${EntityType.PEEP}.${PeepVariant.PEEP}.${PeepSubType.CYAN}`,
  PEEP_YELLOW: `${EntityType.PEEP}.${PeepVariant.PEEP}.${PeepSubType.YELLOW}`,
  PEEP_EYE: `${EntityType.PEEP}.${PeepVariant.PEEP_EYE}.${PeepSubType.NORMAL}`,
  BLOAT: `${EntityType.PEEP}.${PeepVariant.BLOAT}.${BloatSubType.NORMAL}`,
  BLOAT_GREEN: `${EntityType.PEEP}.${PeepVariant.BLOAT}.${BloatSubType.GREEN}`,
  BLOAT_EYE: `${EntityType.PEEP}.${PeepVariant.BLOAT_EYE}.${BloatSubType.NORMAL}`,
  LOKI: `${EntityType.LOKI}.${LokiVariant.LOKI}.0}`,
  LOKII: `${EntityType.LOKI}.${LokiVariant.LOKII}.0}`,
  BLASTOCYST_BIG: `${EntityType.BLASTOCYST_BIG}.0.0`,
  BLASTOCYST_MEDIUM: `${EntityType.BLASTOCYST_MEDIUM}.0.0`,
  BLASTOCYST_SMALL: `${EntityType.BLASTOCYST_SMALL}.0.0`,
  CYST: `${EntityType.CYST}.0.0`,
  GEMINI: `${EntityType.GEMINI}.${GeminiVariant.GEMINI}.${GeminiSubType.NORMAL}`,
  GEMINI_BLUE: `${EntityType.GEMINI}.${GeminiVariant.GEMINI}.${GeminiSubType.BLUE}`,
  GEMINI_GREEN: `${EntityType.GEMINI}.${GeminiVariant.GEMINI}.${GeminiSubType.GREEN}`,
  GEMINI_BABY: `${EntityType.GEMINI}.${GeminiVariant.GEMINI_BABY}.${GeminiSubType.NORMAL}`,
  GEMINI_BABY_BLUE: `${EntityType.GEMINI}.${GeminiVariant.GEMINI_BABY}.${GeminiSubType.BLUE}`,
  GEMINI_BABY_GREEN: `${EntityType.GEMINI}.${GeminiVariant.GEMINI_BABY}.${GeminiSubType.GREEN}`,
  STEVEN: `${EntityType.GEMINI}.${GeminiVariant.STEVEN}.0`,
  STEVEN_BABY: `${EntityType.GEMINI}.${GeminiVariant.STEVEN_BABY}.0`,
  BLIGHTED_OVUM: `${EntityType.GEMINI}.${GeminiVariant.BLIGHTED_OVUM}.0`,
  BLIGHTED_OVUM_BABY: `${EntityType.GEMINI}.${GeminiVariant.BLIGHTED_OVUM_BABY}.0`,
  FISTULA_BIG: `${EntityType.FISTULA_BIG}.${FistulaVariant.FISTULA}.${FistulaSubType.NORMAL}`,
  FISTULA_MEDIUM: `${EntityType.FISTULA_MEDIUM}.${FistulaVariant.FISTULA}.${FistulaSubType.NORMAL}`,
  FISTULA_SMALL: `${EntityType.FISTULA_SMALL}.${FistulaVariant.FISTULA}.${FistulaSubType.NORMAL}`,
  FISTULA_BIG_GREY: `${EntityType.FISTULA_BIG}.${FistulaVariant.FISTULA}.${FistulaSubType.GREY}`,
  FISTULA_MEDIUM_GREY: `${EntityType.FISTULA_MEDIUM}.${FistulaVariant.FISTULA}.${FistulaSubType.GREY}`,
  FISTULA_SMALL_GREY: `${EntityType.FISTULA_SMALL}.${FistulaVariant.FISTULA}.${FistulaSubType.GREY}`,
  TERATOMA: `${EntityType.FISTULA_BIG}.${FistulaVariant.TERATOMA}.0`,
  HEADLESS_HORSEMAN: `${EntityType.HEADLESS_HORSEMAN}.0.0`,
  THE_FALLEN: `${EntityType.FALLEN}.${FallenVariant.FALLEN}.0`,
  KRAMPUS: `${EntityType.FALLEN}.${FallenVariant.KRAMPUS}.0`,
  SATAN: `${EntityType.SATAN}.${SatanVariant.SATAN}.0`,
  SATAN_STOMP: `${EntityType.SATAN}.${SatanVariant.STOMP}.0`,
  GURDY_JR: `${EntityType.GURDY_JR}.0.${GurdyJrSubType.NORMAL}`,
  GURDY_JR_BLUE: `${EntityType.GURDY_JR}.0.${GurdyJrSubType.BLUE}`,
  GURDY_JR_YELLOW: `${EntityType.GURDY_JR}.0.${GurdyJrSubType.YELLOW}`,
  THE_WIDOW: `${EntityType.WIDOW}.${WidowVariant.WIDOW}.${WidowSubType.NORMAL}`,
  THE_WIDOW_BLACK: `${EntityType.WIDOW}.${WidowVariant.WIDOW}.${WidowSubType.BLACK}`,
  THE_WIDOW_PINK: `${EntityType.WIDOW}.${WidowVariant.WIDOW}.${WidowSubType.PINK}`,
  THE_WRETCHED: `${EntityType.WIDOW}.${WidowVariant.THE_WRETCHED}.0`,
  MASK_OF_INFAMY: `${EntityType.MASK_OF_INFAMY}.0.0`,
  MASK_OF_INFAMY_BLACK: `${EntityType.MASK_OF_INFAMY}.0.1`,
  PIN: `${EntityType.PIN}.${PinVariant.PIN}.${PinSubType.NORMAL}`,
  PIN_GREY: `${EntityType.PIN}.${PinVariant.PIN}.${PinSubType.GREY}`,
  FRAIL: `${EntityType.PIN}.${PinVariant.FRAIL}.${FrailSubType.NORMAL}`,
  FRAIL_BLACK: `${EntityType.PIN}.${PinVariant.FRAIL}.${FrailSubType.BLACK}`,
  WORMWOOD: `${EntityType.PIN}.${PinVariant.WORMWOOD}.0`,
  ISAAC: `${EntityType.ISAAC}.${IsaacVariant.ISAAC}.0`,
  BLUE_BABY: `${EntityType.ISAAC}.${IsaacVariant.BLUE_BABY}.0`,
  BLUE_BABY_HUSH: `${EntityType.ISAAC}.${IsaacVariant.BLUE_BABY_HUSH}.0`,
  DADDY_LONG_LEGS: `${EntityType.DADDY_LONG_LEGS}.${DaddyLongLegsVariant.DADDY_LONG_LEGS}.0`,
  TRIACHNID: `${EntityType.DADDY_LONG_LEGS}.${DaddyLongLegsVariant.TRIACHNID}.0`,
  THE_HAUNT: `${EntityType.THE_HAUNT}.${HauntVariant.HAUNT}.${HauntSubType.NORMAL}`,
  THE_HAUNT_BLACK: `${EntityType.THE_HAUNT}.${HauntVariant.HAUNT}.${HauntSubType.BLACK}`,
  THE_HAUNT_PINK: `${EntityType.THE_HAUNT}.${HauntVariant.HAUNT}.${HauntSubType.PINK}`,
  DINGLE: `${EntityType.DINGLE}.${DingleVariant.DINGLE}.${DingleSubType.NORMAL}`,
  DINGLE_BLACK: `${EntityType.DINGLE}.${DingleVariant.DINGLE}.${DingleSubType.BLACK}`,
  DINGLE_RED: `${EntityType.DINGLE}.${DingleVariant.DINGLE}.${DingleSubType.RED}`,
  DANGLE: `${EntityType.DINGLE}.${DingleVariant.DANGLE}.0`,
  MEGA_MAW: `${EntityType.MEGA_MAW}.0.${MegaMawSubType.NORMAL}`,
  MEGA_MAW_BLACK: `${EntityType.MEGA_MAW}.0.${MegaMawSubType.BLACK}`,
  MEGA_MAW_RED: `${EntityType.MEGA_MAW}.0.${MegaMawSubType.RED}`,
  THE_GATE: `${EntityType.GATE}.0.${GateSubType.NORMAL}`,
  THE_GATE_BLACK: `${EntityType.GATE}.0.${GateSubType.BLACK}`,
  THE_GATE_RED: `${EntityType.GATE}.0.${GateSubType.RED}`,
  MEGA_FATTY: `${EntityType.MEGA_FATTY}.0.${MegaFattySubType.NORMAL}`,
  MEGA_FATTY_BROWN: `${EntityType.MEGA_FATTY}.0.${MegaFattySubType.BROWN}`,
  MEGA_FATTY_RED: `${EntityType.MEGA_FATTY}.0.${MegaFattySubType.RED}`,
  THE_CAGE: `${EntityType.CAGE}.0.${CageSubType.NORMAL}`,
  THE_CAGE_GREEN: `${EntityType.CAGE}.0.${CageSubType.GREEN}`,
  THE_CAGE_PINK: `${EntityType.CAGE}.0.${CageSubType.PINK}`,
  MAMA_GURDY: `${EntityType.MAMA_GURDY}.${MamaGurdyVariant.MAMA_GURDY}.0`,
  MAMA_GURDY_LEFT_HAND: `${EntityType.MAMA_GURDY}.${MamaGurdyVariant.LEFT_HAND}.0`,
  MAMA_GURDY_RIGHT_HAND: `${EntityType.MAMA_GURDY}.${MamaGurdyVariant.RIGHT_HAND}.0`,
  DARK_ONE: `${EntityType.DARK_ONE}.0.0`,
  THE_ADVERSARY: `${EntityType.ADVERSARY}.0.0`,
  POLYCEPHALUS: `${EntityType.POLYCEPHALUS}.${PolycephalusVariant.POLYCEPHALUS}.${PolycephalusSubType.NORMAL}`,
  POLYCEPHALUS_PINK: `${EntityType.POLYCEPHALUS}.${PolycephalusVariant.POLYCEPHALUS}.${PolycephalusSubType.PINK}`,
  POLYCEPHALUS_RED: `${EntityType.POLYCEPHALUS}.${PolycephalusVariant.POLYCEPHALUS}.${PolycephalusSubType.RED}`,
  THE_PILE: `${EntityType.POLYCEPHALUS}.${PolycephalusVariant.THE_PILE}.0`,
  MR_FRED: `${EntityType.MR_FRED}.0.0`,
  THE_LAMB: `${EntityType.THE_LAMB}.${LambVariant.LAMB}.0`,
  THE_LAMB_BODY: `${EntityType.THE_LAMB}.${LambVariant.BODY}.0`,
  MEGA_SATAN: `${EntityType.MEGA_SATAN}.${MegaSatanVariant.MEGA_SATAN}.0`,
  MEGA_SATAN_LEFT_HAND: `${EntityType.MEGA_SATAN}.${MegaSatanVariant.MEGA_SATAN_LEFT_HAND}.0`,
  MEGA_SATAN_RIGHT_HAND: `${EntityType.MEGA_SATAN}.${MegaSatanVariant.MEGA_SATAN_RIGHT_HAND}.0`,
  MEGA_SATAN_2: `${EntityType.MEGA_SATAN_2}.${MegaSatanVariant.MEGA_SATAN}.0`,
  MEGA_SATAN_2_LEFT_HAND: `${EntityType.MEGA_SATAN_2}.${MegaSatanVariant.MEGA_SATAN_LEFT_HAND}.0`,
  MEGA_SATAN_2_RIGHT_HAND: `${EntityType.MEGA_SATAN_2}.${MegaSatanVariant.MEGA_SATAN_RIGHT_HAND}.0`,
  GURGLING_BOSS: `${EntityType.GURGLING}.${GurglingVariant.GURGLING_BOSS}.${GurglingSubType.NORMAL}`,
  GURGLING_BOSS_BLACK: `${EntityType.GURGLING}.${GurglingVariant.GURGLING_BOSS}.${GurglingSubType.BLACK}`,
  GURGLING_BOSS_YELLOW: `${EntityType.GURGLING}.${GurglingVariant.GURGLING_BOSS}.${GurglingSubType.YELLOW}`,
  GURGLING: `${EntityType.GURGLING}.${GurglingVariant.GURGLING}.0`,
  THE_STAIN: `${EntityType.STAIN}.0.${StainSubType.NORMAL}`,
  THE_STAIN_GREY: `${EntityType.STAIN}.0.${StainSubType.GREY}`,
  BROWNIE: `${EntityType.BROWNIE}.0.${BrownieSubType.NORMAL}`,
  BROWNIE_BLACK: `${EntityType.BROWNIE}.0.${BrownieSubType.BLACK}`,
  THE_FORSAKEN: `${EntityType.FORSAKEN}.0.${ForsakenSubType.NORMAL}`,
  THE_FORSAKEN_BLACK: `${EntityType.FORSAKEN}.0.${ForsakenSubType.BLACK}`,
  LITTLE_HORN: `${EntityType.LITTLE_HORN}.${LittleHornVariant.LITTLE_HORN}.${LittleHornSubType.NORMAL}`,
  LITTLE_HORN_BLACK: `${EntityType.LITTLE_HORN}.${LittleHornVariant.LITTLE_HORN}.${LittleHornSubType.BLACK}`,
  LITTLE_HORN_ORANGE: `${EntityType.LITTLE_HORN}.${LittleHornVariant.LITTLE_HORN}.${LittleHornSubType.ORANGE}`,
  RAG_MAN: `${EntityType.RAG_MAN}.${RagManVariant.RAG_MAN}.${RagManSubType.NORMAL}`,
  RAG_MAN_BLACK: `${EntityType.RAG_MAN}.${RagManVariant.RAG_MAN}.${RagManSubType.BLACK}`,
  RAG_MAN_RED: `${EntityType.RAG_MAN}.${RagManVariant.RAG_MAN}.${RagManSubType.RED}`,
  RAG_MAN_HEAD: `${EntityType.RAG_MAN}.${RagManVariant.RAG_MAN_HEAD}.${RagManSubType.NORMAL}`,
  ULTRA_GREED: `${EntityType.ULTRA_GREED}.${UltraGreedVariant.ULTRA_GREED}.0`,
  ULTRA_GREEDIER: `${EntityType.ULTRA_GREED}.${UltraGreedVariant.ULTRA_GREEDIER}.0`,
  HUSH: `${EntityType.HUSH}.0.0`,
  HUSH_SKINLESS: `${EntityType.HUSH_SKINLESS}.0.0`,
  TURDLING: `${EntityType.GURGLING}.${GurglingVariant.TURDLING}.0`,
  RAG_MEGA: `${EntityType.RAG_MEGA}.${RagMegaVariant.RAG_MEGA}.0`,
  REBIRTH_PILLAR: `${EntityType.RAG_MEGA}.${RagMegaVariant.REBIRTH_PILLAR}.0`,
  SISTERS_VIS: `${EntityType.SISTERS_VIS}.0.0`,
  BIG_HORN: `${EntityType.BIG_HORN}.${BigHornVariant.BIG_HORN}.0`,
  BIG_HOLE: `${EntityType.BIG_HORN}.${BigHornVariant.BIG_HOLE}.0`,
  SMALL_HOLE: `${EntityType.BIG_HORN}.${BigHornVariant.SMALL_HOLE}.0`,
  DELIRIUM: `${EntityType.DELIRIUM}.0.0`,
  THE_MATRIARCH: `${EntityType.MATRIARCH}.0.0`,
  REAP_CREEP: `${EntityType.REAP_CREEP}.0.0`,
  LIL_BLUB: `${EntityType.LIL_BLUB}.0.0`,
  RAINMAKER: `${EntityType.RAINMAKER}.0.0`,
  THE_VISAGE: `${EntityType.VISAGE}.${VisageVariant.VISAGE}.0`,
  THE_VISAGE_MASK: `${EntityType.VISAGE}.${VisageVariant.VISAGE_MASK}.0`,
  THE_VISAGE_CHAIN: `${EntityType.VISAGE}.${VisageVariant.VISAGE_CHAIN}.0`,
  THE_SIREN: `${EntityType.SIREN}.${SirenVariant.SIREN}.0`,
  THE_SIREN_SKULL: `${EntityType.SIREN}.${SirenVariant.SIREN}.0`,
  THE_SIREN_PROJECTILE: `${EntityType.SIREN}.${SirenVariant.SIREN_HELPER_PROJECTILE}.0`,
  THE_HERETIC: `${EntityType.HERETIC}.0.0`,
  HORNFEL: `${EntityType.HORNFEL}.0.0`,
  GREAT_GIDEON: `${EntityType.GREAT_GIDEON}.0.0`,
  BABY_PLUM: `${EntityType.BABY_PLUM}.0.0`,
  THE_SCOURGE: `${EntityType.SCOURGE}.${ScourgeVariant.SCOURGE}.0`,
  THE_SCOURGE_CHAIN: `${EntityType.SCOURGE}.${ScourgeVariant.SCOURGE_CHAIN}.0`,
  CHIMERA: `${EntityType.CHIMERA}.${ChimeraVariant.CHIMERA}.0`,
  CHIMERA_BODY: `${EntityType.CHIMERA}.${ChimeraVariant.CHIMERA_BODY}.0`,
  CHIMERA_HEAD: `${EntityType.CHIMERA}.${ChimeraVariant.CHIMERA_HEAD}.0`,
  ROTGUT: `${EntityType.ROTGUT}.${RotgutVariant.PHASE_1_HEAD}.0`,
  ROTGUT_MAGGOT: `${EntityType.ROTGUT}.${RotgutVariant.PHASE_2_MAGGOT}.0`,
  ROTGUT_HEART: `${EntityType.ROTGUT}.${RotgutVariant.PHASE_3_HEART}.0`,
  MOTHER: `${EntityType.MOTHER}.${MotherVariant.MOTHER_1}.${MotherSubType.PHASE_1}`,
  MOTHER_PHASE_2: `${EntityType.MOTHER}.${MotherVariant.MOTHER_1}.${MotherSubType.PHASE_2}`,
  MOTHER_2: `${EntityType.MOTHER}.${MotherVariant.MOTHER_2}.${MotherSubType.PHASE_1}`,
  MOTHER_2_PHASE_2: `${EntityType.MOTHER}.${MotherVariant.MOTHER_2}.${MotherSubType.PHASE_2}`,
  MOTHER_BALL: `${EntityType.MOTHER}.${MotherVariant.BALL}.0`,
  MIN_MIN: `${EntityType.MIN_MIN}.0.0`,
  CLOG: `${EntityType.CLOG}.0.0`,
  SINGE: `${EntityType.SINGE}.${SingeVariant.SINGE}.0`,
  SINGE_BALL: `${EntityType.SINGE}.${SingeVariant.SINGE_BALL}.0`,
  BUMBINO: `${EntityType.BUMBINO}.0.0`,
  COLOSTOMIA: `${EntityType.COLOSTOMIA}.0.0`,
  TURDLET: `${EntityType.TURDLET}.0.0`,
  RAGLICH: `${EntityType.RAGLICH}.${RaglichVariant.RAGLICH}.0`,
  RAGLICH_ARM: `${EntityType.RAGLICH}.${RaglichVariant.RAGLICH_ARM}.0`,
  DOGMA_PHASE_1: `${EntityType.DOGMA}.${DogmaVariant.DOGMA_PHASE_1}.0`,
  DOGMA_PHASE_2: `${EntityType.DOGMA}.${DogmaVariant.ANGEL_PHASE_2}.0`,
  DOGMA_ANGEL_BABY: `${EntityType.DOGMA}.${DogmaVariant.ANGEL_BABY_UNUSED}.0`,
  DOGMA_TV: `${EntityType.DOGMA}.${DogmaVariant.TV}.0`,
  BEAST: `${EntityType.BEAST}.${BeastVariant.BEAST}.0`,
  BACKGROUND_BEAST: `${EntityType.BEAST}.${BeastVariant.BACKGROUND_BEAST}.0`,
  BACKGROUND_DEATH: `${EntityType.BEAST}.${BeastVariant.BACKGROUND_DEATH}.0`,
  BACKGROUND_FAMINE: `${EntityType.BEAST}.${BeastVariant.BACKGROUND_FAMINE}.0`,
  BACKGROUND_PESTILENCE: `${EntityType.BEAST}.${BeastVariant.BACKGROUND_PESTILENCE}.0`,
  BACKGROUND_WAR: `${EntityType.BEAST}.${BeastVariant.BACKGROUND_WAR}.0`,
  ROCK_PROJECTILE: `${EntityType.BEAST}.${BeastVariant.ROCK_PROJECTILE}.0`,
  SOUL: `${EntityType.BEAST}.${BeastVariant.SOUL}.0`,
  STALACTITE: `${EntityType.BEAST}.${BeastVariant.STALACTITE}.0`,
  ULTRA_DEATH: `${EntityType.BEAST}.${BeastVariant.ULTRA_DEATH}.0`,
  ULTRA_DEATH_HEAD: `${EntityType.BEAST}.${BeastVariant.ULTRA_DEATH_HEAD}.0`,
  ULTRA_DEATH_SCYTHE: `${EntityType.BEAST}.${BeastVariant.ULTRA_DEATH_SCYTHE}.0`,
  ULTRA_FAMINE: `${EntityType.BEAST}.${BeastVariant.ULTRA_FAMINE}.0`,
  ULTRA_FAMINE_FLY: `${EntityType.BEAST}.${BeastVariant.ULTRA_FAMINE_FLY}.0`,
  ULTRA_PESTILENCE: `${EntityType.BEAST}.${BeastVariant.ULTRA_PESTILENCE}.0`,
  ULTRA_PESTILENCE_FLY: `${EntityType.BEAST}.${BeastVariant.ULTRA_PESTILENCE_FLY}.0`,
  ULTRA_PESTILENCE_FLY_BALL: `${EntityType.BEAST}.${BeastVariant.ULTRA_PESTILENCE_FLY_BALL}.0`,
  ULTRA_PESTILENCE_MAGGOT: `${EntityType.BEAST}.${BeastVariant.ULTRA_PESTILENCE_MAGGOT}.0`,
  ULTRA_WAR: `${EntityType.BEAST}.${BeastVariant.ULTRA_WAR}.0`,
  ULTRA_WAR_BOMB: `${EntityType.BEAST}.${BeastVariant.ULTRA_WAR_BOMB}.0`,
  HORNY_BOYS: `${EntityType.HORNY_BOYS}.0.0`,
  CLUTCH: `${EntityType.CLUTCH}.${ClutchVariant.CLUTCH}.0`,
  CLUTCH_ORBITAL: `${EntityType.CLUTCH}.${ClutchVariant.CLUTCH_ORBITAL}.0`,
  SLOTH: `${EntityType.SLOTH}.${SlothVariant.SLOTH}.0`,
  SUPER_SLOTH: `${EntityType.SLOTH}.${SlothVariant.SUPER_SLOTH}.0`,
  ULTRA_PRIDE: `${EntityType.SLOTH}.${SlothVariant.ULTRA_PRIDE}.0`,
  LUST: `${EntityType.LUST}.${LustVariant.LUST}.0`,
  SUPER_LUST: `${EntityType.LUST}.${LustVariant.SUPER_LUST}.0`,
  WRATH: `${EntityType.LUST}.${WrathVariant.WRATH}.0`,
  SUPER_WRATH: `${EntityType.LUST}.${WrathVariant.SUPER_WRATH}.0`,
  GLUTTONY: `${EntityType.GLUTTONY}.${GluttonyVariant.GLUTTONY}.0`,
  SUPER_GLUTTONY: `${EntityType.GLUTTONY}.${GluttonyVariant.SUPER_GLUTTONY}.0`,
  ENVY: `${EntityType.GLUTTONY}.${EnvyVariant.ENVY}.0`,
  ENVY_BIG: `${EntityType.GLUTTONY}.${EnvyVariant.ENVY_BIG}.0`,
  ENVY_MEDIUM: `${EntityType.GLUTTONY}.${EnvyVariant.ENVY_MEDIUM}.0`,
  ENVY_SMALL: `${EntityType.GLUTTONY}.${EnvyVariant.ENVY_SMALL}.0`,
  SUPER_ENVY: `${EntityType.GLUTTONY}.${EnvyVariant.SUPER_ENVY}.0`,
  SUPER_ENVY_BIG: `${EntityType.GLUTTONY}.${EnvyVariant.SUPER_ENVY_BIG}.0`,
  SUPER_ENVY_SMALL: `${EntityType.GLUTTONY}.${EnvyVariant.SUPER_ENVY_SMALL}.0`,
  SUPER_ENVY_MEDIUM: `${EntityType.GLUTTONY}.${EnvyVariant.SUPER_ENVY_MEDIUM}.0`,
  PRIDE: `${EntityType.PRIDE}.${PrideVariant.PRIDE}.0`,
  SUPER_PRIDE: `${EntityType.PRIDE}.${PrideVariant.SUPER_PRIDE}.0`,
  GABRIEL: `${EntityType.GABRIEL}.${AngelVariant.NORMAL}.0`,
  GABRIEL_FALLEN: `${EntityType.GABRIEL}.${AngelVariant.FALLEN}.0`,
  URIEL: `${EntityType.URIEL}.${AngelVariant.NORMAL}.0`,
  URIEL_FALLEN: `${EntityType.URIEL}.${AngelVariant.FALLEN}.0`,
} as const;

/** EntityIDs which correlate to an NPC. */
export type NPCID = typeof NPCID[keyof typeof NPCID];
