/**
 * Corresponds to the filename used in the XML/STB file for the room.
 *
 * This enum is contiguous. (Every value is satisfied between 0 and 36, inclusive.)
 */
export enum StageID {
  SPECIAL_ROOMS = 0,
  BASEMENT = 1,
  CELLAR = 2,
  BURNING_BASEMENT = 3,
  CAVES = 4,
  CATACOMBS = 5,
  FLOODED_CAVES = 6,
  DEPTHS = 7,
  NECROPOLIS = 8,
  DANK_DEPTHS = 9,
  WOMB = 10,
  UTERO = 11,
  SCARRED_WOMB = 12,
  BLUE_WOMB = 13,
  SHEOL = 14,
  CATHEDRAL = 15,
  DARK_ROOM = 16,
  CHEST = 17,
  SPECIAL_ROOMS_GREED_MODE = 18,
  BASEMENT_GREED_MODE = 19,
  CAVES_GREED_MODE = 20,
  DEPTHS_GREED_MODE = 21,
  WOMB_GREED_MODE = 22,
  SHEOL_GREED_MODE = 23,
  SHOP_GREED_MODE = 24,
  ULTRA_GREED_GREED_MODE = 25,
  VOID = 26,
  DOWNPOUR = 27,
  DROSS = 28,
  MINES = 29,
  ASHPIT = 30,
  MAUSOLEUM = 31,
  GEHENNA = 32,
  CORPSE = 33,
  MORTIS = 34,
  HOME = 35,
  BACKWARDS = 36,
}
