name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup
      - run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup
      - run: npm run lint

  # To enable CI failure notifications over Discord:
  # - Right click on a channel in Discord and select "Edit Channel".
  # - Click on "Integrations" on the left menu.
  # - Click on the "Create Webhook" button.
  # - Click on the box for the new webhook that was created.
  # - Change the name to "GitHub".
  # - Change the image to: https://github.com/IsaacScript/isaacscript/raw/main/misc/github.png
  # - Click on the "Save Changes" button at the bottom.
  # - Click on the "Copy Webhook URL" button.
  # - Go to the main page for your repository on GitHub.
  # - Click on the "Settings" tab near the top.
  # - Click on "Secrets and variables" in the left menu.
  # - Click on "Actions" from the dropdown list.
  # - Click on the "New repository secret" button in the top right.
  # - For the "Name" box, use "DISCORD_WEBHOOK" (without the quotes).
  # - For the "Secret" box, paste in the URL that was copied in the "Copy Webhook URL" step. (The
  #   pasted URL should not have a "/github" suffix.)
  # - Click on the "Add secret" button.
  # - Delete this comment and uncomment the lines below.
  #discord:
  #  name: Discord Failure Notification
  #  needs: [build, lint]
  #  if: always() # This is needed to always run this job, even if the other jobs fail.
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: technote-space/workflow-conclusion-action@v3
  #    - if: env.WORKFLOW_CONCLUSION != 'success' && env.WORKFLOW_CONCLUSION != 'cancelled'
  #      uses: sarisia/actions-status-discord@v1
  #      with:
  #        webhook: ${{ secrets.DISCORD_WEBHOOK }}
  #        status: ${{ env.WORKFLOW_CONCLUSION }}
  #        title: ""
