// This generates the files in the "src/configs" directory.

import type { TSESLint } from "@typescript-eslint/utils";
import { writeFile } from "complete-node";
import path from "node:path";
import { PACKAGE_ROOT } from "./constants.js";
import type { RuleDefinition } from "./utils.js";
import {
  formatWithPrettier,
  getAutoGeneratedComment,
  getRuleEntries,
  getRuleNameWithPluginNamePrefix,
  isRecommendedRule,
} from "./utils.js";

type LinterConfigRules = Record<
  string,
  TSESLint.Linter.RuleLevel | TSESLint.Linter.RuleLevelAndOptions
>;

export const CONFIGS_DIRECTORY_PATH = path.join(PACKAGE_ROOT, "src", "configs");

const BASE_CONFIG = [
  // The main config object.
  {
    // The "plugins" property is populated in the "index.ts" file.
    plugins: {},

    // The "rules" property is populated below.
    rules: {},
  },
] as const satisfies TSESLint.FlatConfig.ConfigArray;

export async function generateConfigs(): Promise<void> {
  await recommended();
}

async function recommended() {
  const ruleEntries = await getRuleEntries();
  const recommendedRules = ruleEntries
    .filter((entry) => isRecommendedRule(entry[1]))
    // eslint-disable-next-line unicorn/no-array-reduce
    .reduce<LinterConfigRules>((config, entry) => reducer(config, entry), {});

  const rules = BASE_CONFIG[0].rules as Record<string, unknown>;
  for (const [ruleName, level] of Object.entries(recommendedRules)) {
    rules[ruleName] = level;
  }

  await writeConfig("recommended", BASE_CONFIG);
}

async function writeConfig(
  name: string,
  config: readonly TSESLint.FlatConfig.Config[],
) {
  const comment = getAutoGeneratedComment();
  const code = `import type { TSESLint } from "@typescript-eslint/utils";\n\nexport const ${name}: TSESLint.FlatConfig.ConfigArray = ${JSON.stringify(config)};`;
  const combined = comment + code;
  const content = await formatWithPrettier(combined, "typescript");

  const fileName = `${name}.ts`;
  const filePath = path.join(CONFIGS_DIRECTORY_PATH, fileName);
  await writeFile(filePath, content);
}

/** Reduces records to key/value pairs. */
function reducer(
  config: LinterConfigRules,
  entry: [string, RuleDefinition],
): LinterConfigRules {
  const [ruleName] = entry;
  const fullRuleName = getRuleNameWithPluginNamePrefix(ruleName);
  config[fullRuleName] = "error";

  return config;
}
