/**
 * This enum is for REPENTOGON, an exe-hack which expands the modding API.
 *
 * @see https://repentogon.com/
 */
export enum StbRailVariant {
  HORIZONTAL = 0,
  VERTICAL = 1,
  DOWN_TO_RIGHT = 2,
  DOWN_TO_LEFT = 3,
  UP_TO_RIGHT = 4,
  UP_TO_LEFT = 5,
  JUNCTION = 6,
  END_LEFT = 7,
  END_RIGHT = 8,
  END_UP = 9,
  END_DOWN = 10,
  HORIZONTAL_CART_LEFT = 16,
  VERTICAL_CART_UP = 17,
  HORIZONTAL_CART_RIGHT = 32,
  VERTICAL_CART_DOWN = 33,
  MINESHAFT_HORIZONTAL_1 = 80,
  MINESHAFT_VERTICAL_1 = 81,
  MINESHAFT_DOWN_TO_RIGHT_1 = 82,
  MINESHAFT_DOWN_TO_LEFT_1 = 83,
  MINESHAFT_UP_TO_RIGHT_1 = 84,
  MINESHAFT_UP_TO_LEFT_1 = 85,
  MINESHAFT_HORIZONTAL_2 = 96,
  MINESHAFT_DOWN_TO_RIGHT_2 = 98,
  MINESHAFT_VERTICAL_2 = 97,
  MINESHAFT_DOWN_TO_LEFT_2 = 99,
  MINESHAFT_UP_TO_RIGHT_2 = 100,
  MINESHAFT_UP_TO_LEFT_2 = 101,
  MINESHAFT_HORIZONTAL_3 = 112,
  MINESHAFT_VERTICAL_3 = 113,
}
