export enum StageTravelState {
  NONE,
  PLAYERS_JUMPING_DOWN,
  PIXELATION_TO_BLACK,
  WAITING_FOR_FIRST_PIXELATION_TO_END,
  WAITING_FOR_SECOND_PIXELATION_TO_GET_HALF_WAY,
  PIXELATION_TO_ROOM,
  PLAYERS_LAYING_DOWN,
}
