// cspell:disable
export const CARD_DESCRIPTION_MAP = new Map<Card, string>([
  [1, "Where journey begins"],
  [2, "May you never miss your goal"],
  [3, "Mother is watching you"],
  [4, "May your rage bring power"],
  [5, "Challenge me!"],
  [6, "Two prayers for the lost"],
  [7, "May you prosper and be in good health"],
  [8, "May nothing stand before you"],
  [9, "May your future become balanced"],
  [10, "May you see what life has to offer"],
  [11, "Spin the wheel of destiny"],
  [12, "May your power bring rage"],
  [13, "May you find enlightenment "],
  [14, "Lay waste to all that oppose you "],
  [15, "May you be pure in heart"],
  [16, "Revel in the power of darkness"],
  [17, "Destruction brings creation"],
  [18, "May you find what you desire "],
  [19, "May you find all you have lost"],
  [20, "May the light heal and enlighten you"],
  [21, "Judge lest ye be judged"],
  [22, "Open your eyes and see"],
  [23, "Item multiplier"],
  [24, "Item multiplier"],
  [25, "Item multiplier"],
  [26, "Item multiplier"],
  [27, "Convert all"],
  [28, "Convert all"],
  [29, "Convert all"],
  [30, "Convert all"],
  [31, "???"],
  [32, "Destruction"],
  [33, "Abundance"],
  [34, "Passage"],
  [35, "Purity"],
  [36, "Vision"],
  [37, "Change"],
  [38, "Companionship"],
  [39, "Resistance"],
  [40, "???"],
  [41, "Void"],
  [42, "???"],
  [43, "Charge it!"],
  [44, "???"],
  [45, "Something stinks..."],
  [46, "A true ending?"],
  [47, "Open Sesame"],
  [48, "Double active"],
  [49, "D6 + D20"],
  [50, "Help from above"],
  [51, "You feel protected"],
  [52, "Become immense!"],
  [53, "Draw 3 cards"],
  [54, "Savor the moment"],
  [55, "It still glows faintly"],
  [56, "Let go and move on"],
  [57, "May no harm come to you"],
  [58, "Run"],
  [59, "May your love bring protection"],
  [60, "May you find a worthy opponent"],
  [61, "Two prayers for the forgotten"],
  [62, "May your heart shatter into pieces"],
  [63, "May nothing walk past you"],
  [64, "May your sins come back to torment you"],
  [65, "May you see the value of all things in life"],
  [66, "Throw the dice of fate"],
  [67, "May you break their resolve"],
  [68, "May your greed know no bounds"],
  [69, "May life spring forth from the fallen"],
  [70, "May your hunger be satiated"],
  [71, "Bask in the light of your mercy"],
  [72, "Creation brings destruction"],
  [73, "May your loss bring fortune"],
  [74, "May you remember lost memories"],
  [75, "May the darkness swallow all around you"],
  [76, "May you redeem those found wanting"],
  [77, "Step into the abyss"],
  [78, "???"],
  [79, "<3"],
  [80, "Again"],
  [81, "Reroll... or not"],
  [82, "Give me your love!"],
  [83, "Opens the unopenable"],
  [84, "Right behind you"],
  [85, "Chemical warfare"],
  [86, "Your very own murder"],
  [87, "Slay a thousand"],
  [88, "Demon rage!"],
  [89, "Life after death"],
  [90, "Embrace chaos"],
  [91, "Leave your body behind"],
  [92, "Motherhood"],
  [93, "$$$"],
  [94, "Bringer of calamity"],
  [95, "Skeletal protector"],
  [96, "Friends from beyond"],
  [97, "Bound by blood"],
]);
