/* eslint-disable sort-exports/sort-exports */
/* cspell:disable */

export const DEFAULT_COLLECTIBLE_DESCRIPTION = "Unknown";

// Temporary map due to missing features in the vanilla API
// (otherwise this would be converted to a type-safe object)
export const COLLECTIBLE_DESCRIPTION_MAP: ReadonlyMap<CollectibleType, string> =
  new Map([
    [1, "Tears up"],
    [2, "Triple shot"],
    [3, "Homing shots"],
    [4, "DMG up"],
    [5, "Boomerang tears"],
    [6, "Tears up + range down"],
    [7, "DMG up"],
    [8, "Friends 'till the end"],
    [9, "Fly love"],
    [10, "Projectile protection"],
    [11, "Extra life"],
    [12, "All stats up!"],
    [13, "Poison touch + speed up"],
    [14, "Speed and range up"],
    [15, "HP up"],
    [16, "HP up"],
    [17, "99 keys"],
    [18, "$$$"],
    [19, "10 bombs"],
    [20, "We all float down here..."],
    [21, "The end is near"],
    [22, "HP up"],
    [23, "HP up"],
    [24, "HP up"],
    [25, "HP up"],
    [26, "HP up"],
    [27, "Speed up"],
    [28, "Speed up"],
    [29, "Range up"],
    [30, "Range up"],
    [31, "Range up"],
    [32, "Tears up"],
    [33, "Temporary flight"],
    [34, "Temporary DMG up"],
    [35, "Mass room damage"],
    [36, "Plop!"],
    [37, "Reusable bomb buddy"],
    [38, "Reusable tear burst"],
    [39, "Mass paralysis"],
    [40, "Become the bomb!"],
    [41, "Mass fear"],
    [42, "Reusable ranged bomb"],
    [44, "Teleport!"],
    [45, "Reusable regeneration"],
    [46, "Luck up"],
    [47, "Reusable air strike"],
    [48, "Piercing shots"],
    [49, "BLLLARRRRGGG!"],
    [50, "DMG up"],
    [51, "DMG up"],
    [52, "???"],
    [53, "Item snatcher"],
    [54, "Full visible map"],
    [55, "Eye in the back of your head"],
    [56, "Oops..."],
    [57, "Attack fly"],
    [58, "Temporary invincibility"],
    [60, "Building bridges"],
    [62, "Kills heal"],
    [63, "Stores energy"],
    [64, "50% off"],
    [65, "Summon bombs"],
    [66, "Temporary enemy slowdown"],
    [67, "Friends 'till the end"],
    [68, "Laser tears"],
    [69, "Charge shots"],
    [70, "Speed + DMG up"],
    [71, "Speed + range up"],
    [72, "Tears + faith up"],
    [73, "Gotta meat 'em all"],
    [74, "+25 coins"],
    [75, "Better pills"],
    [76, "I've seen everything"],
    [77, "Temporary badass"],
    [78, "Reusable soul protection"],
    [79, "DMG + speed up"],
    [80, "DMG + tears up"],
    [81, "9 lives"],
    [82, "Demon wings"],
    [83, "Temporary demon form"],
    [84, "Reusable level skip"],
    [85, "Reusable card generator "],
    [86, "Summon Monstro"],
    [87, "Cross tears"],
    [88, "Attack buddy"],
    [89, "Slow effect"],
    [90, "DMG up"],
    [91, "See-through doors"],
    [92, "+2 hearts"],
    [93, "Temporary Man-Pac"],
    [94, "Gives money"],
    [95, "Friends 'till the bbbbzzzt"],
    [96, "Gives kisses"],
    [97, "Reusable item generator"],
    [98, "Soul generator"],
    [99, "Sticky friend"],
    [100, "Psychic friend"],
    [101, "All stats up"],
    [102, "Reusable pill generator"],
    [103, "Poison damage"],
    [104, "Split shot"],
    [105, "Reroll your destiny"],
    [106, "Bigger boom"],
    [107, "Cut and run"],
    [108, "Damage resistance"],
    [109, "$$$ = DMG"],
    [110, "Freeze effect"],
    [111, "Toot on command"],
    [112, "Extra protection"],
    [113, "Auto-turret friend"],
    [114, "Stab stab stab"],
    [115, "Spectral tears"],
    [116, "Quicker charge"],
    [117, "Protective buddy"],
    [118, "Blood laser barrage"],
    [119, "HP up"],
    [120, "Tears + speed up, DMG down"],
    [121, "HP + DMG up, speed down"],
    [122, "Curse up"],
    [123, "Temporary buddy generator"],
    [124, "It's a mystery"],
    [125, "Homing bombs"],
    [126, "Feel my pain"],
    [127, "I don't remember..."],
    [128, "Attack fly"],
    [129, "HP up"],
    [130, "Flight + dash attack"],
    [131, "Gives bombs"],
    [132, "My Xmas present"],
    [133, "Soul converter"],
    [134, "Cursed?"],
    [135, "Portable blood bank"],
    [136, "Friends 'till the end"],
    [137, "Remote bomb detonation"],
    [138, "DMG + HP up"],
    [139, "More trinket room"],
    [140, "+5 poison bombs"],
    [141, "Ultimate grand supreme"],
    [142, "Pray for a miracle"],
    [143, "Speed + shot speed up"],
    [144, "He's greedy"],
    [145, "Reusable fly hive"],
    [146, "Reusable eternity "],
    [147, "Rocks don't stand a chance"],
    [148, "Fly revenge"],
    [149, "Explosive shots"],
    [150, "Tooth shot"],
    [151, "They grow inside"],
    [152, "Extra laser"],
    [153, "Quad shot"],
    [154, "DMG up"],
    [155, "Plop!"],
    [156, "Item martyr"],
    [157, "RAGE!"],
    [158, "I see my future"],
    [159, "Scary"],
    [160, "Holy white death"],
    [161, "Eternal life?"],
    [162, "Blessing of protection"],
    [163, "Spectral buddy"],
    [164, "Reusable flames"],
    [165, "Shot speed + damage up"],
    [166, "Reroll the basics"],
    [167, "Double shot buddy"],
    [168, "On-demand air strike"],
    [169, "Mega tears"],
    [170, "Daddy's love"],
    [171, "Mass enemy slowdown + damage"],
    [172, "My fate protects me"],
    [173, "Blessing of purity"],
    [174, "Random buddy"],
    [175, "Opens all doors..."],
    [176, "HP + shot speed up"],
    [177, "Gamble 24/7"],
    [178, "Splash!"],
    [179, "Flight eternal"],
    [180, "Toot on touch"],
    [181, "Flight + holy death"],
    [182, "Homing shots + DMG up"],
    [183, "Tears + shot speed up"],
    [184, "Flight + HP up"],
    [185, "Flight + spectral tears"],
    [186, "Mass enemy damage at a cost"],
    [187, "Swing it"],
    [188, "Mirrored buddy"],
    [189, "All stats up"],
    [190, "99 bombs"],
    [191, "Rainbow tears"],
    [192, "Temporary psychic shot"],
    [193, "DMG + HP up"],
    [194, "Shot speed up"],
    [195, "What's all this...?"],
    [196, "Tears up"],
    [197, "Damage + range up"],
    [198, "Stuff"],
    [199, "Better chest loot +2 keys"],
    [200, "Charm tears"],
    [201, "DMG up + concussive tears"],
    [202, "Golden touch"],
    [203, "1+1 free 4Evar"],
    [204, "Filled with goodies"],
    [205, "Infinite charge... at a cost"],
    [206, "DMG + tears up. An out-of-body experience!"],
    [207, "Gotta lick 'em all!"],
    [208, "DMG + challenge up"],
    [209, "Toxic blast +5 bombs"],
    [210, "Unbreakable"],
    [211, "Spider revenge"],
    [212, "Eternal life?"],
    [213, "Shielded tears"],
    [214, "Toxic blood"],
    [215, "He accepts your offering"],
    [216, "DMG + evil up"],
    [217, "You feel itchy..."],
    [218, "Regeneration + HP up"],
    [219, "HP up"],
    [220, "Tear blasts +5 bombs"],
    [221, "Bouncing tears"],
    [222, "Anti-gravity tears + tears up"],
    [223, "It hurts so good +5 bombs"],
    [224, "Bursting shots + tears up"],
    [225, "Sweet suffering"],
    [226, "HP up x3"],
    [227, "My life savings"],
    [228, "Fear shot + tears up"],
    [229, "Charged burst attack"],
    [230, "Evil + DMG up + fear shot"],
    [231, "Sticky feet..."],
    [232, "Let's slow this down a bit..."],
    [233, "Orbiting tears + range up"],
    [234, "Infestation shot"],
    [236, "Turdy touch"],
    [237, "Piercing shots + DMG up"],
    [238, "???"],
    [239, "???"],
    [240, "Some stats up, some stats down"],
    [241, "Wealth... but at what cost?"],
    [242, "Blocks damage... sometimes"],
    [243, "You feel guarded"],
    [244, "It's still being tested..."],
    [245, "Double shot"],
    [246, "Secrets"],
    [247, "Your friends rule"],
    [248, "Giant spiders and flies"],
    [249, "More options"],
    [250, "1+1 BOOM!"],
    [251, "Extra card room"],
    [252, "Extra pill room"],
    [253, "HP + luck up"],
    [254, "DMG + range up"],
    [255, "Tears + shot speed up"],
    [256, "Burning blast +5 bombs"],
    [257, "Flaming tears"],
    [258, "Syntax error"],
    [259, "DMG up + fear shot"],
    [260, "Curse immunity + evil up"],
    [261, "Short range mega tears"],
    [262, "Evil up. Your enemies will pay!"],
    [263, "Rune mimic"],
    [264, "Revenge fly"],
    [265, "Immortal friend"],
    [266, "Sticky babies"],
    [267, "We worked out all the kinks"],
    [268, "Infested friend"],
    [269, "Bloody friend"],
    [270, "Blood sucker"],
    [271, "?"],
    [272, "Big Beautiful Fly"],
    [273, "Explosive thoughts"],
    [274, "Sworn protector"],
    [275, "Evil friend"],
    [276, "Protect it"],
    [277, "Fear him"],
    [278, "He wants to take your life"],
    [279, "Fat protector"],
    [280, "She loves you"],
    [281, "Scape goat"],
    [282, "It's time you learned how"],
    [283, "REEROLLLLL!"],
    [284, "Reroll into something else"],
    [285, "Reroll enemies"],
    [286, "Card mimic"],
    [287, "Tome of knowledge"],
    [288, "It's a box of spiders"],
    [289, "Flame on"],
    [290, "Save your life"],
    [291, "..."],
    [292, "Reusable evil... but at what cost?"],
    [293, "Krampus rage"],
    [294, "Reusable knock-back"],
    [295, "Pay to win"],
    [296, "Convert your soul"],
    [297, "? ?"],
    [298, "You feel stumped"],
    [299, "Speed down + rage is building"],
    [300, "Ramming speed"],
    [301, "HP up + you feel protected"],
    [302, "Stompy"],
    [303, "You feel refreshed and protected"],
    [304, "You feel balanced"],
    [305, "Poison tears"],
    [306, "Piercing shots + speed up"],
    [307, "All stats up"],
    [308, "Trail of tears"],
    [309, "Tears up + knock-back shot"],
    [310, "DMG up, tears + shot speed down"],
    [311, "Sweet revenge"],
    [312, "HP up + you feel healthy"],
    [313, "Holy shield"],
    [314, "HP up + speed down + you feel stompy"],
    [315, "Magnetic tears"],
    [316, "Cursed charge shot"],
    [317, "Toxic splash damage"],
    [318, "Conjoined friend"],
    [319, "Near-sighted friend"],
    [320, "Controlled friend"],
    [321, "The ol' ball and chain"],
    [322, "Mongo friend"],
    [323, "Collected tears"],
    [324, "Undefined"],
    [325, "Lose your head"],
    [326, "Invincibility at a cost"],
    [327, "Fate chosen"],
    [328, "Fate chosen"],
    [329, "Controlled tears"],
    [330, "DMG down + tears way up"],
    [331, "God tears"],
    [332, "Eternal life?"],
    [333, "I know all"],
    [334, "I feel all"],
    [335, "I am all"],
    [336, "Toxic aura tears"],
    [337, "I think it's broken"],
    [338, "It will never leave you"],
    [339, "Evil + range + shot speed up"],
    [340, "Speed up + size down"],
    [341, "Tears + shot speed up"],
    [342, "HP + tears up + shot speed down"],
    [343, "Luck up"],
    [344, "Evil up"],
    [345, "DMG + range up"],
    [346, "HP up"],
    [347, "Double item vision"],
    [348, "Pill mimic"],
    [349, "Flip a coin"],
    [350, "Mass poison"],
    [351, "Giga fart!"],
    [352, "Be gentle..."],
    [353, "Cross blast + 5 bombs"],
    [354, "HP up. Don't swallow the prize!"],
    [355, "Range + luck up"],
    [356, "Active power up"],
    [357, "Double your friends"],
    [358, "Double wiz shot!"],
    [359, "Stick it to 'em!"],
    [360, "Dark friend"],
    [361, "Your fate beside you"],
    [362, "What's in the box?"],
    [363, "Protective friend"],
    [364, "Friendly fly"],
    [365, "Lost protector"],
    [366, "We put bombs in your bombs!"],
    [367, "Egg sack bombs!"],
    [368, "Intensifying tears"],
    [369, "Transcendent tears"],
    [370, "Range + tears up"],
    [371, "Embrace chaos"],
    [372, "Bbbzzzzzt! "],
    [373, "Accuracy brings power"],
    [374, "Holy death shot"],
    [375, "Blast resistance"],
    [376, "Never ending stores!"],
    [377, "Spider love"],
    [378, "Uh oh..."],
    [379, "Wide shot"],
    [380, "Money talks"],
    [381, "Tears up + your future shines brighter"],
    [382, "Gotta fetch 'em all!"],
    [383, "Remote tear detonation"],
    [384, "A gurd of your own!"],
    [385, "Bumbo want coin!"],
    [386, "Rerolls rocks"],
    [387, "Peace be with you"],
    [388, "He wants your keys!"],
    [389, "Rune generator"],
    [390, "Sworn friend"],
    [391, "Turn your enemy"],
    [392, "The heavens will change you"],
    [393, "The kiss of death"],
    [394, "Directed tears"],
    [395, "Laser ring tears"],
    [396, "Short cutter"],
    [397, "Controlled tears"],
    [398, "Shrink shot!"],
    [399, "Consume thy enemy!"],
    [400, "Your destiny"],
    [401, "Sticky bomb shot"],
    [402, "!!!"],
    [403, "Mod buddy"],
    [404, "He farts"],
    [405, "Double tap glitch"],
    [406, "Reroll stats"],
    [407, "Aura stat boost"],
    [408, "Call to the void"],
    [409, "I reward an empty vessel"],
    [410, "Eye shot"],
    [411, "Their blood brings rage!"],
    [412, "Feed them hate"],
    [413, "Feed them love"],
    [414, "There's options"],
    [415, "The untainted gain power"],
    [416, "More money!"],
    [417, "Damage booster"],
    [418, "Rainbow effects!"],
    [419, "I-Teleport!"],
    [420, "Spin the black circle!"],
    [421, "Love toots"],
    [422, "Turn back time"],
    [423, "Protect me from myself"],
    [424, "More sacks!"],
    [425, "Scared of the dark?"],
    [426, "Follows my every move..."],
    [427, "Booom!"],
    [428, "You feel cozy"],
    [429, "Penny tears"],
    [430, "Turret follower"],
    [431, "ydduB Buddy"],
    [432, "Prize bombs"],
    [433, "Me! And my shaaaadow!"],
    [434, "Bug catcher"],
    [435, "4-way buddy!"],
    [436, "Don't cry over it..."],
    [437, "Roll again"],
    [438, "Tears up"],
    [439, "What's inside?"],
    [440, "Matt's kidney stone"],
    [441, "Laser breath"],
    [442, "Loss is power"],
    [443, "Trick or treat?"],
    [444, "He's a bleeder!"],
    [445, "Bark at the moon!"],
    [446, "Toxic breath"],
    [447, "Crying makes me toot"],
    [448, "Blood and guts!"],
    [449, "It itches..."],
    [450, "Gold tears!"],
    [451, "I see the future"],
    [452, "I'm leaking..."],
    [453, "Bone tears!"],
    [454, "Hold me!"],
    [455, "I remember this..."],
    [456, "HP up"],
    [457, "Hard headed!"],
    [458, "What's in there?"],
    [459, "Booger tears!"],
    [460, "Blind tears!"],
    [461, "Egg tears!"],
    [462, "Possessed tears!"],
    [463, "Acid tears!"],
    [464, "A gift from above"],
    [465, "360 tears!"],
    [466, "Outbreak!"],
    [467, "Watch where you point that!"],
    [468, "It follows"],
    [469, ":("],
    [470, "Lil hush!"],
    [471, "Ain't he cute?"],
    [472, "Hail to the king baby"],
    [473, "Chub chub"],
    [474, "You broke it!"],
    [475, "My last resort"],
    [476, "What will it be?"],
    [477, "Consume"],
    [478, "Stop!"],
    [479, "Trinket melter!"],
    [480, "Gain more friends!"],
    [481, "109"],
    [482, "Change"],
    [483, "BOOOOOOOOOM!"],
    [484, "I can't believe it's not butter bean!"],
    [485, "50/50"],
    [486, "I feel numb..."],
    [487, "A pound of flesh..."],
    [488, "Waggles a finger"],
    [489, "Reroll forever"],
    [490, "..."],
    [491, "Pills pills pills!"],
    [492, "Yo listen!"],
    [493, "Panic = power"],
    [494, "Electric tears"],
    [495, "Flame tears"],
    [496, "Needle shot"],
    [497, "Camo kid"],
    [498, "You feel very balanced"],
    [499, "Peace be with you"],
    [500, "Gives sacks"],
    [501, "Money = health!"],
    [502, "Creep shots"],
    [503, "Big brother is watching"],
    [504, "Friendly fly"],
    [505, "Gotta catch em..."],
    [506, "Watch your back!"],
    [507, "More blood!"],
    [508, "It's sharp!"],
    [509, "Bloody friend"],
    [510, "Unleash the power!"],
    [511, "He's violent"],
    [512, "Nothing can escape"],
    [513, "Party time!"],
    [514, "Lag!"],
    [515, "Wrapped up nice for you!"],
    [516, "Sprinkles."],
    [517, "Rapid bomb drops"],
    [518, "What could it be?!"],
    [519, "Delirious friend"],
    [520, "Bloody recharge"],
    [521, "Allow 6 weeks for delivery"],
    [522, "Power of the mind"],
    [523, "Pack and unpack"],
    [524, "Static tears"],
    [525, "You're tearing me apart!"],
    [526, "Lil harbingers!"],
    [527, "Caaan do!"],
    [528, "Eclipsed by the moon"],
    [529, "Eyeball tears"],
    [530, "Just hope you're not next..."],
    [531, "I'm seeing red..."],
    [532, "Feed them!"],
    [533, "Smite thy enemy"],
    [534, "Extra active item room"],
    [535, "You feel safe"],
    [536, "He demands a sacrifice"],
    [537, "Puking buddy"],
    [538, "Choking hazard"],
    [539, "Sacrificial insemination"],
    [540, "Skipping tears"],
    [541, "HP up?"],
    [542, "Projectile shield"],
    [543, "Portable sanctuary"],
    [544, "Stabbing time"],
    [545, "Rise from the grave"],
    [546, "Father's blessing"],
    [547, "Tears up + you feel empty"],
    [548, "Fetch!"],
    [549, "Everything hurts"],
    [550, "It feels cursed"],
    [551, "It feels cursed"],
    [552, "Lost but not forgotten"],
    [553, "Spore shot"],
    [554, "4me"],
    [555, "Pain from gain"],
    [556, "Temporary demon form"],
    [557, "Reusable fortunes"],
    [558, "More eyes"],
    [559, "Zap!"],
    [560, "No it doesn't..."],
    [561, "DMG down + tears up + you feel nutty"],
    [562, "It's only up from there"],
    [563, "Random blast +5 bombs"],
    [564, "Tears + shot speed up"],
    [565, "What a cute little thing!"],
    [566, "Sweet dreams"],
    [567, "Keep the flame burning"],
    [568, "Double tap shield"],
    [569, "Bleed me dry"],
    [570, "Tasty rainbow"],
    [571, "Speed up + your feet feel stronger"],
    [572, "DMG up + range up + controlled tears"],
    [573, "Halo of tears"],
    [574, "Purifying light"],
    [575, "Invasive friend"],
    [576, "Filthy friends"],
    [577, "A king's fortune... but at what cost?"],
    [578, "Party time!"],
    [579, "Divine blade"],
    [580, "Explore the other side"],
    [581, "Flamboyant protector"],
    [582, "Tears up. A mind changing experience!"],
    [583, "Rocket propulsion +5 bombs"],
    [584, "Spiritual companionship"],
    [585, "A sacred offering"],
    [586, "May you get what you came for"],
    [588, "Radiant victory"],
    [589, "The moon's blessing shines upon you"],
    [590, "Speed up + you feel elusive"],
    [591, "HP up + you feel pretty"],
    [592, "Born to rock"],
    [593, "Double tap dash"],
    [594, "You're a gas giant!"],
    [595, "Ring of tears"],
    [596, "Ice tears"],
    [597, "Open the floodgates"],
    [598, "Size down"],
    [599, "Extra curse rooms"],
    [600, "Tears up"],
    [601, "Tears up, you feel forgiven"],
    [602, "Exclusive access!"],
    [603, "Instant energy!"],
    [604, "Mother's strength"],
    [605, "Plop!"],
    [606, "Stare into the abyss"],
    [607, "Messy friend"],
    [608, "Iced iced baby"],
    [609, "???"],
    [610, "Fat buddy"],
    [611, "Hear my pain"],
    [612, "Protect him"],
    [614, "Bloody blast + HP up"],
    [615, "Puffy buddy"],
    [616, "It burns"],
    [617, "Magnetizing tears"],
    [618, "Delicious!"],
    [619, "???"],
    [621, "Full HP + temporary DMG up"],
    [622, "In the beginning"],
    [623, "Open your enemies"],
    [624, "Collect them all!"],
    [625, "I'm a big boy now!"],
    [626, "???"],
    [627, "???"],
    [628, "Where am I?"],
    [629, "Defense drone"],
    [631, "Slice but no dice"],
    [632, "Luck up + you feel protected"],
    [633, "Ascended"],
    [634, "Help from beyond"],
    [635, "Bait and switch"],
    [636, "Time to start over"],
    [637, "They pack a punch!"],
    [638, "Erase thy enemy"],
    [639, "Gross!"],
    [640, "Unleash their sorrow"],
    [641, "Spill your guts"],
    [642, "All your desires fulfilled"],
    [643, "Awaken your faith"],
    [644, "+1 to lowest stat"],
    [645, "Itching for revenge"],
    [646, "Demon blast +5 bombs"],
    [647, "Beat the juice out of them!"],
    [649, "Bouncy friend"],
    [650, "Play time!"],
    [651, "Follow the light"],
    [652, "Kick it!"],
    [653, "Begone!"],
    [654, "Worse pills + evil up"],
    [655, "Let it rip!"],
    [656, "A king's fortune... but at what cost?"],
    [657, "Clogged enemies"],
    [658, "Micro friends"],
    [659, "Tear size + range up"],
    [660, "A link to your future"],
    [661, "They lurk inside"],
    [663, "You feel prickly"],
    [664, "All you can eat"],
    [665, "An eye for secrets"],
    [667, "A helping hand"],
    [668, "..."],
    [669, "All stats up"],
    [670, "There might be options"],
    [671, "Power of love"],
    [672, "Blood money"],
    [673, "Deliver me from evil"],
    [674, "Unfinished business"],
    [675, "Shards of knowledge"],
    [676, "It multiplies"],
    [677, "The true out-of-body experience!"],
    [678, "Fetus shots"],
    [679, "Abyssal friend"],
    [680, "Oh no..."],
    [681, "It hungers"],
    [682, "Clingy buddy"],
    [683, "Break your enemies"],
    [684, "Out for blood"],
    [685, "Your faith grows"],
    [686, "Power of faith"],
    [687, "Best friends forever!"],
    [688, "Let him free"],
    [689, "?????"],
    [690, "Bounce away!"],
    [691, "Destined for greatness"],
    [692, "He awaits your offering"],
    [693, "Infest"],
    [694, "Eternal sorrow"],
    [695, "May your rage bring haste"],
    [696, "Divine protection"],
    [697, "He wants revenge"],
    [698, "Double trouble!"],
    [699, "Ancient power"],
    [700, "I can see see the future future future"],
    [701, "Buried memories"],
    [702, "Hot blooded"],
    [703, "Lost brother"],
    [704, "Rip and tear"],
    [705, "One with the shadows"],
    [706, "Come forth from the depths"],
    [707, "HP up"],
    [708, "DMG up"],
    [709, "Angel breaker"],
    [710, "Make your destiny"],
    [711, "Life and death"],
    [712, "Item summoner"],
    [713, "Return"],
    [714, "Come back"],
    [715, "Saved for later"],
    [716, "Spending power"],
    [717, "Under a rock"],
    [719, "Portable shop"],
    [720, "Anything is possible"],
    [721, "Isaac and his mother lived alone in a small house on a hill"],
    [722, "Repent"],
    [723, "-1"],
    [724, "Thick blooded"],
    [725, "Your stomach rumbles"],
    [726, "Double tap sneeze"],
    [727, "Spooky blast +5 bombs"],
    [728, "Demonic gestation"],
    [729, "Chuck away!"],
    [730, "DMG + luck up"],
    [731, "DMG + range up"],
    [732, "DMG up"],
  ]);
