import { TrinketType } from "isaac-typescript-definitions";

export const DEFAULT_TRINKET_NAME = "Unknown";

// This is a temporary map due to missing features in the vanilla API. (Otherwise, this would be
// converted to a type-safe object.)
export const TRINKET_NAME_MAP: ReadonlyMap<TrinketType, string> = new Map([
  [1, "Swallowed Penny"],
  [2, "Petrified Poop"],
  [3, "AAA Battery"],
  [4, "Broken Remote"],
  [5, "Purple Heart"],
  [6, "Broken Magnet"],
  [7, "Rosary Bead"],
  [8, "Cartridge"],
  [9, "Pulse Worm"],
  [10, "Wiggle Worm"],
  [11, "Ring Worm"],
  [12, "Flat Worm"],
  [13, "Store Credit"],
  [14, "Callus"],
  [15, "Lucky Rock"],
  [16, "Mom's Toenail"],
  [17, "Black Lipstick"],
  [18, "Bible Tract"],
  [19, "Paper Clip"],
  [20, "Monkey Paw"],
  [21, "Mysterious Paper"],
  [22, "Daemon's Tail"],
  [23, "Missing Poster"],
  [24, "Butt Penny"],
  [25, "Mysterious Candy"],
  [26, "Hook Worm"],
  [27, "Whip Worm"],
  [28, "Broken Ankh"],
  [29, "Fish Head"],
  [30, "Pinky Eye"],
  [31, "Push Pin"],
  [32, "Liberty Cap"],
  [33, "Umbilical Cord"],
  [34, "Child's Heart"],
  [35, "Curved Horn"],
  [36, "Rusted Key"],
  [37, "Goat Hoof"],
  [38, "Mom's Pearl"],
  [39, "Cancer"],
  [40, "Red Patch"],
  [41, "Match Stick"],
  [42, "Lucky Toe"],
  [43, "Cursed Skull"],
  [44, "Safety Cap"],
  [45, "Ace of Spades"],
  [46, "Isaac's Fork"],
  [48, "A Missing Page"],
  [49, "Bloody Penny"],
  [50, "Burnt Penny"],
  [51, "Flat Penny"],
  [52, "Counterfeit Penny"],
  [53, "Tick"],
  [54, "Isaac's Head"],
  [55, "Maggy's Faith"],
  [56, "Judas' Tongue"],
  [57, "???'s Soul"],
  [58, "Samson's Lock"],
  [59, "Cain's Eye"],
  [60, "Eve's Bird Foot"],
  [61, "The Left Hand"],
  [62, "Shiny Rock"],
  [63, "Safety Scissors"],
  [64, "Rainbow Worm"],
  [65, "Tape Worm"],
  [66, "Lazy Worm"],
  [67, "Cracked Dice"],
  [68, "Super Magnet"],
  [69, "Faded Polaroid"],
  [70, "Louse"],
  [71, "Bob's Bladder"],
  [72, "Watch Battery"],
  [73, "Blasting Cap"],
  [74, "Stud Finder"],
  [75, "Error"],
  [76, "Poker Chip"],
  [77, "Blister"],
  [78, "Second Hand"],
  [79, "Endless Nameless"],
  [80, "Black Feather"],
  [81, "Blind Rage"],
  [82, "Golden Horse Shoe"],
  [83, "Store Key"],
  [84, "Rib of Greed"],
  [85, "Karma"],
  [86, "Lil Larva"],
  [87, "Mom's Locket"],
  [88, "NO!"],
  [89, "Child Leash"],
  [90, "Brown Cap"],
  [91, "Meconium"],
  [92, "Cracked Crown"],
  [93, "Used Diaper"],
  [94, "Fish Tail"],
  [95, "Black Tooth"],
  [96, "Ouroboros Worm"],
  [97, "Tonsil"],
  [98, "Nose Goblin"],
  [99, "Super Ball"],
  [100, "Vibrant Bulb"],
  [101, "Dim Bulb"],
  [102, "Fragmented Card"],
  [103, "Equality!"],
  [104, "Wish Bone"],
  [105, "Bag Lunch"],
  [106, "Lost Cork"],
  [107, "Crow Heart"],
  [108, "Walnut"],
  [109, "Duct Tape"],
  [110, "Silver Dollar"],
  [111, "Bloody Crown"],
  [112, "Pay To Win"],
  [113, "Locust of War"],
  [114, "Locust of Pestilence"],
  [115, "Locust of Famine"],
  [116, "Locust of Death"],
  [117, "Locust of Conquest"],
  [118, "Bat Wing"],
  [119, "Stem Cell"],
  [120, "Hairpin"],
  [121, "Wooden Cross"],
  [122, "Butter!"],
  [123, "Filigree Feather"],
  [124, "Door Stop"],
  [125, "Extension Cord"],
  [126, "Rotten Penny"],
  [127, "Baby-Bender"],
  [128, "Finger Bone"],
  [129, "Jawbreaker"],
  [130, "Chewed Pen"],
  [131, "Blessed Penny"],
  [132, "Broken Syringe"],
  [133, "Short Fuse"],
  [134, "Gigante Bean"],
  [135, "A Lighter"],
  [136, "Broken Padlock"],
  [137, "Myosotis"],
  [138, " 'M"],
  [139, "Teardrop Charm"],
  [140, "Apple of Sodom"],
  [141, "Forgotten Lullaby"],
  [142, "Beth's Faith"],
  [143, "Old Capacitor"],
  [144, "Brain Worm"],
  [145, "Perfection"],
  [146, "Devil's Crown"],
  [147, "Charged Penny"],
  [148, "Friendship Necklace"],
  [149, "Panic Button"],
  [150, "Blue Key"],
  [151, "Flat File"],
  [152, "Telescope Lens"],
  [153, "Mom's Lock"],
  [154, "Dice Bag"],
  [155, "Holy Crown"],
  [156, "Mother's Kiss"],
  [157, "Torn Card"],
  [158, "Torn Pocket"],
  [159, "Gilded Key"],
  [160, "Lucky Sack"],
  [161, "Wicked Crown"],
  [162, "Azazel's Stump"],
  [163, "Dingle Berry"],
  [164, "Ring Cap"],
  [165, "Nuh Uh!"],
  [166, "Modeling Clay"],
  [167, "Polished Bone"],
  [168, "Hollow Heart"],
  [169, "Kid's Drawing"],
  [170, "Crystal Key"],
  [171, "Keeper's Bargain"],
  [172, "Cursed Penny"],
  [173, "Your Soul"],
  [174, "Number Magnet"],
  [175, "Strange Key"],
  [176, "Lil Clot"],
  [177, "Temporary Tattoo"],
  [178, "Swallowed M80"],
  [179, "RC Remote"],
  [180, "Found Soul"],
  [181, "Expansion Pack"],
  [182, "Beth's Essence"],
  [183, "The Twins"],
  [184, "Adoption Papers"],
  [185, "Cricket Leg"],
  [186, "Apollyon's Best Friend"],
  [187, "Broken Glasses"],
  [188, "Ice Cube"],
  [189, "Sigil of Baphomet"],
]);
